### ISSUE TITLE
RTD/doc search results call Julia functions Python functions instead

### ISSUE THREAD

**Issue by randyzwitch** [JuliaLang/julia#11527]
I wanted to read the documentation for `Base.copy`, and to my surprise the labels reference them as Python functions. 

Did someone do a bulk overwrite on the docs? Here's the link and a screenshot

http://julia.readthedocs.org/en/latest/search/?q=copy&check_keywords=yes&area=default

![screen shot 2015-06-01 at 4 30 23 pm](https://cloud.githubusercontent.com/assets/2762787/7922634/95819c28-087b-11e5-98e2-bd249356343a.png)

**Comment by pao** [comment]
Probably a Sphinx default that we fail to override. Fix will probably be in JuliaDoc. Research time!

**Comment by pao** [comment]
Yes, the Julia domain inherits directly from the Python domain, with some overrides. I think this only affects search results.

**Comment by pao** [comment]
I have no idea where this can be coming from--[the only string reference to "Python"](http://fossies.org/dox/Sphinx-1.3.1/python_8py_source.html#l00587) in the domain [we do in fact replace](https://github.com/JuliaLang/JuliaDoc/blob/master/juliadoc/julia.py#L18), [the default domain is set to "jl"](https://github.com/JuliaLang/julia/blob/acc29933a96267bdd039d2abfa100f301edca536/doc/conf.py#L96) in config.py, and there is no translation done ([language is set to default](https://github.com/JuliaLang/julia/blob/acc29933a96267bdd039d2abfa100f301edca536/doc/conf.py#L64) which is `None`) so the i18n engine can't be inserting it.

**Comment by yuyichao** [comment]
This only happens for the "latest" doc. Is there any difference between the latest and the 0.3 version?

**Comment by yuyichao** [comment]
And the Julia-CN doc search is also correct.

**Comment by pao** [comment]
Except the search index might still be getting a translation?

```
dumping search index in English (code: en) ... done
```

**Comment by pao** [comment]
Hrm...that's weird. I at least confirmed that the translation files aren't at fault. This looks like something thinks this reference is cross-domain (otherwise it would just be "function" according to the documentation of config.py).

**Comment by pao** [comment]
Changes in JuliaDoc between version used on release-0.3 and master: https://github.com/JuliaLang/JuliaDoc/compare/0dd9903f12f21140d46ceae9b30088ec40e353d6...012be05a6a704fbdce09ff5c3f060930d6d427f9

It doesn't appear that much has been done to conf.py that hasn't been backported, either, just some changes to the sidebars. Nothing that should be influencing this.

**Comment by yuyichao** [comment]
So both of them are generated nightly as well?

**Comment by pao** [comment]
They are both generated on a branch push (there's a webook that GitHub issues.)

**Comment by yuyichao** [comment]
It appears to be OK now???

**Comment by yuyichao** [comment]
Did anyone do anything and can this be closed now?

**Comment by pao** [comment]
Didn't do a darn thing, but confirm fixed. I assume this is somehow RTD's doing.

**Comment by yuyichao** [comment]
@pao Sorry to bother you again but the problem seems to be back .......

**Comment by yuyichao** [comment]
Still only for `0.4`

**Comment by yuyichao** [comment]
Ping. @pao ? The search result is still showing "Python Function" now...

**Comment by pao** [comment]
We literally don't control this in any way, as proven by the fact it changed, then changed back, without touching anything. Perhaps we should bring it up with RTD.

**Comment by yuyichao** [comment]
Do they have a tracker?

**Comment by agjohnson** [comment]
RTD hasn't made any changes that would have affected this, I do see what looks like a corrupted build env on one of the servers however. This could result in transient failures like this -- though still not sure why the failure case generates invalid indexed titles.

**Comment by agjohnson** [comment]
Oh, and with maintainer status on the project, you can trigger a environment wipe on the project's version page:
https://readthedocs.org/projects/julia/versions/

**Comment by pao** [comment]
cc @nolta @StefanKarpinski would one of you be able to trigger the environment wipe for `latest`?

**Comment by StefanKarpinski** [comment]
Actually, I don't think I'm an admin on this. At least I don't see it on my read the docs dashboard. @nolta – could you add @pao and myself?

**Comment by nolta** [comment]
Ok, added and wiped.

**Comment by pao** [comment]
That does not appear to have fixed it.

**Comment by agjohnson** [comment]
Okay, after a deep dark rabbit hole, the domain in your docs now has the proper prefix on the latest build :)

This is using the same server that was problematic before, so hopefully this makes the builds consistent.

**Comment by pao** [comment]
Deep and dark, indeed. Thanks for taking a look, and for the fix.

**Comment by pao** [comment]
@agjohnson Sorry to bother you again, but the original issue reported here ("Python function" showing up in search results) is still present; are we waiting for the fix to be pushed to RTD in production? Or did I misunderstand what all got fixed (was it just the environment installation problem)?

**Comment by agjohnson** [comment]
@pao It was fixed, but seems one of the other build servers we are decommissioning has the outdated readthedocs-sphinx-ext 0.5.3 package, I'll update all of the build servers this morning.

**Comment by pao** [comment]
Got it, thanks for the clarification.

**Comment by tkelman** [comment]
I don't see "Python function" any more, looks fixed now.

**Comment by yuyichao** [comment]
Fixed here too. Hopefully it won't come back anymore.....

**Comment by yuyichao** [comment]
@agjohnson @pao It comes back for me again right now and IIRC at least once in the past week.

**Comment by pao** [comment]
Seems to be transient (most recent works for me right now)--maybe one of their build servers is/was still not updated?

**Comment by agjohnson** [comment]
We just rolled all new build servers, so there may have been a point where the old extension was being pulled in. Definitely raise the issue on our tracker if it comes up again.

**Comment by pao** [comment]
Will do, thanks.

**Comment by yuyichao** [comment]
@agjohnson It is "Python function" at this moment again.... (and IIRC was correct sometime yesterday)

**Comment by yuyichao** [comment]
Reported at https://github.com/rtfd/readthedocs.org/issues/1382

**Comment by tkelman** [comment]
Depending on when it was built, this could easily have something to do with #11906 ?

**Comment by hayd** [comment]
It's now back to saying Julia function, but it's been off and on this entire time.

**Comment by pao** [comment]
@tkelman, since none of that has touched the definitions in JuliaDoc, we shouldn't be able to break it from within the doc sources themselves, unless we explicitly generated rst which specifies that they are Python functions. Julia is the default type.

**Comment by yuyichao** [comment]
Doesn't seems seems to be referenced here so https://github.com/JuliaLang/JuliaDoc/issues/16

**Comment by JeffBezanson** [comment]
This is fixed and superseded by the new doc system.
