### ISSUE TITLE
constructing array with typemax(Int64)/2 range

### ISSUE THREAD

**Issue by Vesalon** [JuliaLang/julia#11552]
I was looking to make a large array and attempted to make one with typemax(Int64) elements and wasn't able to, so I tried to simply make one of half the size, using any other numbers didn't cause this error

```
julia> [1:typemax(Int64)]
ERROR: invalid Array size
 in vcat at range.jl:501

julia> [1:typemax(Int64)]
ERROR: invalid Array size
 in vcat at range.jl:501

julia> x = typemax(Int64)
9223372036854775807

julia> [1:x]
ERROR: invalid Array size
 in vcat at range.jl:501

julia> [1:x/2]

Please submit a bug report with steps to reproduce this fault, and any error mes
sages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x2a080b7 -- vcat at range.jl:505
vcat at range.jl:505
jlcall_vcat_1067 at  (unknown line)
jl_apply_generic at C:\Users\Ves\AppData\Local\Julia-0.3.8\bin\libjulia.dll (unk
nown line)
jl_interpret_toplevel_expr at C:\Users\Ves\AppData\Local\Julia-0.3.8\bin\libjuli
a.dll (unknown line)
jl_interpret_toplevel_thunk_with at C:\Users\Ves\AppData\Local\Julia-0.3.8\bin\l
ibjulia.dll (unknown line)
jl_eval_with_compiler_p at C:\Users\Ves\AppData\Local\Julia-0.3.8\bin\libjulia.d
ll (unknown line)
jl_f_top_eval at C:\Users\Ves\AppData\Local\Julia-0.3.8\bin\libjulia.dll (unknow
n line)
eval_user_input at REPL.jl:53
jlcall_eval_user_input_1065 at  (unknown line)
jl_apply_generic at C:\Users\Ves\AppData\Local\Julia-0.3.8\bin\libjulia.dll (unk
nown line)
anonymous at task.jl:95
jl_handle_stack_switch at C:\Users\Ves\AppData\Local\Julia-0.3.8\bin\libjulia.dl
l (unknown line)
julia_trampoline at C:\Users\Ves\AppData\Local\Julia-0.3.8\bin\libjulia.dll (unk
nown line)
unknown function (ip: 4202784)
unknown function (ip: 4199370)
unknown function (ip: 4199672)
BaseThreadInitThunk at C:\windows\system32\kernel32.dll (unknown line)
RtlUserThreadStart at C:\windows\SYSTEM32\ntdll.dll (unknown line)
RtlUserThreadStart at C:\windows\SYSTEM32\ntdll.dll (unknown line)
```

using typemax(Int32) and typemax(Int32)/2 did not cause this error

```
julia> x = Int32
Int32

julia> x = typemax(Int32)
2147483647

julia> [1:x]
ERROR: MemoryError()
 in vcat at range.jl:501

julia> [1:x/2]
ERROR: MemoryError()
 in vcat at range.jl:501

julia>
```

**Comment by quinnj** [comment]
Possibly solved by #11491 (with a backport)

**Comment by jakebolewski** [comment]
I still see this error:

```julia
julia> x = typemax(Int64)
9223372036854775807

julia> [1:x]
ERROR: invalid Array size
 in vcat at ./range.jl:662
 in vect at abstractarray.jl:33

julia> [1:x/2]

signal (4): Illegal instruction: 4
vcat at range.jl:664
jl_apply at /Users/jacobbolewski/Julia/julia-dev/src/gf.c:1657
[1]    75509 illegal hardware instruction  /Users/jacobbolewski/Julia/julia-dev/usr/bin/julia
```

I'm going to attach a gc tag to bait @carnaval into fixing this.

**Comment by mauro3** [comment]
This works now:
```
              _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc1+1 (2016-08-05 15:23 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit acfd04c* (2 days old release-0.5)
|__/                   |  x86_64-pc-linux-gnu

julia> x = typemax(Int64)
9223372036854775807

julia> [1:x]
1-element Array{UnitRange{Int64},1}:
 1:9223372036854775807

julia> [1:x/2]
1-element Array{FloatRange{Float64},1}:
 1.0:1.0:4.611686018427388e18
```

**Comment by yuyichao** [comment]
@mauro3 that's the new non-concatenations behavior and is not what this bug is about.

**Comment by yuyichao** [comment]
OTOH, we are properly raising OOM error afaict.

**Comment by mauro3** [comment]
Ah, yes!  Here, for those following along at home, the output when collecting:
```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-rc1+1 (2016-08-05 15:23 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit acfd04c* (3 days old release-0.5)
|__/                   |  x86_64-pc-linux-gnu

julia> x = typemax(Int64)
9223372036854775807

julia> [1:x;]
ERROR: invalid Array size
 in vcat(::UnitRange{Int64}) at ./range.jl:803

julia> [1:x/2;]

signal (11): Segmentation fault
while loading no file, in expression starting on line 0
jl_typemap_entry_assoc_exact at /home/mauro/julia/julia-0.5/src/typemap.c:797
jl_typemap_assoc_exact at /home/mauro/julia/julia-0.5/src/julia_internal.h:724 [inlined]
jl_apply_generic at /home/mauro/julia/julia-0.5/src/gf.c:1889
eval_user_input at ./REPL.jl:60
jl_call_method_internal at /home/mauro/julia/julia-0.5/src/julia_internal.h:192 [inlined]
jl_apply_generic at /home/mauro/julia/julia-0.5/src/gf.c:1930
macro expansion at ./REPL.jl:95 [inlined]
#3 at ./event.jl:46
jl_call_method_internal at /home/mauro/julia/julia-0.5/src/julia_internal.h:192 [inlined]
jl_apply_generic at /home/mauro/julia/julia-0.5/src/gf.c:1930
jl_apply at /home/mauro/julia/julia-0.5/src/julia.h:1392 [inlined]
start_task at /home/mauro/julia/julia-0.5/src/task.c:253
unknown function (ip: 0xffffffffffffffff)
Allocations: 1991730 (Pool: 1990783; Big: 947); GC: 1
zsh: segmentation fault (core dumped)  julia5
```
So, not fixed after all.

**Comment by inkydragon** [comment]
Fixed in 1.6.3.

```julia
julia> [1:typemax(Int64)]
1-element Vector{UnitRange{Int64}}:
 1:9223372036854775807

julia> [1:typemax(Int32)]
1-element Vector{UnitRange{Int64}}:
 1:2147483647

julia> [1:typemax(Int16)]
1-element Vector{UnitRange{Int64}}:
 1:32767


julia> [1:typemax(Int64)/2]
1-element Vector{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}:
 1.0:1.0:4.611686018427388e18

julia> [1:typemax(Int32)/2]
1-element Vector{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}:
 1.0:1.0:1.073741823e9

julia> [1:typemax(Int16)/2]
1-element Vector{StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}:
 1.0:1.0:16383.0
```

**Comment by KristofferC** [comment]
Perhaps a test could be added to prevent regressions in the future.

**Comment by inkydragon** [comment]
We already have some typemax tests.

https://github.com/JuliaLang/julia/blob/be28eb301323c8ca5192774112ab48023da77d49/test/ranges.jl#L948-L955

https://github.com/JuliaLang/julia/blob/be28eb301323c8ca5192774112ab48023da77d49/test/ranges.jl#L547-L551
