### ISSUE TITLE
Indentation tabs are incorrectly counted in Base.indentation (used by """...""" strings)

### ISSUE THREAD

**Issue by ScottPJones** [JuliaLang/julia#11659]
The tab character means to move over to the next tab stop, i.e. every 8 characters.
The code in `string.jl` is incorrect, it treats tabs as being == 8 spaces.
If you have 7 spaces, followed by 1 tab character, or just 1 tab character, you should move over to the same location.
This function is used in 3 places, the `triplequotation` function in `string.jl`, used to handle all """ strings,
in `REPL.jl`, and in `LineEdit.jl`

**Comment by StefanKarpinski** [comment]
You can't really count on tabs stops being every 8 characters either.

**Comment by ScottPJones** [comment]
@StefanKarpinski But it is a stop, NOT a fixed with of 8 spaces.  The code is definitely incorrect.
>In practice, settable tab stops were rather quickly replaced with fixed tab stops, de facto standardized at every multiple of 8 characters horizontally, and every 6 lines vertically (typically one inch vertically).

**Comment by ScottPJones** [comment]
Also, tab stops being by *default* 8 spaces is part of many ANSI/ISO standards, dating back to the '70s.  Go look at CSS3, for a modern one...

**Comment by hayd** [comment]
This is also useful for Markdown. The CommonMark spec asks that tabs be stopped (not fixed width) to **4** spaces. So it would be nice if there was an efficient method to do this generally.

I assume that tab stopping is done on characters within each line? (Is a line just split on \n? or \r and \r\n too?)

**Comment by ScottPJones** [comment]
@hayd I can change it to use a configurable setting, but I wouldn't actually recommend following that part of the CommonMark spec (default to 4 instead of 8) - it just goes against too many other standards...
If you really want to use something other than the standard setting of 8, then usually you need some way of indicating that to your editor, anything that prints it, etc., it's a bit of a mess...
`\n` should really set the Y position to Y+1 (i.e. next line), and `\r` sets the X position to 0, but Unix convention is that `\n` does both... (pre-OS X Mac's convention was `\r` did both, and MS-DOS & Windows follow the ASCII standard...  The tab stopping is based on the X position... `X = ((X+8) \ 8) * 8`,
where `\` is integer division.

@vtjnash Actually, my original title was correct... there is a lot more wrong with Base.indentation, not just tabs... What about things like double-width spaces, for example?

There are other issues with the unindent function... it really should strip the leading whitespace, and recreate the line with the correct indentation, respecting any tab characters after the first non-whitespace character...

**Comment by hayd** [comment]
We should following *the* CommonMark spec where possible + Github tables + LaTeX. Maybe I've misunderstood this issue. All I'm saying is if you make a function which replaces tabs to their spaces equivalent (tab stopped) this may also be useful for markdown. The newline (\r \r\n) issue is less of an issue as these should also be replaced with \n before markdown processing, but I thought it may be worth mentioning.

**Comment by ScottPJones** [comment]
@hayd  The problem with the CommonMark spec, is what happens when you print your code, and the printer driver takes all of your tabs, and expands them with width of 8?  I think that's why a lot of people (like the style guide for Julia) just say, don't use tabs ever...

**Comment by StefanKarpinski** [comment]
The original usage of this function was for unindenting triple-quoted strings. For that I would argue that we shouldn't count indentation in terms of spaces but insist that all lines have the same leading indentation and remove that, regardless of how it's spelled. I'm not sure what to do if some of the lines don't begin with that same indentation. I'm not sure what to do for the two uses of `indentation` in the REPL code.

**Comment by ScottPJones** [comment]
Whatever the original intention of these functions was, for better or worse, they are now used outside the triplequotation code, so they really should be done correctly.  (Here is where having the notion of the functions being private would have helped...)

**Comment by hayd** [comment]
Markdown is a bit of a weird one for whitespace, for the most part it is/should be ignored anyway. The CommonMark spec just says replace tabs with spaces (before parsing/ignoring - they are in html after all). Not using tabs at all is the best advice IMO.

I don't think you can expect *any* of the following:
```
* arg1\tsomething
* argtwo\tsomething
* arg_3\tsomething
```
to line up, even though they may in the current implementation.  cc @one-more-minute

**Comment by StefanKarpinski** [comment]
Feel free to implement a correct version, @ScottPJones. We should, however, not be guessing how wide people mean their tabs to be, when parsing triple-quoted strings.

**Comment by ScottPJones** [comment]
@StefanKarpinski That is why I planned on having it configurable, defaulting to the standard 8 (which is what is currently used).  That way somebody could change it, to match the setting of their editor, or the setting of the file they are currently compiling, etc.

**Comment by ScottPJones** [comment]
@hayd Yes, if it were just plain text, that's one thing, and that's the case that I wanted to fix, but when there are things like LaTeX and Markdown or HTML in the line, you really can't do anything meaningful (and the CommonMark spec doesn't really do anything very meaningful either).

**Comment by hayd** [comment]
@ScottPJones OT but my point is for docstrings, plaintext/terminal is only one of the way that they are likely to be shown, relying on whitespace to align text is not a good idea. Specifically this regards the docstring syntax above which you use in another issue (perhaps you used spaces).

**Comment by Ismael-VC** [comment]
In Python I use **[`textwrap.dedent`](https://docs.python.org/2/library/textwrap.html#textwrap.dedent)** to achive something like [this](http://ideone.com/QIsHR7). Pherhaps more utility functions for handling strings, could be useful?

**Comment by Ismael-VC** [comment]
string:

```
		"""\
		Julia is a high-level
			high-performance

			dynamic programming language
				for technical computing
		    It provides a sophisticated compiler

		distributed parallel execution
	numerical accuracy
		and an extensive mathematical function library
		"""
```

Note that Python uses `\` to suppress end of line, Julia just ignores it.

Python `print`:

```
	Julia is a high-level
		high-performance

		dynamic programming language
			for technical computing
	    It provides a sophisticated compiler

	distributed parallel execution
numerical accuracy
	and an extensive mathematical function library
```

Julia `println`:

```
Julia is a high-level
    high-performance

    dynamic programming language
        for technical computing
    It provides a sophisticated compiler

distributed parallel execution
numerical accuracy
and an extensive mathematical function library
```

**Comment by Ismael-VC** [comment]
I'm not sure how **[`Base.unindent`](https://github.com/JuliaLang/julia/blob/master/base/string.jl#L1010-1040)** works, since it's not documented. But I suspect it has nothing to do with Pythons `textwrap.dedent`.

**Comment by ScottPJones** [comment]
@Ismael-VC I'll have to look up what the behavior of `textwrap.dedent` is, and I can't speak to the intentions of whoever wrote `Base.indentation` and `Base.unindent`.   Since triple-quoted strings seem to have been lifted from Python, that very well be what they intended.   This is another place where the lack of internal documentation is a big problem...

**Comment by IainNZ** [comment]
@ScottPJones 
> This is another place where the lack of internal documentation is a big problem...

Why do you write stuff like this man? Its a thread about tabs, not about docs, its just snarky and really frustrating to read :disappointed:. Everyone knows that documentation is lacking in places, they didn't do it to spite you.

**Comment by ScottPJones** [comment]
I almost have this completely working, except for the fact that `REPL.jl` seems to be looking for `\t` characters in the ~/.julia_history file, which my fixed `unindent` code converts to spaces (based on the new global variable tab_indentation_width).
There's almost no documentation in `REPL.jl`, so unless the author can explain, I have no idea why it is looking for tab characters in the history file.  (This is a good case of where an `@author` tag in a header at the beginning of a file would be very useful!).

**Comment by pao** [comment]
`git blame REPL.jl`

Or use GitHub: https://github.com/JuliaLang/julia/blame/master/base/REPL.jl#L340

cc @StefanKarpinski

**Comment by ScottPJones** [comment]
Oh, another git command I hadn't known about!  (sounds kind of nasty though!)  Thanks!

**Comment by StefanKarpinski** [comment]
This is part of the history file format, as roughly described in #6348, except there I talked about prefixing each input line with four spaces but I ended up opting for using a single tab instead. I should probably document the history format somewhere, although it's unclear where that sort of documentation belongs.

@ScottPJones, why are you calling unindent on the history file in the first place?

**Comment by ScottPJones** [comment]
@StefanKarpinski Just to be clear, regardless of the name of the git command @pao pointed me at, I do NOT *blame* you for anything! OK?
I think your idea of a human readable format is very good... did you consider using something like JSON though to save the history?  That would be both human readable, and you have a lot more flexibility in adding metadata.
I'm not calling `unindent`, it is called in both `LineEdit.jl` and `REPL.jl` (as I mentioned in the opening message of this issue), they both use it to handle the following:
```julia
    # Bracketed Paste Mode
    "\e[200~" => (s,o...)->begin
        ps = state(s, mode(s))
        input = readuntil(ps.terminal, "\e[201~")[1:(end-6)]
        input = replace(input, '\r', '\n')
        if position(buffer(s)) == 0
            indent = Base.indentation(input)[1]
            input = Base.unindent(input[(indent+1):end], indent)
        end
```
If the check in your history code were relaxed to check for either a `\t`, or 4 or more spaces, at the beginning of the line, everything would work fine.
I think that would be useful regardless of my change, because if somebody did edit the history file, which apparently was one of the justifications for your making it readable, the editor might change tabs to spaces automatically (I set mine to do so, since the rules for Julia code in Base ask for spaces instead of tabs).
Shall I make a PR to relax that check?  Thanks!

**Comment by StefanKarpinski** [comment]
Relevant PR: https://github.com/JuliaLang/julia/pull/11718. As I noted there, the leading tab in the history file format doesn't end up in what's passed to this code, or at least it shouldn't. Leading tabs are added before writing to the history file and stripped out upon reading it.
