### ISSUE TITLE
Matrix power fails for SymTridiagonal with odd exponents

### ISSUE THREAD

**Issue by leethargo** [JuliaLang/julia#12068]
I'm using Julia Version 0.3.10 interactively:

    julia> SymTridiagonal([1, 2], [0])^1
    2x2 SymTridiagonal{Int64}:
     1  0
     0  2
    
    julia> SymTridiagonal([1, 2], [0])^2
    2x2 Array{Int64,2}:
     1  0
     0  4
    
    julia> SymTridiagonal([1, 2], [0])^3
    ERROR: `*` has no method matching *(::SymTridiagonal{Int64}, ::Array{Int64,2})
     in power_by_squaring at intfuncs.jl:74
     in ^ at intfuncs.jl:86
    
    julia> SymTridiagonal([1, 2], [0])^4
    2x2 Array{Int64,2}:
     1   0
     0  16
    
    julia> SymTridiagonal([1, 2], [0])^5
    ERROR: `*` has no method matching *(::SymTridiagonal{Int64}, ::Array{Int64,2})
     in power_by_squaring at intfuncs.jl:74
     in ^ at intfuncs.jl:86

**Comment by tkelman** [comment]
What's your `versioninfo()` ? Seems to work on master.

**Comment by pao** [comment]
He mentioned it's 0.3.10. Possible something needs backporting?

**Comment by tkelman** [comment]
Yeah I'm blind sorry, too much rapid-fire triage.

Really hard to tell with this kind of thing what change is responsible, without doing a reverse bisect - passing = `git bisect bad`, failing = `git bisect good`. This is a good test case though, if it isn't already covered somewhere under `test/linalg*`

**Comment by leethargo** [comment]
Probably no longer relevant, but it says:

    julia> versioninfo()
    Julia Version 0.3.10
    Commit c8ceeef (2015-06-24 13:54 UTC)
    Platform Info:
      System: Linux (x86_64-unknown-linux-gnu)
      CPU: Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
      WORD_SIZE: 64
      BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)
      LAPACK: libopenblas
      LIBM: libm
      LLVM: libLLVM-3.3

**Comment by andreasnoack** [comment]
Fixed by 0c8aeedea65c01ad4c3dff7119e3f41edc897ef7

**Comment by tkelman** [comment]
Well, test added to 0.4. Bug's still present on 0.3, but at this point people need to identify what fixed the issue if we're going to consider backporting anything else to 0.3.

**Comment by andreasnoack** [comment]
I know, but since we are so close to 0.4 I think the time is better spent on other issues than tracking this one down on 0.3.
