### ISSUE TITLE
gmp, mpfr, virtualenv build broken in windows (msys2)

### ISSUE THREAD

**Issue by twadleigh** [JuliaLang/julia#13206]
A few days ago, in order to rebase a couple of my branches on an up-to-date master, I made a pull that forced me to rebuild my `deps` (maybe due to #12463?).

Since then, though, I have not been able to rebuild gmp. It fails during config with text like this near the end:
```
checking size of mp_limb_t... 0
configure: error: Oops, mp_limb_t doesn't seem to work
Makefile:1803: recipe for target 'build/gmp-6.0.0/config.status' failed
```
I also get this error on a fresh clone.

~~Some googling suggests something about having absolute paths in the configure line breaks things.~~ If I go into the source directory and do a bare `./configure`, it succeeds (and gives a size of `mp_limb_t` of 8).

Has anyone else seen this? I've looked a bit into how we might tweak the invocation of `configure` but the logic in `deps/Makefile` looks, um, complicated.

**Comment by twadleigh** [comment]
It looks like an out-of-tree build for gmp just won't work for windows/msys2 (at least without some sort of patch for gmp). The configure command that `deps/Makefile` wants to execute on my machine is:
```
/c/tw/julia2/deps/srccache/gmp-6.0.0/configure --prefix=/c/tw/julia2/usr --build=x86_64-w64-mingw32 --libdir=/c/tw/julia2/usr/lib  LDFLAGS=" -Wl,--stack,8388608" F77="gfortran -m64" CC="gcc -m64 " CXX="g++ -m64 " F77= --enable-shared --disable-static
```
Executing this in the `deps/build/gmp-X.X.X` directory, it fails. However, if I execute the same in the gmp source tree, it succeeds. A bare `/c/tw/julia2/deps/srccache/gmp-6.0.0/configure` also fails when run from `deps/build/gmp-X.X.X`, while it succeeds in the tree.

**Comment by twadleigh** [comment]
My current workaround is this:
 1. after I hit the failure, I copy the gmp source tree into `deps/build/gmp-X.X.X`;
 2. rerun the `configure` command within this directory, but referring to the local configure script.

**Comment by machakann** [comment]
Hi, I also tried to build both 32 and 64 bit julia on Windows 7 (64bit), but both trial has finished to fail with the same reason. I also be able to  build only `gmp-6.0.0` independently.

**Comment by twadleigh** [comment]
Now it also looks like `virtualenv` is broken, too. :unamused:

**Comment by twadleigh** [comment]
Finally got it to build all the way through `make binary-dist`. To fix the `virtualenv` thing, I:

1. copied the contents of `deps\srccache\virtualenv-XXX` to `deps\build\julia-env`;
2. `touch`ed `deps/build/julia-env/bin/activate` into existence.

Afther that, resuming with `make binary-dist` completed.

**Comment by ihnorton** [comment]
for gmp, the following patch works for me:
```
diff --git a/deps/Makefile b/deps/Makefile
index a7a6643..c92d998 100644
--- a/deps/Makefile
+++ b/deps/Makefile
@@ -1802,7 +1802,7 @@ $(SRCDIR)/srccache/gmp-$(GMP_VER)/patched: $(SRCDIR)/srccache/gmp-$(GMP_VER)/con
 $(BUILDDIR)/gmp-$(GMP_VER)/config.status: $(SRCDIR)/srccache/gmp-$(GMP_VER)/configure $(SRCDIR)/srccache/gmp-$(GMP_VER)/patched
        mkdir -p $(dir $@)
        cd $(dir $@) && \
-       $< $(CONFIGURE_COMMON) F77= --enable-shared --disable-static $(GMP_CONFIGURE_OPTS)
+       `realpath --relative-to=./ $<` $(CONFIGURE_COMMON) F77= --enable-shared --disable-static $(GMP_CONFIGURE_OPTS)
        touch -c $@
 $(GMP_SRC_TARGET): $(BUILDDIR)/gmp-$(GMP_VER)/config.status
        $(MAKE) -C $(dir $<) $(LIBTOOL_CCLD)
```

There is no difference in the generated `Makefile`s, so the fact that this works is mystifying.

I'll make a PR, unless someone wants to dig further and figure out [what is wrong with the GMP m4 macros](https://www.mail-archive.com/mingw-w64-public@lists.sourceforge.net/msg02019.html). However, I'm not sure if `realpath` is supported on all of our target platforms (@tkelman?), and there may be some better way to accomplish the goal of calling configure as a relative path.

**Comment by tkelman** [comment]
We have a relative_path.sh script in contrib. I think this was working in cygwin-cross last time I tried (I'll test again), so it might be an MSYS2-specific problem. Virtualenv is picky which python you're using, be sure you aren't using MSYS2's python there.

**Comment by twadleigh** [comment]
@tkelman:
```
$ which python
/c/tw/Anaconda/python
```

**Comment by tkelman** [comment]
This is definitely specific to msys2 which is why I didn't notice in testing.

**Comment by twadleigh** [comment]
And I was really enjoying using the Git for Windows SDK as my 1-click solution for all things POSIX. :cry:

**Comment by tkelman** [comment]
Should be fixable, just needs a few build patches probably. What was the virtualenv error, exactly?

**Comment by twadleigh** [comment]
Here is the error I get:
```
"/c/tw/Anaconda/python" /c/tw/julia/deps/srccache/virtualenv-1.11.6/virtualenv.py build/julia-env
New python executable in build/julia-env\Scripts\python.exe
Installing setuptools, pip...done.
[ -e build/julia-env/Scripts ] && ! [ -e build/julia-env/bin ] && cmd //C mklink //J build/julia-env\\bin build/julia-env\\Scripts
Parameter format not correct - "julia-env\bin".
Makefile:1995: recipe for target 'build/julia-env' failed
make[3]: [build/julia-env] Error 1 (ignored)
touch -c build/julia-env
make[3]: Leaving directory '/c/tw/julia/deps'
touch -c ../deps/build/julia-env/bin/activate
. ./../deps/build/julia-env/bin/activate && pip install sphinx==1.3.1 \
              && pip install -r /c/tw/julia/doc/requirements.txt
/bin/sh: ./../deps/build/julia-env/bin/activate: No such file or directory
Makefile:33: recipe for target '../deps/build/julia-env/bin/sphinx-build' failed
make[2]: *** [../deps/build/julia-env/bin/sphinx-build] Error 1
make[2]: Leaving directory '/c/tw/julia/doc'
/c/tw/julia/Makefile:56: recipe for target '/c/tw/julia/doc/_build/html' failed
make[1]: *** [/c/tw/julia/doc/_build/html] Error 2
make[1]: Leaving directory '/c/tw/julia'
Makefile:438: recipe for target 'binary-dist' failed
make: *** [binary-dist] Error 2
```

**Comment by tkelman** [comment]
Ahk we need to use backslashes for `mklink` there. This is msys2 so `cygpath_w` is a no-op iirc

**Comment by twadleigh** [comment]
@tkelman, apparently so:
```
ifeq ($(BUILD_OS), WINNT) # MSYS
spawn = $(1)
cygpath_w = $(1)
else ifneq (,$(findstring CYGWIN,$(BUILD_OS))) # Cygwin
spawn = $(1)
cygpath_w = `cygpath -w $(1)`
else
ifeq ($(OS), WINNT) # unix-to-Windows cross-compile
spawn = wine $(1)
cygpath_w = `winepath -w $(1)`
else # not Windows
spawn = $(1)
cygpath_w = $(1)
endif
endif
```
My msys2 (git sdk) has a working cygpath, though:
```
$ cygpath -w `pwd`
C:\tw\julia
```

**Comment by tkelman** [comment]
Right, but MSYS1 doesn't, and we're still using MSYS1 on appveyor. We aren't building gmp or mpfr from source on appveyor, but changing `cygpath_w` there would probably break other things. Apparently MSYS2 should now be available on the appveyor VM's https://github.com/appveyor/ci/issues/352 but I haven't tried refactoring to use that.

**Comment by tkelman** [comment]
did gmp 6.1.0 change anything here?

**Comment by joa-quim** [comment]
Unfortunately not (MSYS2).

```
checking size of mp_limb_t... 0
configure: error: Oops, mp_limb_t doesn't seem to work
Makefile:1795: recipe for target 'build/gmp-6.1.0/config.status' failed
```

**Comment by tkelman** [comment]
Ah, thanks for testing. Still needs a PR to fix it then. Using `relative_path.sh` to call gmp's configure might be good enough here.

**Comment by tkelman** [comment]
Can anyone test #14164 and confirm there whether that change fixes matters?

**Comment by joa-quim** [comment]
Sorry, not yet. Made a ``make cleanall`` but still errors 

```
checking size of mp_limb_t... 0
configure: error: Oops, mp_limb_t doesn't seem to work
Makefile:1797: recipe for target 'build/gmp-6.1.0/config.status' failed
make[1]: *** [build/gmp-6.1.0/config.status] Error 1
Makefile:78: recipe for target 'julia-deps' failed
```

**Comment by Keno** [comment]
Can you confirm you applied the patch and post the output of `make VERBOSE=1`?

**Comment by tkelman** [comment]
You may also need to do `make -C deps distclean-gmp`

**Comment by joa-quim** [comment]
Sorry, I had not notice that this is still a PR. Applied the patch and it's  building fine now (though not finished yet)

**Comment by tkelman** [comment]
should be fixed, leave a comment and we'll reopen if not

**Comment by waTeim** [comment]
well make works, but make install still fails as above

    $ make install
    make[1]: Entering directory '/home/jeffw/src/julia/doc'
    make -C ./../deps install-virtualenv
    make[2]: Entering directory '/home/jeffw/src/julia/deps'
    "/c/Python27/python" /home/jeffw/src/julia/deps/srccache/virtualenv-1.11.6/virtualenv.py build/julia-env
    New python executable in build/julia-env\Scripts\python.exe
    Installing setuptools, pip...done.
    [ -e build/julia-env/Scripts ] && ! [ -e build/julia-env/bin ] && cmd //C mklink //J build/julia-env\\bin build/julia-env\\Scripts
    Parameter format not correct - "julia-env\bin".
    Makefile:1996: recipe for target 'build/julia-env' failed
    make[2]: [build/julia-env] Error 1 (ignored)
    touch -c build/julia-env
    make[2]: Leaving directory '/home/jeffw/src/julia/deps'
    touch -c ../deps/build/julia-env/bin/activate
    . ./../deps/build/julia-env/bin/activate && pip install sphinx==1.3.1 \
              && pip install -r /home/jeffw/src/julia/doc/requirements.txt
    /bin/sh: ./../deps/build/julia-env/bin/activate: No such file or directory
    Makefile:33: recipe for target '../deps/build/julia-env/bin/sphinx-build' failed
    make[1]: *** [../deps/build/julia-env/bin/sphinx-build] Error 1
    make[1]: Leaving directory '/home/jeffw/src/julia/doc'
    Makefile:56: recipe for target '/home/jeffw/src/julia/doc/_build/html' failed
    make: *** [/home/jeffw/src/julia/doc/_build/html] Error 2

**Comment by tkelman** [comment]
Agh, `/Scripts` needless platform differences strike again. The arguments to `mklink` need to use backslashes rather than forward slashes.

**Comment by waTeim** [comment]
It might be beneficial to just use python since you're assuming it anyway.  Pass parameters canonically -- using / -- and then let python figure out if you really meant \ or / since that's built in.

**Comment by tkelman** [comment]
Considering how long this code is to create an NTFS junction in Python: http://stackoverflow.com/questions/1143260/create-ntfs-junction-point-in-python
I think it would be easier to use the just-built Julia and call the `symlink` function. Unfortunately I don't think we can rely on having a working Julia executable yet at this stage of the build.

**Comment by waTeim** [comment]
naw, it's just a regex, I think.  Is the assumption cygwin or msys?  This doesn't actually build from a windows command prompt right?

**Comment by tkelman** [comment]
MSYS. This line https://github.com/JuliaLang/julia/blob/32bd104ce00149c3ace1145a53c0e5ce30691d48/deps/Makefile#L1998
is only necessary in MSYS since MSYS2's Python doesn't work with virtualenv (they may have fixed this, dunno?). Cygwin's Python works fine with virtualenv and puts things under `/bin` where sphinx can find them. We still use MSYS1 on AppVeyor so we can't assume the existence of `cygpath -w` when `BUILD_OS == WINNT`, but maybe just a sed call to turn forward slashes into double-backslashes would do the trick here.

**Comment by waTeim** [comment]
Like this (for context)


    $(VIRTUALENV_TARGET): $(VIRTUALENV_SOURCE)
        "$(shell $(SRCDIR)/find_python2)" $< $@
    ifeq ($(BUILD_OS), WINNT)
        -[ -e $@/Scripts ] && ! [ -e $@/bin ] && cmd //C mklink //J `echo $@/bin $@/Scripts | sed -e s/\\\\//\\\\\\\\/g`
    endif
            touch -c $@

**Comment by tkelman** [comment]
I would use a non-slash character as the sed fence, maybe `|`, and if you put single quotes around the expression can you get away with one fewer level of escaping? But yeah, I'd merge a PR that did something like that.

**Comment by waTeim** [comment]
Hmm one set of escaping I think is because of executing in a shell (backtick execution), and the other set is because it's also the escape character for Makefiles -- and of course it's escape for sed.  Maybe something other than |, it will confuse bash make it think it's another pipe symbol maybe.  

the above does in fact work as is at least in MSYS2.

**Comment by tkelman** [comment]
It won't confuse bash if it's inside a single quote - `sed -e 's|\\\\/|\\\\\\\\|g'`

**Comment by waTeim** [comment]
vertical bar though.. how about another meta character.  -- maybe `#`?  

    sed -e 's#\\\\/#\\\\\\\\#g'

**Comment by twadleigh** [comment]
I just tried to build again for the first time in a while. I'm currently getting a build failure due to two test failures in mpfr. I recently did an msys2 update. My best guess is it's a gcc regression.

**Comment by tkelman** [comment]
Interesting. Is msys2 using gcc 5.2 or 5.3? Cygwin cross is still on 4.9. Maybe check if opensuse cross is applying some patch for this?

**Comment by twadleigh** [comment]
msys2 is currently on gcc 5.2.

**Comment by waTeim** [comment]
But I thought the problem using packaged gcc on MSYS2 is it assumes the wrong threading model (POSIX not WinThreads) thus you must avoid using it and rather obtain the toolchain as a separate download.

**Comment by tkelman** [comment]
If you want the source build to be compatible with packages from WinRPM, then using the opensuse toolchain is recommended, yes. I think the msys2 toolchain might still work at least for a basic build of Julia without considering package compatibility, though maybe more likely to work correctly on 64 bit than 32 bit where the exception handling model is also incompatible. The opensuse toolchain is on gcc 5.3 as of a couple weeks ago.

**Comment by twadleigh** [comment]
Hmmm. WinRPM compatibility is pretty important to me. I guess I should reconsider my toolchain.

**Comment by tkelman** [comment]
The msys2 toolchain is not frequently tested, at least not by me. If you can test and verify otherwise I'm certainly willing to reconsider my recommendations.

**Comment by twadleigh** [comment]
I just updated to the toolchain available from the `get_toolchain.sh` script and attempted a clean rebuild. I'm still getting those two mpfr test failures.

**Comment by ElectricRCAircraftGuy** [comment]
I'm building [something else](https://github.com/ElectricRCAircraftGuy/Microchip_XC32_Compiler), but getting the same GMP configure error of:

```
checking whether vsnprintf works... probably
configure: WARNING: cannot check for properly working vsnprintf when cross compiling, will assume it's ok
checking whether sscanf needs writable input... no
checking for struct pst_processor.psp_iticksperclktick... no
checking size of void *... 8
checking size of unsigned short... 2
checking size of unsigned... 4
checking size of unsigned long... 4
checking size of mp_limb_t... 0                           <===== SIZE SHOULD BE 8
configure: error: Oops, mp_limb_t doesn't seem to work    <===== ERROR
make: *** [Makefile:4701: configure-gmp] Error 1
```

I think it's a Windows symlink problem, since Windows doesn't support symlinks very well. I opened the GMP config log in `C:\Users\gabriel\GS\dev\Microchip_XC32_Compiler\xc32-v4.35-src\pic32m-build\gcc\gmp\config.log`, and it shows:

```
configure:27426: checking size of mp_limb_t
configure:27431: gcc -c -g -O2 -D__USE_MINGW_ACCESS -DNO_ASM -I/c/Users/gabriel/GS/dev/Microchip_XC32_Compiler/xc32-v4.35-src/pic32m-build/opt/include -imacros host-defs.h conftest.c >&5
conftest.c:80:10: fatal error: /c/Users/gabriel/GS/dev/Microchip_XC32_Compiler/xc32-v4.35-src/pic32m-source/gcc/gmp/gmp-h.in: No such file or directory
   80 | #include "/c/Users/gabriel/GS/dev/Microchip_XC32_Compiler/xc32-v4.35-src/pic32m-source/gcc/gmp/gmp-h.in"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Notice this!:
```
fatal error: /c/Users/gabriel/GS/dev/Microchip_XC32_Compiler/xc32-v4.35-src/pic32m-source/gcc/gmp/gmp-h.in: No such file or directory
```

It says "No such file or directory". That's interesting, because in my project, the `gcc/gmp` dir is a symlink which points up to `../gmp-6.1.0`. So, I suspect that symlink is simply _not working in Windows._ I may need to manually copy the contents there, or use the Windows `mklink` command to recreate the symlinks as an admin in the Command Prompt.

**Comment by ElectricRCAircraftGuy** [comment]
No, I'm still stuck. I added a question here: https://stackoverflow.com/q/77414776/4561887

**Comment by ElectricRCAircraftGuy** [comment]
I came up with an answer. Here it is: [The fix: when compiling in an MSYS2 terminal in Windows, _absolute `#include` paths are not allowed in C and C++!_](https://stackoverflow.com/a/77435216/4561887). In short: call the gcc `configure` script with a relative path, _not_ an absolute path, when building with MSYS2 UCRT64 gcc, or else GMP fails to configure. 

I have an open discussion ongoing about this with the GMP community via their mailing list (see: https://gmplib.org/manual/Reporting-Bugs: gmp-bugs@gmplib.org), too.
