### ISSUE TITLE
Many automated builds/tests are broken with a libgit2 ECERTIFICATE error

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#13399]
The errors are along the lines of:

```
ERROR: LoadError: GitError(Code:ECERTIFICATE, Class:SSL, The SSL certificate is invalid)
 [inlined code] from libgit2/error.jl:96
 in clone at libgit2/repository.jl:95
 in clone at libgit2.jl:303
 in anonymous at /home/ubuntu/buildbot/slave/coverage_ubuntu14_04-x64/build/julia-1ed51ea4cd/share/julia/test/libgit2.jl:72
 in temp_dir at /home/ubuntu/buildbot/slave/coverage_ubuntu14_04-x64/build/julia-1ed51ea4cd/share/julia/test/libgit2.jl:62
 in temp_dir at /home/ubuntu/buildbot/slave/coverage_ubuntu14_04-x64/build/julia-1ed51ea4cd/share/julia/test/libgit2.jl:5
```

@staticfloat first pointed this out on a [buildbot](http://buildbot.e.ip.saba.us:8010/builders/coverage_ubuntu14.04-x64/builds/1119/steps/Run%20non-inlined%20tests/logs/stdio), but it's also happening on Travis:
https://travis-ci.org/JuliaStats/NullableArrays.jl/jobs/83049793
https://travis-ci.org/JuliaLang/JLD.jl/jobs/83031348
https://travis-ci.org/JuliaStats/PDMats.jl/jobs/83032826

**Comment by wildart** [comment]
We could disable certificate check, at least for METADATA packages. For `clone`, let's prompt user with warning and allow to cancel a started operation.

**Comment by tkelman** [comment]
Wouldn't that largely defeat the purpose of using https in the first place? It looks like we need to configure libgit2 and openssl in the nightly binaries to bundle its own working certs.

**Comment by staticfloat** [comment]
If we bundle ca certs somewhere does that fix the problem?

**Comment by tkelman** [comment]
I would hope so, but not sure the best way to test that. It looks like we don't run the tests on the centos 5 binary builders right now, would first want to check if they pass the libgit2 and pkg tests locally. Then figure out how to make them self contained and work when moved to different clean machines.

**Comment by vks** [comment]
I also get this error when trying to install packages with nightly.

```julia
julia> Pkg.add("Gadfly")
INFO: Initializing package repository ~/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
ERROR: GitError(Code:ECERTIFICATE, Class:SSL, The SSL certificate is invalid)
 [inlined code] from libgit2/error.jl:96
 in clone at libgit2/repository.jl:95
 in clone at libgit2.jl:303
 in anonymous at pkg/dir.jl:57
 in cd at file.jl:22
 in init at pkg/dir.jl:55
 in cd at pkg/dir.jl:28
 in add at pkg.jl:27
```

**Comment by wildart** [comment]
We could require along with `libssl` dependency to install `ca-certificates` from `openssl` bundle (or whatever alternative for particular platform). That should be easy to fix.

**Comment by tkelman** [comment]
@wildart this is about tarball binaries. We want to avoid requiring manual installation of any packages for those. We should try including the certificates in the binary, if that can be made to work. @staticfloat little help finding out if the centos5 builders are passing the https tests locally?

**Comment by staticfloat** [comment]
Looks like they pass;

```
$ ./julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+564 (2015-10-01 19:15 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 966850c (0 days old master)
|__/                   |  x86_64-unknown-linux-gnu

julia> Base.runtests("libgit2")
     * libgit2               in   7.75 seconds
    SUCCESS
```

**Comment by tkelman** [comment]
Great, thanks. Now where do the certs live and how do we make the tarball build see them? (Also what is the license on them?)

**Comment by wildart** [comment]
MPL 2.0 from [Mozilla](https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/), however they need to be [converted to proper format](https://github.com/bagder/curl/blob/master/lib/mk-ca-bundle.pl).

**Comment by staticfloat** [comment]
I don't think the answer here is to bundle our own `cert.pem` bundle; that way lies madness, incompatibility and security holes.  The proper way to do this is to point our `libssl.so` to the system-provided certificates.

On Centos5, the SSL master ca bundle is stored in `/etc/pki/tls`, and you can see via `strace` that Julia is trying to access that when you run the `libgit2` tests:

```
open("/etc/pki/tls/cert.pem", O_RDONLY) = -1 ENOENT (No such file or directory)
```

On Ubuntu, on the other hand, the directory holding this kind of stuff is `/usr/lib/ssl`; you can get these things via `openssl version -d`, I'm currently looking into how we can override this search path at runtime.

**Comment by tkelman** [comment]
Is this baked into openssl, or could a build flag on libgit2 make it search more places?

Do arch and opensuse and whatever other distros all use different paths for this? Is it lib64 in some cases?

**Comment by staticfloat** [comment]
It's a little bit of a mess: http://gagravarr.org/writing/openssl-certs/others.shtml#ca-openssl

**Comment by wildart** [comment]
There is a `libgit2` flag `GIT_OPT_SET_SSL_CERT_LOCATIONS` which points to cert file location.

**Comment by staticfloat** [comment]
That looks good; if someone can give me an example of how I would set that option (like in this example) I can test it out and figure out what works on Ubuntu.  Note that we would want to set the `path` parameter of that option on Ubuntu, but the `file` parameter of that option on CentOS5.  I'm thinking we'll just build a small database of files/paths to search, and then choose the first we `isfile()` as true.

**Comment by wildart** [comment]
```julia
cert_path = "/cert/file/location/"
cert_file = "cacert.pem"
GIT_OPT_SET_SSL_CERT_LOCATIONS = 13
err = ccall((:git_libgit2_opts, :libgit2), Cint,
             (Cint, Cstring, Cstring),
              GIT_OPT_SET_SSL_CERT_LOCATIONS, cert_file, cert_path)
err == 0 && LibGit2.clone("https://github.com/JuliaLang/Example.jl.git", "/tmp/Example")
# LibGit2.Error.last_error() # check error
```

**Comment by staticfloat** [comment]
```julia
cert_path = "/usr/lib/ssl/certs"
GIT_OPT_SET_SSL_CERT_LOCATIONS = 12
err = ccall((:git_libgit2_opts, :libgit2), Cint,
                    (Cint, Ptr{Void}, Cstring),
                     GIT_OPT_SET_SSL_CERT_LOCATIONS, C_NULL, cert_path)
LibGit2.clone("https://github.com/JuliaLang/Example.jl.git", "/tmp/Example")
```
On Ubuntu, works! In short, you're a scholar and a gentleman.

**Comment by tkelman** [comment]
Great. Little convoluted to have to hard-code these and run through them at LibGit2 module init time, but sounds worth trying. We should probably spin up a set of docker containers of different distros that we know people use Julia on and check that our list covers them all.

**Comment by staticfloat** [comment]
What do you think of querying `openssl version -d` first, to see if we can shortcut the whole process?

**Comment by tkelman** [comment]
How likely are common base distros to have working certs present, but not command-line openssl? And depending how long shelling out or querying the presence of a bunch of files takes, maybe we do this on the first invocation of a Pkg command that needs it, rather than on every Julia startup?

**Comment by wildart** [comment]
I am not sure that certificates will be present, in fresh OS installation, unless you install them explicitly.

**Comment by wildart** [comment]
Why not set certificate location through ENV flag and check it on Julia start up?

**Comment by staticfloat** [comment]
> How likely are common base distros to have working certs present, but not command-line openssl?
Not very likely, I don't think.  I have yet to login to a *nix computer that doesn't have `openssl` installed, including locked-down cluster-type ones.  (EDIT:  nevermind, I found one; my openwrt router doesn't have it installed by default)

> I am not sure that certificates will be present, in fresh OS installation, unless you install them explicitly.
SSL certificate authority files are pretty fundamental to using the internet; unless you are talking about a computer that is not intended to use the internet, (in which case this issue is somewhat moot) they will have certificate files.  They may be outdated or restricted but they will have them.

**Comment by wildart** [comment]
Certificates are only required for secure connection which is optional. Browsers usually come with their own certs.

**Comment by pao** [comment]
> openwrt router doesn't have it installed by default

Anyone willing to get Julia running on MIPS is welcome to deal with that themselves.

**Comment by lkuper** [comment]
This issue is breaking the Travis build of one of our Julia packages, too (only on the Linux build job, not OS X).  Is there a workaround?

**Comment by simonster** [comment]
@tkelman and @staticfloat have already heard this, but my argument for just shipping the certs is that if you compare the number of changes since Precise's release:

http://changelogs.ubuntu.com/changelogs/pool/main/c/ca-certificates/ca-certificates_20141019ubuntu0.12.04.1/changelog
http://changelogs.ubuntu.com/changelogs/pool/main/o/openssl/openssl_1.0.1-4ubuntu5.31/changelog

2 for the CA certs vs. a lot for openssl. So if we bundle libssl we will already need to deal with security updates and the number of additional updates required for the CA certs should be pretty negligible.

Eventually when we have default packages that are shipped with Julia, we will hopefully be able to update this stuff independently from Base.

**Comment by mlubin** [comment]
Would installing the ``ca-certificates`` ubuntu package solve the immediate issue on travis?

**Comment by simonster** [comment]
I think it has it, since curl works, but the bundled libssl is looking in the wrong place.

**Comment by tkelman** [comment]
There may be an environment variable that could be set to change the cert search path for the existing builds. Otherwise we need a patch of some kind, in the build or init code. The buildbots had a failure yesterday and are not completely back up yet.

**Comment by staticfloat** [comment]
I have one approach (the nonbundling one) on [this branch](https://github.com/JuliaLang/julia/tree/sf/sslcerts), and I'm working on another approach (the bundling one) on a different branch.

**Comment by wildart** [comment]
I like the nonbundling one.

**Comment by hayd** [comment]
Perhaps (as we were discussing before) patching upstream libgit2 to optionally use mbedtls as an alternative to openssl isn't so ridiculous.

**Comment by simonster** [comment]
Even if we use mbedtls we still need to either bundle the certs or find them. There is no SSL implementation that doesn't require certs.

**Comment by tkelman** [comment]
mbedtls would fix the building as non-root case, if you happen to have gfortran and cmake and m4 etc all installed but not ssl-dev headers. Could also download and extract the deb directly and point libgit2 at that. Certs is only an issue with binaries built on one distro and used on a different one.

**Comment by staticfloat** [comment]
Could ya'll try out [this binary](https://julianightlies.s3.amazonaws.com/bin/linux/x64/0.5/julia-0.5.0-695b070642-linux64.tar.gz) on whatever linux systems you have and ensure that it works for you as well? I've been testing it just by running `Pkg.update()`.

**Comment by lkuper** [comment]
@staticfloat I've just pulled master and rebuilt, and I'm seeing the following:

```
$ ./julia 
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+640 (2015-10-06 18:24 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 128f8c6 (0 days old master)
|__/                   |  x86_64-redhat-linux

julia> Pkg.update()
INFO: Updating METADATA...
WARNING: fetch: GitError(Code:ERROR, Class:Net, SSL error: error:140E0114:SSL routines:SSL_shutdown:uninitialized)
```

Is there something I'm doing wrong -- perhaps some missing env var or dependency?

**Comment by staticfloat** [comment]
I've never seen that particular error before.  What system are you running on?
-E

**Comment by lkuper** [comment]
@staticfloat Oops, just edited my comment.  This is on both Ubuntu and CentOS.

**Comment by staticfloat** [comment]
I just tried it out on Ubuntu 14.04 and I had no problem.  Do you have `libssl-dev` installed?  (You can check with `dpkg -l | grep libssl-dev` on Ubuntu, `yum list openssl-dev` on CentOS).  After ensuring that you have the development libraries for SSL installed, can you try `make -C deps distclean-libgit2` followed by a `make` again and see if that changes things?

**Comment by wildart** [comment]
SSL_shutdown error happens when there is not connection. The message is misleading because there is a bug in handling SSL connection in libgit2. It is already fixed in upstream, [#3445](https://github.com/libgit2/libgit2/pull/3445).

**Comment by lkuper** [comment]
@staticfloat @wildart I do have the necessary libraries on both platforms.  (On CentOS the package is called `openssl-devel`.)  I tried `make -C deps distclean-libgit2 && make`, and in both cases I got the same error when I ran `Pkg.update()`.

I tried blowing away my `~/.julia/v0.5` directory and calling `Pkg.init()` again, and got a similar error:

```
julia> Pkg.init()
INFO: Initializing package repository /home/lkuper/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
ERROR: GitError(Code:ERROR, Class:Net, SSL error: error:140E0114:SSL routines:SSL_shutdown:uninitialized)
 [inlined code] from libgit2/error.jl:96
 in clone at libgit2/repository.jl:185
 in clone at libgit2.jl:303
 in anonymous at pkg/dir.jl:49
 in cd at file.jl:22
 in init at pkg/dir.jl:47
 in init at pkg.jl:23
```

I'm a bit mystified, but I'll see if `make clean` helps and I'll try to figure out if anything is wrong with my git configuration.

**Comment by lkuper** [comment]
@staticfloat Same problem persists after a `make distcleanall`.  By the way, I'm behind a firewall and I use `git config --global url."https://".insteadOf git://`.  I also have Julia 0.3.11 installed, and there, I have no problem with `Pkg.update()` or `Pkg.add()`.  So it doesn't seem like the problem is with my git configuration.  Could libgit2 be not seeing my `~/.gitconfig` for some reason?

**Comment by wildart** [comment]
@lkuper Can you try a libgit2 `master` build? This SSL_shutdown error was fixed week ago. I suspect that something happens before this error and incorrect SSL shutdown overwrites cause of your problem.

**Comment by lkuper** [comment]
@wildart Thank you for trying to help.  Yes, libgit2 builds and installs for me with no problems, following the directions at https://github.com/libgit2/libgit2#building-libgit2---using-cmake .  `julia/deps/libgit2/build$ cmake --build .` also works fine.  This doesn't solve the issue in Julia, though.  I'll file a separate bug.

**Comment by waTeim** [comment]
Whelp, I have this problem now, what do?

    julia> Pkg.init();
    INFO: Initializing package repository /home/jeffw/.julia/v0.5
    INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
    ERROR: GitError(Code:ECERTIFICATE, Class:SSL, The SSL certificate is invalid)

    julia> versioninfo()
    Julia Version 0.5.0-dev+2336
    Commit 9cda53d (2016-01-28 14:53 UTC)
    Platform Info:
      System: Linux (arm-linux-gnueabihf)     
      CPU: ARMv7 Processor rev 10 (v7l)        <----- yes, it's ARM
      WORD_SIZE: 32
      BLAS: libopenblas (NO_AFFINITY ARMV7)
      LAPACK: libopenblas
      LIBM: libm
      LLVM: libLLVM-3.7.1


### Cert location

Lots of certs in the mozilla directory.

    ls /usr/share/ca-certificates/
    ./           ../          cacert.org/  mozilla/     spi-inc.org/

**Comment by tkelman** [comment]
Source build or nightly binary?

**Comment by waTeim** [comment]
nightly binary

**Comment by tkelman** [comment]
Ok looks like the default location fix in #13429 only works when binaries are built from a centos-like system (which we do for x86 and amd64), not an ubuntu-like system (which we do for arm). I don't think we have full control over the arm buildbot, though @ViralBShah and/or @staticfloat may know more of the details. As a workaround you may be able to try setting `LibGit2.set_ssl_cert_locations` to the locations that are right for your system?

**Comment by waTeim** [comment]
Sure I can try that

    julia> methods(LibGit2.set_ssl_cert_locations)
    # 1 method for generic function "set_ssl_cert_locations":
    set_ssl_cert_locations(cert_file) at libgit2.jl:502

Does this need to be called once per cert or something?

**Comment by waTeim** [comment]
I tried both that function and the above for including an [entire directory](https://gist.github.com/waTeim/36db753aeccd509157c6).  Still no luck

    function set_git_path(cert_path)
       GIT_OPT_SET_SSL_CERT_LOCATIONS = 12
       err = ccall((:git_libgit2_opts,:libgit2),Cint,(Cint,Ptr{Void},Cstring),GIT_OPT_SET_SSL_CERT_LOCATIONS,C_NULL,cert_path)
    end

Followed by:

    julia> include("julia-git.jl")
    set_git_path (generic function with 1 method)

    julia> set_git_path("/etc/ssl/certs")
    0

    julia> Pkg.init()
    INFO: Initializing package repository /home/jeffw/.julia/v0.5
    INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
    ERROR: GitError(Code:ECERTIFICATE, Class:SSL, The SSL certificate is invalid)


Maybe they're actually invalid?  This linux distro is older (2013) but maybe they have updated their certs? Is there a way to tell?

**Comment by tkelman** [comment]
Which distro? Some have separate ca-certificates vs ca-certificates-mozilla packages but I'm not sure how they differ. Might be worth a new issue, closed issues aren't the best place for active debugging.

**Comment by waTeim** [comment]
That's true, but I wasn't sure this was worth a new issue or if this had not already been dealt with or just "closed for now."  or what.

This distro is [Yocto Linux, poky release](https://www.yoctoproject.org/tools-resources/projects/poky).  

This did work:  (I guess you just have to arbitrarily know which is the right file):

    julia> LibGit2.set_ssl_cert_locations("/etc/ssl/certs/ca-certificates.crt")
    0

    julia> Pkg.init()
    INFO: Initializing package repository /home/jeffw/.julia/v0.5
    INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl

   **success**


    julia> Pkg.add("StateSpace")
    ERROR: Base.Pkg.PkgError("unknown package StateSpace")

    julia> Pkg.clone("git://github.com/ElOceanografo/StateSpace.jl.git");
    INFO: Cloning StateSpace from git://github.com/ElOceanografo/StateSpace.jl.git
    INFO: Computing changes...
    INFO: Cloning cache of ArrayViews from https://github.com/JuliaLang/ArrayViews.jl.git
    INFO: Cloning cache of Calculus from https://github.com/johnmyleswhite/Calculus.jl.git
    INFO: Cloning cache of Compat from https://github.com/JuliaLang/Compat.jl.git
    INFO: Cloning cache of Distributions from https://github.com/JuliaStats/Distributions.jl.git
    INFO: Cloning cache of ForwardDiff from https://github.com/JuliaDiff/ForwardDiff.jl.git
    INFO: Cloning cache of NaNMath from https://github.com/mlubin/NaNMath.jl.git
    INFO: Cloning cache of PDMats from https://github.com/JuliaStats/PDMats.jl.git
    INFO: Cloning cache of StatsBase from https://github.com/JuliaStats/StatsBase.jl.git
    INFO: Cloning cache of StatsFuns from https://github.com/JuliaStats/StatsFuns.jl.git
    INFO: Installing ArrayViews v0.6.4
    INFO: Installing Calculus v0.1.14
    INFO: Installing Compat v0.7.9
    INFO: Installing Distributions v0.8.9
    INFO: Installing ForwardDiff v0.1.5
    INFO: Installing NaNMath v0.2.0
    INFO: Installing PDMats v0.3.6
    INFO: Installing StatsBase v0.7.4
    INFO: Installing StatsFuns v0.2.0

**Comment by pclausen** [comment]
On Windows this https://stackoverflow.com/questions/48950748/julia-git-error helped me on Windows 7. 

Summary:
- Close Julia window
- Go to https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in 
- Use the "Easy Fix"
- Download and run
- Now re-run Julia --> Pkg.update() works!

**Comment by Ashwin-Shenoy-NITK** [comment]
I have run the easy fix but the same error keeps coming back even if I re run julia. I am using a 64 bit machine, Windows 7 OS & running Julia 0.6.3. Julia.exe is also in the path. 
What can I do ?

**Comment by hbtmgz** [comment]
I have met the same problem and I run the easy fix , while it would not work
