### ISSUE TITLE
printf minimum width issue with %g

### ISSUE THREAD

**Issue by chriscoey** [JuliaLang/julia#16977]
Is this behavior incorrect in the second case below?

```
julia> @printf "|%8.2g|" 0.0000312
| 3.1e-05|
julia> @printf "|%8.2g|" 0.00003
| 3e-05|
```

In the second case, only 6 characters are printed between the bars, yet I specified with %8 that a minimum of 8 chars should be printed. 

One option is to pad the extra spaces before 3. Otherwise, print a decimal and zero after 3, which is the same (correct) behavior as:

```
julia> @printf "|%#8.2g|" 0.00003
| 3.0e-05|
```

Bumping #10610, Julia might benefit from rethinking print formatting.

**Comment by quinnj** [comment]
Yes, this is fixed in #32859

**Comment by TXKurt** [comment]
Hello,

I found this thread because I was having a similar problem and it isn't fixed.
The length of the string below should be 14:

julia> import Printf; length(Printf.@sprintf("%14g",-9.4369e-16))
13

It's missing a leading space with all the releases I have: 0.7, 1.0.5, 1.5.1 (Windows).

**Comment by quinnj** [comment]
@TXKurt , to get the fix, you need to checkout the branch of code in #32859, like `git checkout origin jq/printf`, then run `make`, then your julia will have the code that contains the fix for this. For example, I just ran your code on that branch and see:
```julia
julia> import Printf; length(Printf.@sprintf("%14g",-9.4369e-16))
14

julia> Printf.@sprintf("%14g",-9.4369e-16)
"   -9.4369e-16"
```

**Comment by quinnj** [comment]
Fixed in https://github.com/JuliaLang/julia/pull/32859
