### ISSUE TITLE
Exceptions dropped in multithreaded code

### ISSUE THREAD

**Issue by samuelpowell** [JuliaLang/julia#17532]
```
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0-dev+5275 (2016-07-11 13:22 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 590b4be (9 days old master)
|__/                   |  x86_64-apple-darwin13.4.0

julia> Threads.@threads for i = 1:Threads.nthreads()
           undefined
       end

julia> 
```

Is this a consequence of #17388, or another problem?

**Comment by kpamnany** [comment]
Exceptions in threads are silently dropped right now. This is known and will be addressed, hopefully in the next major update to threading.

**Comment by samuelpowell** [comment]
Thanks @kpamnany. I could not find an associated issue so I'll leave this open, but please close if I've overlooked something.

**Comment by Keno** [comment]
Can we just put a `jl_static_show` or something in there to at least get some indication that things broke?

**Comment by Keno** [comment]
cc @JeffBezanson

**Comment by JeffBezanson** [comment]
This has been fixed.

**Comment by kschzt** [comment]
I'm afraid this isn't fixed, `Threads.@spawn begin sleep(1); throw(error("nope")) end` still swallows the error. Just wanted to note that here in case someone else stumbles on this issue and gets confused. IIUC the fix is pending https://github.com/JuliaLang/julia/issues/33248.

**Comment by kpamnany** [comment]
> I'm afraid this isn't fixed, `Threads.@spawn begin sleep(1); throw(error("nope")) end` still swallows the error. Just wanted to note that here in case someone else stumbles on this issue and gets confused. IIUC the fix is pending #33248.

??

```
julia> Threads.@spawn begin sleep(1); throw(error("nope")) end
Task (runnable) @0x00007f72b741fd00

julia> wait(ans)
ERROR: TaskFailedException:
nope
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./REPL[1]:1 [inlined]
 [3] (::var"#1#2")() at ./threadingconstructs.jl:169
Stacktrace:
 [1] wait(::Task) at ./task.jl:267
 [2] top-level scope at REPL[2]:1
```

**Comment by kschzt** [comment]
Apologies! I just realised as well that I need to wait() on the thread. Thanks :)
