### ISSUE TITLE
Matrix division fails when applied on a square matrix with duplicate rows (and columns)

### ISSUE THREAD

**Issue by rakeshvar** [JuliaLang/julia#17591]
I am trying to do least squares with a rank deficient matrix using  [the / operator](http://docs.julialang.org/en/release-0.4/stdlib/linalg/). It works in the general case, but fails when applied on a square symmetric matrix with duplicate rows (and columns).

``` julia
> n, p = 99, 8;
> y = randn(n);
> X = randn(n, p);
> X[:, 1] = 1;

# Rank deficient. X[:, 1] = X[:, 2] + X[:, 3] 
> X[:, 3] = 1 - X[:, 2];
> (X\y)'
1x8 Array{Float64,2}:
 -0.0643163  -0.123173  0.0588565  0.0812868  -0.0363878  -0.0676099  -0.0715549  0.0175931
> ((X'*X)\(X'*y))'
1x8 Array{Float64,2}:
 -0.124538  -0.0629509  0.119078  0.0812868  -0.0363878  -0.0676099  -0.0715549  0.0175931

# Duplicate column. X[:, 1] = X[:, 3] = 1
> X[:, 3] = 1;
> (X\y)'
1x8 Array{Float64,2}:
 -0.00272991  -0.182029  -0.00272991  0.0812868  -0.0363878  -0.0676099  -0.0715549  0.0175931
> (X'*X)\(X'*y)
ERROR: Base.LinAlg.SingularException(8)
 in \ at linalg/factorization.jl:25
 in \ at linalg/dense.jl:448
```

**Comment by ViralBShah** [comment]
Wouldn't the matrix be singular by construction?

**Comment by rakeshvar** [comment]
It should still work if the matrix is singular, because it will return the minimum norm solution in that case. In fact, it is singular in all four cases; and three of them work like they should. Only the last one fails.

**Comment by tkelman** [comment]
use qrfact if you want a least squares solution even in the square case. I suspect the case that succeeded wound up not exactly singular, but was probably very ill conditioned.

**Comment by andreasnoack** [comment]
We could use the pivoted Cholesky for this. It will be little more costly, though.

**Comment by andreasnoack** [comment]
So actually the documentation is wrong and I've fixed it in https://github.com/JuliaLang/julia/pull/17605. With that change, this issue is fixed short term but we could consider using QR for all floating point types. It's a little weird that we use QR for rectangular systems and LU for square. It would also be nicer to Julia's type system because then we'd choose factorization based on the element type information only instead the shape of the matrix.

**Comment by StefanKarpinski** [comment]
> The only issue is that QR is slightly more expensive than LU.

The consistent feedback I've gotten from people is that they prefer the default to be reliable and reasonably fast over maximally fast and sometimes not work. If people really need the additional performance and LU works for them, they can explicitly call `lufact`.

**Comment by tkelman** [comment]
Part of the problem is backslash has a pretty significantly different meaning for square matrices vs rectangular ones, it's really solving different problems.

**Comment by andreasnoack** [comment]
Not necessarily. We could just say that `\` always solves a least squares problem with some rule to make it unique, e.g. minimum norm if the input type is a floating point type. For a square non-singular problem that happens to be the unique solution to the system.

**Comment by StefanKarpinski** [comment]
Why does minimum norm only apply to floating point types? Doesn't minimum norm make sense any time least squares makes sense?

**Comment by andreasnoack** [comment]
No, we could decide to use the minimum norm solution more generally, e.g. for rational elements but I'm not sure it worth it. The alternative is to give a solution that imposes the necessary number of zeros. That is actually what Matlab does generally for underdetermined system. The argument is mainly computational. As discussed in https://groups.google.com/forum/#!msg/julia-users/OzLIPsjWzck/U0LuXFgjBQAJ we should use the LU to solve underdetermined systems with rational coefficients but the minimum norm solution is a little messy and expensive. The minimum norm solution we are using [here](https://github.com/JuliaLang/julia/blob/c6fab9ddbc70a5550ad727bdbccbc663ffb32c99/base/linalg/qr.jl#L575-L593) uses reflectors which makes the problem simpler but that is only possible for floating points. We could also decide to use the cheaper zero imposing solution in all cases such that
```jl
[1 1 1; 1 2 3]\[1;1]
```
would be `[1.0,0.0,0.0]` instead of `[0.833333,  0.333333, -0.166667]`.

**Comment by stevengj** [comment]
`qrfact(A)` is more than 2x slower than `lufact(a)` on my machine.  Can't `\` just switch to QR only if `lufact` throws a `SingularException`?

**Comment by andreasnoack** [comment]
I just did some benchmarking and the difference seems even larger. I didn't expect it to be that much. To do what I suggested, we'd have to estimate the rank and therefore we'd need column pivoting in the QR. The upper graph shows relative (median) timings between QR with column pivoting against LU (with row pivoting). The x-axis is matrix size measured in powers of two. Just for completeness, the lower graph is similar measurements for QR without pivoting.

Unfortunately, I don't think that using QR when LU fails will be a good solution. Numerical rank determination with LU doesn't really work. The singular error code is only returned when an exact zero pivot is detected, so in most cases, rounding errors will just blow up the solution. It would fix the reported issue here, but for very similar problem, e.g. permutation of the columns, the magnitude of the solution would probably just be very large.

<img width="640" alt="screen shot 2016-07-26 at 9 58 24 am" src="https://cloud.githubusercontent.com/assets/505001/17140753/99a30e4e-5317-11e6-8ee1-b66978fdc43b.png">

<img width="641" alt="screen shot 2016-07-26 at 10 00 00 am" src="https://cloud.githubusercontent.com/assets/505001/17140795/bbc3a1e6-5317-11e6-8717-e9d0ce10e276.png">

**Comment by stevengj** [comment]
What does Matlab do?

**Comment by tkelman** [comment]
see the flow chart(s) at http://www.mathworks.com/help/matlab/ref/mldivide.html#bt4jslc-6

**Comment by andreasnoack** [comment]
i.e. roughly what we do now, i.e. LU for square and QR for rectangular, expect that Matlab tries harder to find structure. Furthermore, Matlab doesn't throw on singular problems. It returns `NaN`s.

**Comment by tkelman** [comment]
And warns when something is near-singular

**Comment by Sacha0** [comment]
@andreasnoack, intriguing results! Would you post a gist containing the QRP/PLU and QR/PLU benchmarks? Thanks and best!
