### ISSUE TITLE
Avoid printing huge arrays in error message.

### ISSUE THREAD

**Issue by innerlee** [JuliaLang/julia#18781]
Julia version: 0.4.6 - 0.6.0, 
OS: Ubuntu

try run the following buggy code in repl:
```julia
a=zeros(10000000)
a[a.==1,1:2]
```
then the screen is flooded with red ``false`` for a while. Maybe it not very helpful dumping such a large array?

![julia](https://cloud.githubusercontent.com/assets/9464825/19060667/98834fec-8a1c-11e6-8036-8206c94ce4fb.png)

In addition (separate issue?), if press ``ctrl+c`` in the middle of printing, julia will crash with
```julia
SYSTEM: show(lasterr) caused an error
ERROR: InterruptException:
 in print_response(::Base.Terminals.TTYTerminal, ::Any, ::Array{Ptr{Void},1}, ::Bool, ::Bool, ::Void) at ./REPL.jl:176
 in print_response(::Base.REPL.LineEditREPL, ::Any, ::Array{Ptr{Void},1}, ::Bool, ::Bool) at ./REPL.jl:141
 in (::Base.REPL.##22#23{Bool,Base.REPL.##33#42{Base.REPL.LineEditREPL,Base.REPL.REPLHistoryProvider},Base.REPL.LineEditREPL,Base.LineEdit.Prompt})(::Base.LineEdit.MIState, ::Base.AbstractIOBuffer{Array{UInt8,1}}, ::Bool) at ./REPL.jl:654
 in run_interface(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface) at ./LineEdit.jl:1579
 in run_frontend(::Base.REPL.LineEditREPL, ::Base.REPL.REPLBackendRef) at ./REPL.jl:931
 in run_repl(::Base.REPL.LineEditREPL, ::Base.##926#927) at ./REPL.jl:190
 in _start() at ./client.jl:368
```

**Comment by KristofferC** [comment]
Fixed on 0.5 for arrays. For other types there is an issue open and a WIP PR #18726

**Comment by nalimilan** [comment]
@KristofferC That's not fixed even on 0.6 AFAICT. The *indexed* array is no longer printed, but there's still a problem when the *indexing* array is a large boolean vector. We should abbreviate the contents of the indexing array when it contains more than say 10-20 elements.

**Comment by nalimilan** [comment]
That said, it's a duplicate of https://github.com/JuliaLang/julia/issues/14734, right?

**Comment by tkelman** [comment]
closing as duplicate

**Comment by KristofferC** [comment]
@naliman ah yes. True.
