### ISSUE TITLE
Pkg version resolution issues

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/julia#20313]
**Long bug report**, mostly for my own reference.

Two related issues:
- a strange version resolution that doesn't make much sense, and
- a wrong error message (which I've seen before but now have a reproducible test case)

The following is starting from a clean empty `JULIA_PKGDIR`, and using a particular branch of my METADATA fork so the results won't change with new commits to default JuliaLang metadata-v2.
```
$ rm -rf $HOME/Julia/jlpkgtmp
$ JULIA_PKGDIR=$HOME/Julia/jlpkgtmp ~/Julia/julia-0.6/julia --depwarn=no
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0-dev.2459 (2017-01-29 03:30 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 058cc7d* (0 days old master)
|__/                   |  x86_64-linux-gnu

julia> Pkg.init("https://github.com/tkelman/METADATA.jl","tk/old-images")
INFO: Initializing package repository /home/tkelman/Julia/jlpkgtmp/v0.6
INFO: Cloning METADATA from https://github.com/tkelman/METADATA.jl

julia> Pkg.add("ImageRegistration")
INFO: Cloning cache of BinDeps from https://github.com/JuliaLang/BinDeps.jl.git
<same for Cairo, ColorTypes, Colors, Compat, Dates, FixedPointNumbers, Graphics, ImageRegistration,
ImageView, Images, IniFile, Reexport, SHA, SIUnits, TexExtensions, Tk, URIParser, Winston, Zlib>
INFO: Installing BinDeps v0.4.5
INFO: Installing Cairo v0.2.35
INFO: Installing ColorTypes v0.2.12
INFO: Installing Colors v0.6.9
INFO: Installing Compat v0.14.0
INFO: Installing Dates v0.4.4
INFO: Installing FixedPointNumbers v0.2.1
INFO: Installing Graphics v0.1.3
INFO: Installing ImageRegistration v0.0.1
INFO: Installing ImageView v0.2.0
INFO: Installing Images v0.4.44
INFO: Installing IniFile v0.2.5
INFO: Installing Reexport v0.0.3
INFO: Installing SHA v0.3.0
INFO: Installing SIUnits v0.1.0
INFO: Installing TexExtensions v0.0.3
INFO: Installing Tk v0.4.0
INFO: Installing URIParser v0.1.7
INFO: Installing Winston v0.12.1
INFO: Installing Zlib v0.1.12
INFO: Building Cairo
INFO: Building Images
====================================[ ERROR: Images ]=====================================

LoadError: UndefVarError: Uint8 not defined
while loading /home/tkelman/Julia/jlpkgtmp/v0.6/Images/deps/build.jl, in expression starting on line 92

==========================================================================================
INFO: Building Tk

=====================================[ BUILD ERRORS ]=====================================

WARNING: Images had build errors.

 - packages with build errors remain installed in /home/tkelman/Julia/jlpkgtmp/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Images")`
 - build a single package by running its `deps/build.jl` script

==========================================================================================
INFO: Package database updated

julia> Pkg.pin("Images",v"0.5.14") ### <---- why didn't Pkg pick this version in the first place????
INFO: Creating Images branch pinned.1b3536e6.tmp
INFO: Cloning cache of ColorVectorSpace from https://github.com/JuliaGraphics/ColorVectorSpace.jl.git
INFO: Cloning cache of DataStructures from https://github.com/JuliaLang/DataStructures.jl.git
INFO: Cloning cache of FileIO from https://github.com/JuliaIO/FileIO.jl.git
INFO: Cloning cache of StatsBase from https://github.com/JuliaStats/StatsBase.jl.git
INFO: Installing ColorVectorSpace v0.1.12
INFO: Installing DataStructures v0.5.2
INFO: Installing FileIO v0.2.2
INFO: Installing StatsBase v0.13.0

julia> Pkg.status()
1 required packages:
 - ImageRegistration             0.0.1
23 additional packages:
 - BinDeps                       0.4.5
 - Cairo                         0.2.35
 - ColorTypes                    0.2.12
 - ColorVectorSpace              0.1.12
 - Colors                        0.6.9
 - Compat                        0.14.0
 - DataStructures                0.5.2
 - Dates                         0.4.4
 - FileIO                        0.2.2
 - FixedPointNumbers             0.2.1
 - Graphics                      0.1.3
 - ImageView                     0.2.0
 - Images                        0.5.14             pinned.1b3536e6.tmp
 - IniFile                       0.2.5
 - Reexport                      0.0.3
 - SHA                           0.3.0
 - SIUnits                       0.1.0
 - StatsBase                     0.13.0
 - TexExtensions                 0.0.3
 - Tk                            0.4.0
 - URIParser                     0.1.7
 - Winston                       0.12.1
 - Zlib                          0.1.12

julia> Pkg.free("Images")
INFO: Freeing Images
INFO: Downgrading Images: v0.5.14 => v0.4.44
INFO: Removing ColorVectorSpace v0.1.12
INFO: Removing DataStructures v0.5.2
INFO: Removing FileIO v0.2.2
INFO: Removing StatsBase v0.13.0
INFO: Building Images
====================================[ ERROR: Images ]=====================================

LoadError: UndefVarError: Uint8 not defined
while loading /home/tkelman/Julia/jlpkgtmp/v0.6/Images/deps/build.jl, in expression starting on line 92

==========================================================================================

=====================================[ BUILD ERRORS ]=====================================

WARNING: Images had build errors.

 - packages with build errors remain installed in /home/tkelman/Julia/jlpkgtmp/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Images")`
 - build a single package by running its `deps/build.jl` script

==========================================================================================

julia> Pkg.pin("ColorTypes",v"0.3.0") ### the error message below is blaming the wrong package!!!
INFO: Creating ColorTypes branch pinned.a846a532.tmp
ERROR: unsatisfiable package requirements detected: no feasible version could be found for package: ImageRegistration
Stacktrace:
 [1] resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}) at ./pkg/resolve.jl:37
 [2] resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at ./pkg/entry.jl:500
 [3] resolve(::Dict{String,Base.Pkg.Types.VersionSet}) at ./pkg/entry.jl:480
 [4] pin(::String, ::String) at ./pkg/entry.jl:339
 [5] pin(::String, ::VersionNumber) at ./pkg/entry.jl:350
 [6] (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#pin,Tuple{String,VersionNumber}})() at ./pkg/dir.jl:31
 [7] cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#pin,Tuple{String,VersionNumber}}, ::String) at ./file.jl:69
 [8] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N} where N) at ./pkg/dir.jl:31
 [9] pin(::String, ::VersionNumber) at ./pkg/pkg.jl:201
```

If installing Images 0.5.14 works fine, why didn't Pkg choose to do that? It instead picked an old version, 0.4.44, which happens to not load on recent Julia. My current best theory is that Images 0.4.44 is the most recent version that doesn't depend on the ColorVectorSpace package. If both Images 0.4.44 and Images 0.5.14 are feasible solutions to dependency version resolution though, then I guess the version-weight objective function says the 0.4.44 solution is better somehow?

cc @carlobaldassi do you have any advice for how to poke at the resolver and figure out what it's thinking?

The second issue is the error message when you try to pin ColorTypes to 0.3.0. That isn't possible because ColorTypes 0.3.0 requires FixedPointNumbers 0.3.0 or higher, but Images 0.4.44 and 0.5.14 both have upper bounds on FixedPointNumbers of strictly less than 0.3.0. (Be aware that the test branch of metadata here is a bit behind the state of the default JuliaLang metadata-v2.) If you undo the failed pinning of ColorTypes with a `Pkg.free`, then switch to Images 0.5.14, then try `Pkg.pin("ColorTypes",v"0.3.0")` again, you get a better error message that explains the situation perfectly. The original error from when Images 0.4.44 was installed was blaming ImageRegistration, which is not the package responsible for the issue. The code that's throwing the `unsatisfiable package requirements detected` error has a bug.

```
julia> Pkg.free("ColorTypes")
INFO: Freeing ColorTypes
INFO: Downgrading ColorTypes: v0.3.0 => v0.2.12

julia> Pkg.pin("Images",v"0.5.14")
INFO: Package Images: checking out existing branch pinned.1b3536e6.tmp
INFO: Installing ColorVectorSpace v0.1.12
INFO: Installing DataStructures v0.5.2
INFO: Installing FileIO v0.2.2
INFO: Installing StatsBase v0.13.0

julia> Pkg.pin("ColorTypes",v"0.3.0")
INFO: Package ColorTypes: checking out existing branch pinned.a846a532.tmp
ERROR: fixed packages introduce conflicting requirements for FixedPointNumbers:
         ColorTypes requires versions [0.3.0,∞)
         Images requires versions [0.1.0,0.3.0)
       the requirements are unsatisfiable because their intersection is empty
Stacktrace:
 [1] check_requirements(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Base.Pkg.Types.Fixed}) at ./pkg/query.jl:205
 [2] resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}, ::Dict{String,VersionNumber}, ::Set{String}) at ./pkg/entry.jl:497
 [3] resolve(::Dict{String,Base.Pkg.Types.VersionSet}) at ./pkg/entry.jl:480
 [4] pin(::String, ::String) at ./pkg/entry.jl:339
 [5] pin(::String, ::VersionNumber) at ./pkg/entry.jl:350
 [6] (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#pin,Tuple{String,VersionNumber}})() at ./pkg/dir.jl:31
 [7] cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#pin,Tuple{String,VersionNumber}}, ::String) at ./file.jl:69
 [8] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N} where N) at ./pkg/dir.jl:31
 [9] pin(::String, ::VersionNumber) at ./pkg/pkg.jl:201
```

**Comment by carlobaldassi** [comment]
You were right about the reason for the first issue, see #20319.

About the second issue, it's not really a bug, but rather a failure of the solver to pinpoint the reason why it can't find a solution. Here is what happens: when you pin Images to v0.5.14 first, the code in `check_requirements` is able to detect the inconsistency, because FixedPointNumbers is a direct dependency of it (and of ColorTypes) and the requirements of the two pinned packages are in direct contradiction. However, when you don't pin Images, and try to add both ImageRegistration and "ColorTypes v0.3.0", the inconsistency is not immediately obvious, because it's indirect (ImageRegistration requires Images, and all versions of Images have upper bounds on FixedPointNumbers). So the solver is invoked, and of course fails. However, the solver by itself can only detect a violation of one of the hard constraints that it is given. In this case, it detects a violation of the only constraint it has, i.e. "install ImageRegistration" (it does not "see" the constraint "install ColorTypes v0.3.0" because that is implicit, the graph has already been pruned at this point). So technically, "no feasible version could be found for package: ImageRegistration" is correct; in pactice, it's not very helpful and probably in this case even confusing.

Having said that, the issue here is not so easy to address: one would need to perform some analysis for the reason of the contradiction, but in general there may not be an obvious reason at all, since the dependency graph can get arbitrarily complicated. Also note that the solver works by message passing: it's a distributed algorithm, which is why it's efficient, but it means that there is nothing like a backtrace, which makes things harder to interpret when it ends up in an inconsistent state. Plus as I said fixed packages are accounted for outside the core of the solver itself, by trimming the graph. I need to think if something meaningful can be done at all, at least for a subset of the cases, like this one.

In the meanwhile, suggestions on how to improve the wording for this type of occurrences are welcome.

**Comment by tkelman** [comment]
I've seen this error get even more wrong and blame a seemingly random package that wasn't what was asked for or the cause of the problem, or even a package that had difficult bounds to satisfy. This situation is hard to reproduce since it's often transient and state dependent.

If the resolver fails, could we re run a slower less aggressive algorithm for the purposes of getting better constraint reporting? Listing which versions of the asked-for package have upper bounded dependencies could help, as one step.

**Comment by vtjnash** [comment]
possibly related: https://github.com/JuliaLang/julia/issues/13340

**Comment by carlobaldassi** [comment]
> I've seen this error get even more wrong and blame a seemingly random package that wasn't what was asked for or the cause of the problem, or even a package that had difficult bounds to satisfy. This situation is hard to reproduce since it's often transient and state dependent.

Yes, looking at the code again, what actually happens in this case is that the solver reports the first time that some contradictory messages reach some package. This can happen anywhere in the graph, really. I think the reporting could be improved though, I'll try to come up with something in the next days.

**Comment by mkborregaard** [comment]
I don't know whether to report here or open a new issue, but I have issue 2 of the OP. Pkg operations (`add`, `rm`, `update`) fail with:
```
ERROR: unsatisfiable package requirements detected: no feasible version could be found for package: QuartzImageIO
  (you may try increasing the value of the
   JULIA_PKGRESOLVE_ACCURACY environment variable)
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:? (repeats 2 times)
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}) at ./pkg/entry.jl:476
 in edit(::Function, ::String, ::Base.Pkg.Types.VersionSet, ::Vararg{Base.Pkg.Types.VersionSet,N}) at ./pkg/entry.jl:30
 in (::Base.Pkg.Entry.##2#5{String,Base.Pkg.Types.VersionSet})() at ./task.jl:360
 in sync_end() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in macro expansion at ./task.jl:327 [inlined]
 in add(::String, ::Base.Pkg.Types.VersionSet) at ./pkg/entry.jl:51
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in add(::String) at ./pkg/pkg.jl:100
```
The only operation that gives a different error is, specifically `Pkg.rm("QuartzImageIO")` which fails with the complaint about ColorVectorSpace:
```
Pkg.rm("QuartzImageIO")
ERROR: unsatisfiable package requirements detected: no feasible version could be found for package: ColorVectorSpace
  (you may try increasing the value of the
   JULIA_PKGRESOLVE_ACCURACY environment variable)
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:? (repeats 2 times)
 in resolve(::Dict{String,Base.Pkg.Types.VersionSet}, ::Dict{String,Dict{VersionNumber,Base.Pkg.Types.Available}}, ::Dict{String,Tuple{VersionNumber,Bool}}, ::Dict{String,Base.Pkg.Types.Fixed}) at ./pkg/entry.jl:476
 in edit(::Function, ::String) at ./pkg/entry.jl:30
 in rm(::String) at ./pkg/entry.jl:81
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#rm,Tuple{String}})() at ./pkg/dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#rm,Tuple{String}}, ::String) at ./file.jl:59
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in rm(::String) at ./pkg/pkg.jl:91
```

Following, `Pkg.rm("ColorVectorSpace)` seems not to complain
```
INFO: Removing ColorVectorSpace (unregistered)
```
but it does not resolve the problem, nor does it make `Pkg.rm("QuartzImageIO")` stop complaining. It appears my Pkg is currently dead.

**Comment by kmsquire** [comment]
Hi Michael, if you haven't yet, why don't you post your problem on Discourse?  It should be resolvable.

**Comment by mkborregaard** [comment]
Will do, thanks. I was uncertain whether this was too specific and would just spam the forum.

**Comment by mkborregaard** [comment]
You're right, it's solved now :-) https://discourse.julialang.org/t/pkg-broken-no-feasible-version-error/2347

**Comment by tkelman** [comment]
I'm going to call this basically fixed by #20313 and #20480.

**Comment by tkelman** [comment]
On second thought, maybe not completely fixed - Julia 0.5.1, at METADATA commit https://github.com/JuliaLang/METADATA.jl/commit/28ca77546e9a4595cdbd051d995f98ce16ec82cf with [this REQUIRE file](https://gist.github.com/b86025d3cca35792636a2304d746edc2), gives a resolution failure unless `JULIA_PKGRESOLVE_ACCURACY` is set to at least 4.

**Comment by tkelman** [comment]
Though it's fixed on master (have to modify VERSION to lie and say it's 0.5.x to test with the same REQUIRE file, since Grid.jl is deprecated and not installable on 0.6-). Probably by #20480 which was a more complicated change and not backported yet. Maybe it (or parts of it?) should be.
