### ISSUE TITLE
misreported line number for undefined interpolated variable in docstring

### ISSUE THREAD

**Issue by tpapp** [JuliaLang/julia#21018]
MWE (call with `julia filename.jl`):
```julia
"User mistakenly leaves a `$f` unquoted in a docstring"
function foo()
end

"Various other expressions follow. Error message indicates line numbers around 500."
function bar()
end
```

Error message on `v0.5.1`:
```julia
$ julia /tmp/foo.jl 
ERROR: LoadError: UndefVarError: f not defined
 in include_from_node1(::String) at ./loading.jl:488
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
while loading /tmp/foo.jl, in expression starting on line 481
```
Error message in `v0.6.0-pre-alpha`:
```julia
tamas@tamas ~/src/julia-0.6.0-pre.alpha % bin/julia /tmp/foo.jl
ERROR: LoadError: UndefVarError: f not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:539
 [2] include(::String) at ./sysimg.jl:14
 [3] process_options(::Base.JLOptions) at ./client.jl:305
 [4] _start() at ./client.jl:371
while loading /tmp/foo.jl, in expression starting on line 511
```

Related: #8963, but until that is decided, it would be great if the line number could be reported correctly.

**Comment by daanhb** [comment]
I ran into a similar issue with a misreported line number for an `UndefVarError`, but without an interpolated variable. In fact the docstring is entirely valid. If the definition of a function has a missing type parameter (leading to the `UndefVarError`) AND if that function has a (valid) docstring, then the line number is wrongly reported. Without the docstring, the error is reported with the correct line number.

MWE, for a file with the following contents:
```
"doc string"
myfun(::Type{Val{T}}) = 20
```
The output of `julia filename.jl` is:
```
RROR: LoadError: UndefVarError: T not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] process_options(::Base.JLOptions) at ./client.jl:305
 [4] _start() at ./client.jl:371
while loading /tmp/foo.jl, in expression starting on line 521
```
This is on Julia 0.6 RC2. I've seen this one a number of times and I have very often (perhaps not always...) seen line number 521.

**Comment by mschauer** [comment]
I run into a variant (statistically your and my MWE cancel 😄 )
```
"test"
f{T}(x::T) where {T} = x
```

```
ERROR: LoadError: UndefVarError: f not defined
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:576
 [2] include(::String) at ./sysimg.jl:14
while loading test.jl, in expression starting on line 521
```

**Comment by mschauer** [comment]
@tpapp The docstring triggers wrong line reporting: `... while loading test.jl, in expression starting on line 521`, whereas the file has only two lines.

**Comment by tpapp** [comment]
@mschauer: sorry, I was testing on `master` and could not reproduce. It is indeed an issue in `v0.6.2`, but I believe that it is fixed in `master`. So is the original issue, and the one reported by @daanhb.

If you agree, then I would close the issue.

**Comment by daanhb** [comment]
I ran the two MWE's in this issue again today, the one posted by @tpapp and the other one by me. The line number is still incorrectly reported in `v0.6.3`. However, `v0.7.0-alpha.0` correctly reports the line number in both cases.

For example, the MWE with unquoted `f` on line 1 in the docstring leads to the following output:
```
ERROR: LoadError: UndefVarError: f not defined
Stacktrace:
 [1] top-level scope
 [2] include at ./boot.jl:314 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1071
 [4] include(::Module, ::String) at ./sysimg.jl:29
 [5] exec_options(::Base.JLOptions) at ./client.jl:267
 [6] _start() at ./client.jl:427
in expression starting at /tmp/test21018.jl:1
```

So it seems fixed in `0.7` and I'd be happy with having this issue closed.

**Comment by tpapp** [comment]
@daanhb: thanks for the confirmation, closing the issue.
