### ISSUE TITLE
InterruptException not enabled when running scripts

### ISSUE THREAD

**Issue by ggggggggg** [JuliaLang/julia#21287]
To reproduce

  * Create `watchfile.jl` containing `watch_file("abc")`
  * make sure file abc exists, `touch abc` from command line
  * `julia watchfile.jl`
  * press `Ctrl-C`

Output: 
```
computer:user user$ julia watchfile.jl 
^C
signal (2): Interrupt: 2
while loading /Users/user/watchfile.jl, in expression starting on line 1
kevent at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0xffffffffffffffff)
Allocations: 949593 (Pool: 948780; Big: 813); GC: 0
Segmentation fault: 11
```
I think it should throw an `InterruptException` or maybe a `UVError`.

**Comment by vtjnash** [comment]
It's not a segfault (signal (11)), it's an interrupt (signal (2)). When run at the console, Julia doesn't enable the InterruptException handler.

**Comment by Keno** [comment]
Well, it's an interrupt and then it segfaults.

**Comment by yuyichao** [comment]
What version is this?

**Comment by ggggggggg** [comment]
```
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by ggggggggg** [comment]
As @vtjnash points out this isn't special to `watch_file`, you get the same behavior with a file `test.jl` containing
```
while true
sleep(1)
end
```

I'm writing a script that is intended to run until stopped. In python I usually just catch Ctrl-c and end gracefully. I was hoping to do the same here.

**Comment by yuyichao** [comment]
The segfault should be fixed on master in cases it's theoretically possible

**Comment by ggggggggg** [comment]
In that case I'll close this and hope it's better in 0.6.

**Comment by JeffBezanson** [comment]
The segfault seems to be fixed, but we still don't throw an InterruptException.

**Comment by Keno** [comment]
I think that's actually intentional, because we wanted to guarantee that the process quits.

**Comment by yuyichao** [comment]
The current behavior is intentially although it can still segfault. The three options that should not segfault for a well written program are,

1. Throw `InterruptException` at safepoint
2. `jl_exit` at safepoint
3. `_exit` immediately. (OK, this can be `_exit` at safepoint too but there's little point doing that....)

What we have right now is option 1 in REPL and `jl_exit` immediately in script. Since `jl_exit` does cleanup and call `exit` this can still crash. If we really want to have no segfault at all, we need to pick one from 2 or 3 above. Picking 2 means `Ctrl-C` cannot be used to break out of dead loops. Picking 3 means there won't be clean up. Of course we can also go with 1. Or if we can combine 2 and 3 and do `jl_exit` at safepoint and call `_exit` after a 100ms time out.

**Comment by StefanKarpinski** [comment]
> Or if we can combine 2 and 3 and do `jl_exit` at safepoint and call `_exit` after a 100ms time out.

This seems like a pragmatic (mostly) best of both worlds solution.

**Comment by yuyichao** [comment]
It's mainly bad in the sense that we won't be able to guarantee anything (well, other than it shouldn't segfault). We may not run the finalizer and we may not exit immediately.....

**Comment by yuyichao** [comment]
If people like it, it should be pretty easy to implement. Hopefully no one cares about the guarantees (which we don't really provide now anyway.................)
