### ISSUE TITLE
repr output for arrays with where clause types does not parse

### ISSUE THREAD

**Issue by simonster** [JuliaLang/julia#23037]
e.g.:

```julia
julia> repr(Array{Int}[[1]])
"Array{Int64,N} where N[[1]]"

julia> Array{Int64,N} where N[[1]]
ERROR: syntax: invalid variable expression in "where"
```

Both people and machines might have an easier time parsing this with parens, i.e. `(Array{Int64,N} where N)[[1]]`.

**Comment by laborg** [comment]
This has been fixed in 1.7
```julia
julia> repr(Array{Int}[[1]])
"Array{Int64}[[1]]"

julia> Array{Int64}[[1]]
1-element Vector{Array{Int64}}:
 [1]
```

**Comment by vtjnash** [comment]
Not actually fixed, but we have another issue/reproducer open, so it is a duplicate
