### ISSUE TITLE
tuple concatenation in v0.7.0-dev is worse

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaLang/julia#23277]
just in case this is not present as another issue
Details are from a discourse [post](https://discourse.julialang.org/t/efficient-tuple-concatenation/5398/3)

**Comment by vtjnash** [comment]
resolved in discourse

**Comment by pablosanjose** [comment]
This is still not quite resolved, I think. If I try the proposed solution
```
@inline tuplejoin(x) = x
@inline tuplejoin(x, y) = (x..., y...)
@inline tuplejoin(x, y, z...) = (x..., tuplejoin(y, z...)...)
```
to concatenate tuples of different lengths, current master (well, 16 days old) still allocates and slows down relative to v0.6.

In v0.7
```
julia> @btime tuplejoin((1,2),(1,2,3),(1,2,4,5),(1,2),(1,2),(1,2));
  253.331 ns (1 allocation: 128 bytes)
```

While in v0.6
```
julia> @btime tuplejoin((1,2),(1,2,3),(1,2,4,5),(1,2),(1,2),(1,2));
  4.512 ns (0 allocations: 0 bytes)
```

**Comment by vtjnash** [comment]
duplicate of #22545

**Comment by truedichotomy** [comment]
Where did `tuplejoin` go in the latest version of Julia? I can't find it anywhere.

**Comment by pablosanjose** [comment]
I don't think it was ever part of Base.

**Comment by shbhuk** [comment]
Is there a simple way to do this (concatenate tuples) v1.0?
