### ISSUE TITLE
Unexpected allocations caused by unused typevars

### ISSUE THREAD

**Issue by rdeits** [JuliaLang/julia#29393]
Under some circumstances, having an unused typevar in a method definition causes the method to unexpectedly allocate and perform poorly. For example: 

```julia
julia> function foo(y::T) where {N, T}
         1.0 * y
       end
foo (generic function with 1 method)

julia> using BenchmarkTools
[ Info: Recompiling stale cache file /home/BOSDYN/rdeits/.julia/compiled/v1.0/BenchmarkTools/ZXPQo.ji for BenchmarkTools [6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf]

julia> @btime foo($(1))
  13.938 ns (1 allocation: 16 bytes)
1.0
```

where the `N` parameter is unused. Removing that parameter fixes the problem: 

```julia
julia> function foo(y::T) where {T}
         1.0 * y
       end
foo (generic function with 1 method)

julia> @btime foo($(1))
  1.239 ns (0 allocations: 0 bytes)
1.0
```

Is this and expected performance issue? I've observed it with Julia 1.0 and the latest nightly build. 

```julia
julia> versioninfo()
Julia Version 1.0.1-pre.171
Commit 398d87829d (2018-09-26 22:52 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E3-1535M v6 @ 3.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

**Comment by JeffBezanson** [comment]
Was also observed here https://github.com/JuliaLang/julia/issues/27813#issuecomment-400620048 (there's a response below that). Hasn't been a high priority but I guess we can do something about it, and/or give a warning for parameters that don't appear in the signature.

**Comment by nalimilan** [comment]
+1 for a warning.

**Comment by Keno** [comment]
Might be fixed by https://github.com/JuliaLang/julia/pull/29323?

**Comment by JeffBezanson** [comment]
No, I think it's a calling convention issue.

**Comment by vtjnash** [comment]
Fixed by https://github.com/JuliaLang/julia/commit/cfec1731d123868ca2b755f27a9e7bd3aca4060c [#46608](https://github.com/JuliaLang/julia/pull/46608)

**Comment by KristofferC** [comment]
It's funny that the commit message explicitly says that it does not fix this issue.
