### ISSUE TITLE
cat(a, b; dims=1) is slow compared with vcat(a, b)

### ISSUE THREAD

**Issue by strickek** [JuliaLang/julia#31183]
```
julia> using BenchmarkTools

julia> a = [1, 2]
2-element Array{Int64,1}:
 1
 2

julia> b = [3, 4]
2-element Array{Int64,1}:
 3
 4

julia> @btime vcat(a, b)
  180.394 ns (1 allocation: 112 bytes)
4-element Array{Int64,1}:
 1
 2
 3
 4

julia> @btime cat(a, b; dims=1)
  44.690 μs (37 allocations: 1.45 KiB)
4-element Array{Int64,1}:
 1
 2
 3
 4

```
With hcat and dims=2 it is the same story.

**Comment by daviehh** [comment]
`@code_warntype cat(a, b;dims=1)` thinks it's not type-stable; 

```
const c=[1,2]
const d=[3,4]
@btime cat(c, d; dims=1)
```

> 531.153 ns (9 allocations: 544 bytes)

bring allocations down but still higher than vcat and runs slower. Looks like here

https://github.com/JuliaLang/julia/blob/80516ca20297a67b996caa08c38786332379b6a5/base/abstractarray.jl#L1517

 that `vcat` calls `cat`, which would be quite strange for this behavior...

**Comment by strickek** [comment]
Maybe related: #30686

**Comment by strickek** [comment]
I checked this topic again with Julia v1.6.0-RC2:
Situation improved for cat() from 37 to 25 allocations.
```
julia> @btime vcat(a, b)
  50.506 ns (1 allocation: 112 bytes)
4-element Vector{Int64}:
 1
 2
 3
 4

julia> @btime cat(a, b; dims=1)
  1.630 μs (25 allocations: 704 bytes)
4-element Vector{Int64}:
 1
 2
 3
 4
```
faster is `dims=Val(1)`, see: https://discourse.julialang.org/t/very-slow-loop/53608/24
```
julia> @btime cat(a, b; dims=Val(1))
  1.290 μs (17 allocations: 528 bytes)
4-element Vector{Int64}:
 1
 2
 3
 4
```
Conclusion:  If possible, use `vcat()` or `hcat()`

**Comment by vtjnash** [comment]
At least the Array allocations are faster and smaller now, so it is somewhat 
```
julia> @btime vcat(a, b)
  41.726 ns (2 allocations: 96 bytes)
4-element Vector{Int64}:
 1
 2
 3
 4

julia> @btime cat(a, b; dims=1)
  825.628 ns (12 allocations: 304 bytes)
4-element Vector{Int64}:
 1
 2
 3
 4

julia> @btime cat(a, b; dims=Val(1))
  42.858 ns (2 allocations: 96 bytes)
4-element Vector{Int64}:
 1
 2
 3
 4
```

Profile suggests it is due to a lot of dynamic dispatch in the `dims=1` case (to compute cshp and such), which could be reduced by forcing dispatch early and converting the dims to type `Val`
```
julia> dim = 1; @btime cat(a, b; dims=Val(dim))
  120.839 ns (2 allocations: 96 bytes)
4-element Vector{Int64}:
 1
 2
 3
 4
```

**Comment by BioTurboNick** [comment]
This issue seems to have been solved since at least 1.10

<img width="335" height="446" alt="Image" src="https://github.com/user-attachments/assets/83933221-bf80-4340-919a-05c69c6c9761" />

**Comment by adienes** [comment]
perhaps it is system dependent? this still reproduces for me. in fact the `cat` call is is substantially slower on nightly than 1.10

```
julia> using BenchmarkTools

julia> a = [1, 2];

julia> b = [3, 4];

julia> @btime vcat(a, b)
  38.180 ns (2 allocations: 96 bytes)

julia> @btime cat(a, b; dims=1)
  849.206 ns (18 allocations: 464 bytes)

julia> versioninfo()
Julia Version 1.13.0-DEV.868
Commit f2a8e18a98c (2025-07-15 06:42 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 10 × Apple M1 Max
  WORD_SIZE: 64
  LLVM: libLLVM-20.1.2 (ORCJIT, apple-m1)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 8 virtual cores)
```

**Comment by BioTurboNick** [comment]
Sorry, I made them global const, as is good practice.

Is the issue about differences in cat methods, or about global variables being slower?

**Comment by adienes** [comment]
well there's a function barrier here so the global-ness I think shouldn't really matter. but you raise a good point that the benchmarking practice in the MWE is a bit misleading; the arguments should be interpolated into the function call (or put in `setup`

```
julia> using BenchmarkTools

julia> @btime vcat(a, b) setup=(a = [1,2]; b = [3,4])
  18.412 ns (2 allocations: 96 bytes)
4-element Vector{Int64}:
 1
 2
 3
 4

julia> @btime cat(a, b; dims=1) setup=(a = [1,2]; b = [3,4])
  16.826 ns (2 allocations: 96 bytes)
```

so indeed it has been fixed since 1.10. sorry for the noise
