### ISSUE TITLE
Error from Julia 1.2-rc1 with custom sysimages: undefined symbol: mbedtls_x509_crt_verify_restartable (reproducible on Travis)

### ISSUE THREAD

**Issue by tkf** [JuliaLang/julia#32220]
When running `Pkg.test` with some custom sysimages, I get the following error in Julia 1.2-rc1 but not in Julia 1.1 (but with some specific combinations of packages compiled into the system image):

> `/home/travis/julia/bin/julia: symbol lookup error: /home/travis/julia/bin/../lib/julia/libmbedtls.so.12: undefined symbol: mbedtls_x509_crt_verify_restartable`

Examples with the error:

* https://travis-ci.com/tkf/julia-sysimage-recipes/builds/113968604 (Flux etc.)
* https://travis-ci.com/tkf/julia-sysimage-recipes/builds/113967025 (VegaLite, DataFrames, etc.)

Examples without the error:

* https://travis-ci.com/tkf/julia-sysimage-recipes/builds/113968102 (Rebugger etc.)
* https://travis-ci.com/tkf/julia-sysimage-recipes/builds/113967991 (Plots etc.)
* https://travis-ci.com/tkf/julia-sysimage-recipes/builds/113967975 (PyCall etc.)
* https://travis-ci.com/tkf/julia-sysimage-recipes/builds/113967900 (Pandas etc.)

**Comment by pfitzseb** [comment]
I just got the same error locally:
```
(v1.2) pkg> test TableView
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
/home/pfitzseb/Documents/julia-1.2.0-RC/bin/julia: symbol lookup error: /home/pfitzseb/Documents/julia-1.2.0-RC/bin/../lib/julia/libmbedtls.so.12: undefined symbol: mbedtls_pk_verify_restartable
```
This seems to be related to open sockets or something like that. A fairly minimal repro is
```
julia> using Blink, WebIO

julia> w = Window()
Window(1, Electron(Process(`/home/pfitzseb/.julia/dev/Blink/deps/atom/electron /home/pfitzseb/.julia/dev/Blink/src/AtomShell/main.js port 6128`, ProcessRunning), Sockets.TCPSocket(RawFD(0x00000014) active, 0 bytes waiting), Dict{String,Any}("callback" => getfield(Blink, Symbol("##1#2"))())), Page(1, WebSocket(server, CONNECTED), Dict{String,Any}("callback" => getfield(Blink, Symbol("##1#2"))()), Distributed.Future(1, 1, 1, Some(true))))

julia> body!(w, dom"div"("hi"))
Page(1, WebSocket(server, CONNECTED), Dict{String,Any}("webio" => getfield(WebIO, Symbol("##99#100")){WebIO.BlinkConnection}(WebIO.BlinkConnection(Page(#= circular reference @-4 =#))),"callback" => getfield(Blink, Symbol("##1#2"))()), Distributed.Future(1, 1, 1, Some(true)))

(v1.2) pkg> test TableView
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
./julia: symbol lookup error: /home/pfitzseb/Documents/julia-1.2.0-RC/bin/../lib/julia/libmbedtls.so.12: undefined symbol: mbedtls_pk_verify_restartable
```

**Comment by quinnj** [comment]
I've seen these kind of issues before w/ a mismatch between the julia-shipped mbedtls libraries and the MbedTLS.jl-shipped binaries. Maybe old binaries aren't getting cleaned up? Can people who are experiencing this issue comment on their setups? Local source builds? Platform? Version of MbedTLS.jl?

**Comment by tkf** [comment]
The error in Travis is using the binary distribution.  Looking at [Manifest.toml](https://github.com/tkf/julia-sysimage-recipes/blob/46fc9ab7e3684b7d3be04ac377bef2fa4961f754/Manifest.toml) of the [failed build](https://travis-ci.com/tkf/julia-sysimage-recipes/builds/113968604), it seems MbedTLS.jl is not installed.

**Comment by pfitzseb** [comment]
I'm running into this with the Linux x64 binary distribution. MbedTLS.jl is on version 0.6.8.

**Comment by KristofferC** [comment]
https://github.com/JuliaWeb/MbedTLS.jl/issues/193

**Comment by staticfloat** [comment]
If anyone who has this problem can get a `Libdl.dllist()` _after_ hitting the error, that would be very helpful.  I am suspicious that somehow a library is getting linked in during custom sysimg build time that brings in a different version of MbedTLS.

**Comment by pfitzseb** [comment]
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.2.0-pre.0 (2019-04-11)
 _/ |\__'_|_|_|\__'_|  |  release-1.2/8a84ba5018 (fork: 1 commits, 68 days)
|__/                   |

julia> using Libdl

julia> Libdl.dllist()
29-element Array{String,1}:
 "linux-vdso.so.1"                                                                                                          
 ⋮                                                                            
 "/home/pfitzseb/Documents/Git/julia/usr/bin/../lib/libspqr.so.2"             

julia> using Blink, WebIO

julia> Libdl.dllist()
29-element Array{String,1}:
 "linux-vdso.so.1"                                                            
 "/home/pfitzseb/Documents/Git/julia/usr/bin/../lib/libjulia.so.1"                                                                
 ⋮                                                                            
 "/home/pfitzseb/Documents/Git/julia/usr/bin/../lib/libspqr.so.2"             

julia> w = Window()
Window(1, Electron(Process(`/home/pfitzseb/.julia/dev/Blink/deps/atom/electron /home/pfitzseb/.julia/dev/Blink/src/AtomShell/main.js port 3346`, ProcessRunning), Sockets.TCPSocket(RawFD(0x0000001d) active, 0 bytes waiting), Dict{String,Any}("callback" => getfield(Blink, Symbol("##1#2"))())), Page(1, WebSocket(server, CONNECTED), Dict{String,Any}("callback" => getfield(Blink, Symbol("##1#2"))()), Distributed.Future(1, 1, 1, Some(true))))

julia> Libdl.dllist()
30-element Array{String,1}:
 "linux-vdso.so.1"                                                            
 "/home/pfitzseb/Documents/Git/julia/usr/bin/../lib/libjulia.so.1"                                                              
 ⋮                                                                                    
 "/home/pfitzseb/Documents/Git/julia/usr/bin/../lib/libspqr.so.2"             
 "/home/pfitzseb/.julia/packages/MbedTLS/X4xar/deps/usr/lib/libmbedcrypto.so" 

(v1.2) pkg> test TableView
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
/usr/local/bin/julia: symbol lookup error: /home/pfitzseb/Documents/Git/julia/usr/bin/../lib/libmbedtls.so.12: undefined symbol: mbedtls_pk_verify_restartable

Julia has exited. Press Enter to start a new session.
```
I can't get you the output of `Libdl.dllist()` after hitting the error since Julia segfaults. I have the relevant print statements in my tests, but those obviously aren't getting hit (presumably because the test process fails somewhere in Pkg).

**Comment by vtjnash** [comment]
Set the environment variable `LD_BIND_NOW=1` to disable glibc from killing the process with prejudice when hitting that error.

**Comment by quinnj** [comment]
@staticfloat and I think that https://github.com/JuliaWeb/MbedTLS.jl/pull/204 should resolve this. (we really need to put MbedTLS.jl as a stdlib; these library mismatches are super annoying)

**Comment by pfitzseb** [comment]
Hm, `jq/1.2` doesn't seem to fix this for me:
```
MbedTLS on  jq/1.2 
λ git pull           
Already up to date.

MbedTLS on  jq/1.2 
λ julia -q
(v1.2) pkg> build MbedTLS
  Building MbedTLS → `~/.julia/dev/MbedTLS/deps/build.log`
 Resolving package versions...

(v1.2) pkg> 

MbedTLS on  jq/1.2 
λ julia -q
(v1.2) pkg> st MbedTLS
    Status `~/.julia/environments/v1.2/Project.toml`
  [739be429] MbedTLS v0.6.8+ [`~/.julia/dev/MbedTLS`]

julia> using Blink, WebIO
[ Info: Recompiling stale cache file /home/pfitzseb/.julia/compiled/v1.2/Blink/wSmkt.ji for Blink [ad839575-38b3-5650-b840-f874b8c74a25]

julia> w = Window();

(v1.2) pkg> test TableView
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
julia: symbol lookup error: /home/pfitzseb/Documents/Git/julia/usr/bin/../lib/libmbedtls.so.12: undefined symbol: mbedtls_pk_verify_restartable
```

I unfortunately couldn't get the output of `Libdl.dllist()` because the process spawned by `Pkg.test` dies even with `LD_BIND_NOW=1`, but I did get a bit more info (with MbedTLS.jl release, not `jq/1.2`):
```
λ LD_BIND_NOW=1 julia -q
julia> using Blink, WebIO

julia> w = Window();

(v1.2) pkg> test TableView
ERROR: error compiling do_test!: error compiling #test#62: error compiling #test#114: error compiling backwards_compatibility_for_test: error compiling #with_dependencies_loadable_at_toplevel#27: error compiling #mktempdir#15: error compiling #29: error compiling #_add_or_develop#26: error compiling #apply_versions#19: error compiling install_git: error compiling shred!: error compiling #62: error compiling #fetch#5: error compiling #fetch: error compiling #fetch#115: could not load library "libgit2"                                                               
/home/pfitzseb/Documents/Git/julia/usr/bin/../lib/libmbedx509.so.0: undefined symbol: mbedtls_asn1_write_tagged_string
```

**Comment by staticfloat** [comment]
@pfitzseb if you're on Linux, (which it looks like you are) you can use something like `strace julia -e 'commands to make julia crash' 2>&1 | grep -i mbedtls` to show which libraries are getting loaded.  That would be helpful, so as to ensure that it's not a previously-built custom sysimg that's causing the problem, or something like that.

**Comment by pfitzseb** [comment]
```
λ ./julia -v 
julia version 1.2.0-rc1

λ strace ./julia -e 'using Blink, WebIO, Pkg; w = Window(); sleep(10); Pkg.test("TableView")' 2>&1 | grep -i mbedtls
stat("/home/pfitzseb/.julia/dev/MbedTLS", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/pfitzseb/.julia/dev/MbedTLS/src/MbedTLS.jl", {st_mode=S_IFREG|0644, st_size=3564, ...}) = 0
stat("/home/pfitzseb/.julia/compiled/v1.2/MbedTLS/bf9T0.ji", {st_mode=S_IFREG|0600, st_size=332865, ...}) = 0
stat("/home/pfitzseb/Documents/julia-1.2.0-RC/local/share/julia/compiled/v1.2/MbedTLS/bf9T0.ji", 0x7fffe86d4e90) = -1 ENOENT (No such file or directory)
stat("/home/pfitzseb/Documents/julia-1.2.0-RC/share/julia/compiled/v1.2/MbedTLS/bf9T0.ji", 0x7fffe86d4e90) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/pfitzseb/.julia/compiled/v1.2/MbedTLS/bf9T0.ji", O_RDONLY|O_CLOEXEC) = 15
stat("/home/pfitzseb/.julia/dev/MbedTLS/src/MbedTLS.jl", {st_mode=S_IFREG|0644, st_size=3564, ...}) = 0
stat("/home/pfitzseb/.julia/dev/MbedTLS/src/MbedTLS.jl", {st_mode=S_IFREG|0644, st_size=3564, ...}) = 0
stat("/home/pfitzseb/.julia/dev/MbedTLS/src/MbedTLS.jl", {st_mode=S_IFREG|0644, st_size=3564, ...}) = 0
stat("/home/pfitzseb/.julia/dev/MbedTLS/deps/deps.jl", {st_mode=S_IFREG|0644, st_size=1656, ...}) = 0
stat("/home/pfitzseb/.julia/dev/MbedTLS/src/constants.jl", {st_mode=S_IFREG|0644, st_size=28091, ...}) = 0
stat("/home/pfitzseb/.julia/dev/MbedTLS/src/error.jl", {st_mode=S_IFREG|0644, st_size=789, ...}) = 0
stat("/home/pfitzseb/.julia/dev/MbedTLS/src/md.jl", {st_mode=S_IFREG|0644, st_size=5851, ...}) = 0
stat("/home/pfitzseb/.julia/dev/MbedTLS/src/cipher.jl", {st_mode=S_IFREG|0644, st_size=10086, ...}) = 0
stat("/home/pfitzseb/.julia/dev/MbedTLS/src/rsa.jl", {st_mode=S_IFREG|0644, st_size=3621, ...}) = 0
stat("/home/pfitzseb/.julia/dev/MbedTLS/src/entropy.jl", {st_mode=S_IFREG|0644, st_size=1674, ...}) = 0
stat("/home/pfitzseb/.julia/dev/MbedTLS/src/ctr_drbg.jl", {st_mode=S_IFREG|0644, st_size=1494, ...}) = 0
stat("/home/pfitzseb/.julia/dev/MbedTLS/src/pk.jl", {st_mode=S_IFREG|0644, st_size=3714, ...}) = 0
stat("/home/pfitzseb/.julia/dev/MbedTLS/src/x509_crt.jl", {st_mode=S_IFREG|0644, st_size=1113, ...}) = 0
stat("/home/pfitzseb/.julia/dev/MbedTLS/src/ssl.jl", {st_mode=S_IFREG|0644, st_size=24336, ...}) = 0
stat("/home/pfitzseb/.julia/dev/MbedTLS/src/debug.jl", {st_mode=S_IFREG|0644, st_size=421, ...}) = 0
read(15, "_DES_CBC_SHA=21\nconst MBEDTLS_TL"..., 131072) = 70721
openat(AT_FDCWD, "/home/pfitzseb/.julia/compiled/v1.2/MbedTLS/bf9T0.ji", O_RDONLY|O_CLOEXEC) = 15
openat(AT_FDCWD, "/home/pfitzseb/.julia/dev/MbedTLS/deps/usr/lib/libmbedcrypto.so", O_RDONLY|O_CLOEXEC) = 25
openat(AT_FDCWD, "/home/pfitzseb/Documents/julia-1.2.0-RC/bin/../lib/julia/libmbedtls.so.12", O_RDONLY|O_CLOEXEC) = 25
lstat("/home/pfitzseb/.julia/registries/General/M/MbedTLS", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
stat("/home/pfitzseb/.julia/registries/General/M/MbedTLS", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/home/pfitzseb/.julia/registries/General/M/MbedTLS", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 81
stat("/home/pfitzseb/.julia/registries/General/M/MbedTLS/.gitignore", 0x7fffe86d4fc0) = -1 ENOENT (No such file or directory)
lstat("/home/pfitzseb/.julia/registries/General/M/MbedTLS/Package.toml", {st_mode=S_IFREG|0644, st_size=115, ...}) = 0
lstat("/home/pfitzseb/.julia/registries/General/M/MbedTLS/Deps.toml", {st_mode=S_IFREG|0644, st_size=787, ...}) = 0
lstat("/home/pfitzseb/.julia/registries/General/M/MbedTLS/Versions.toml", {st_mode=S_IFREG|0644, st_size=2944, ...}) = 0
lstat("/home/pfitzseb/.julia/registries/General/M/MbedTLS/Compat.toml", {st_mode=S_IFREG|0644, st_size=444, ...}) = 0
write(2, "./julia: symbol lookup error: /h"..., 153./julia: symbol lookup error: /home/pfitzseb/Documents/julia-1.2.0-RC/bin/../lib/julia/libmbedtls.so.12: undefined symbol: mbedtls_pk_verify_restartable
```
So yeah, apparently Julia's loading `~/.julia/dev/MbedTLS/deps/usr/lib/libmbedcrypto.so` and `julia-1.2.0-RC/bin/../lib/julia/libmbedtls.so.12` (instead of the one in MbedTLS.jl).

**Comment by staticfloat** [comment]
That should be fine as long as they're the same version (which, if you're using Jacob's new branch, they should be).  What version of libraries are lying within `~/.julia/dev/MbedTLS/deps/usr/lib`?  Did you clean out your `~/.julia/dev/MbedTLS/deps/usr` so as to ensure that you don't have old libraries laying around in there even after switching branches?

**Comment by quinnj** [comment]
Hmmmmm.....what seems fishy to me is that `libmbedx509.so` never gets loaded? `mbedtls_pk_verify_restartable` should be defined in `libmbedcrypto`, but I think I remember seeing there might be issues if the mbed libraries aren't loaded in just the right order.

**Comment by pfitzseb** [comment]
Hm, after deleting `~/.julia/dev/MbedTLS/deps/usr` I can no longer repro the issue (terminal history [here](https://gist.github.com/pfitzseb/e5baab5b400df6c30d1a8366c4972ccc) if someone cares).

**Comment by staticfloat** [comment]
Yeah, I'm betting you just had old binaries laying around in `~/.julia/dev/MbedTLS/deps/usr`, so the new binaries were just never downloaded.

**Comment by quinnj** [comment]
@pfitzseb, I just pushed a couple of cleanup commits to the jq/1.2 branch in MbedTLS.jl (literally a few seconds ago); could you try again real quick just to make sure things work for you?

**Comment by pfitzseb** [comment]
Still works, afaict.
