### ISSUE TITLE
Internal error: encountered unexpected error in runtime: StackOverflowError()

### ISSUE THREAD

**Issue by thofma** [JuliaLang/julia#32433]
Here is a reduced version of the type inference problem we encounter at https://github.com/Nemocas/AbstractAlgebra.jl/pull/338:
```julia
abstract type T{a}                                                                                                                                           
end

function evaluate(a::b, ::Vector{b}, c) where b <: T{d}  where d
  evaluate(a, e, c)
end

function a()
  evaluate(b, c, [])  
end

a()
```
Internal error on v1.0.4 and v1.1.0:
```
Internal error: encountered unexpected error in runtime:
StackOverflowError()
save_env at /buildworker/worker/package_linux64/build/src/subtype.c:133
forall_exists_subtype at /buildworker/worker/package_linux64/build/src/subtype.c:1101
subtype_in_env at /buildworker/worker/package_linux64/build/src/subtype.c:1180
try_subtype_in_env at /buildworker/worker/package_linux64/build/src/subtype.c:1359
[...]
```
Full log of v1.0.4 and v1.1.0 run (they differ slightly): https://gist.github.com/thofma/b5990ee7be47c8babb658d6d3952017a)

On latest master it just gives (as expected):
```julia
ERROR: LoadError: UndefVarError: b not defined                                                                                                               
Stacktrace:
 [1] a() at /home/thofmann/creduce_julia/_bla.jl:9
 [2] top-level scope at /home/thofmann/creduce_julia/_bla.jl:12
 [3] include at ./boot.jl:328 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1094
 [5] include(::Module, ::String) at ./Base.jl:31
 [6] exec_options(::Base.JLOptions) at ./client.jl:295
 [7] _start() at ./client.jl:468
in expression starting at /home/thofmann/creduce_julia/_bla.jl:12
```

**Comment by JeffBezanson** [comment]
This might have been fixed. Do you need it backported to 1.0? #31167 might have fixed it.

**Comment by thofma** [comment]
I have cherry picked #31167 on top of the release-1.0 branch and the example from OP is still failing.

Also, it seems that this does not help with the original problem we are seeing at`https://github.com/wbhart/AbstractAlgebra.jl#speedup_evaluation` (https://github.com/Nemocas/AbstractAlgebra.jl/pull/338). There I get an `Internal error` on julia 1.0.4 and it just hangs on latest julia master.

**Comment by wbhart** [comment]
@JeffBezanson I think we have essentially decided to do our first Oscar CAS release against Julia LTS, so when these issues are fixed, we would need them backported. However, we also always test against master, so we can see and report these as they come up.

**Comment by thofma** [comment]
#31167 does not fix the issue, but could help to track it.

**Comment by wbhart** [comment]
I think the hang we are seeing in the Julia-1.2-rc2 when the AbstractAlgebra.jl tests are run is unrelated to this issue. We need to produce a minimal example that demonstrates it.

Even without Nemocas/AbstractAlgebra.jl#338 the test suite hangs. So it seems there are multiple issues in type inference in Julia-1.2-rc2. I will try to find a minimal example of the next one tomorrow.

**Comment by wbhart** [comment]
We no longer see the issue that we were seeing in (Nemocas/AbstractAlgebra.jl#338) that prompted this bug report. We don't know why that is, and it is all the more mysterious given that it now even passes in julia-1.1.1 which hasn't seen a new release. But given that we can no longer reproduce this, I consider it solved.

There are three other issues which I exhibit in my GitHub repo [1] in branches bug2, bug3, bug4, one of which (bug4) may be related to the original issue we see here. But as far as this issue itself is concerned and the issue that motivated us reporting it, we no longer see it in any version of Julia. We will work on minimal reproducible examples of bug2, bug3 and bug4.

I'm not sure on the status of backporting in Julia itself. But from our perspective, this ticket can otherwise be closed.

[1] https://github.com/wbhart/AbstractAlgebra.jl
