### ISSUE TITLE
Repeated sizehint! can leak memory

### ISSUE THREAD

**Issue by cstjean** [JuliaLang/julia#33912]
On 1.2.0, Linux, it seems that repeated `sizehint!` calls grow the underlying memory used without bounds:

```julia
julia> vector_capacity(v::Vector) = ccall(:jl_array_size, Int, (Any, UInt), v, 1)
vector_capacity (generic function with 1 method)

julia> let
          v = rand(10_000)
          for _ in 1:100_000
              popfirst!(v)
              sizehint!(v, 10_000)
              push!(v,  2.0)
          end
          println(vector_capacity(v))
       end
219998
```

I'm poking into internals I don't really understand, so perhaps I'm wrong?

Other bug (maybe?), without `sizehint!`

```julia
julia> let
          v = rand(10_000)
          for _ in 1:100_000
              popfirst!(v)
              push!(v,  2.0)
          end
          println(vector_capacity(v))
      end
40000
```

The maximum length of the vector is 10_000, isn't it odd/wasteful that the memory usage grows to 4X the initial size?

**Comment by KristofferC** [comment]
I think the reason for this is that the `offset` field in `jl_array` keeps growing until it is quite large before it gets limited by

https://github.com/JuliaLang/julia/blob/25beaf5f3e28adb76fad26649ffe1ab81647d8ba/src/array.c#L975-L987

In the second case, `offset` grows until it is 26000 (and `maxsize` is then 40000) and then not until then does `offset` gets limited. We can simulate what happens with:

```jl
let offset = 1; arr_len = 10000;
    siz = arr_len
    offset_coefficient = 13/20 
    while true
        offset += 1
        siz += 1
        if siz > arr_len
            arr_len *= 2
        end
        if offset >= offset_coefficient * arr_len
            break
        end
    end
    @show offset, siz, arr_len
    nothing
end

# (offset, siz, arr_len) = (26000, 35999, 40000)
```

Changing the `offset_coefficient` can also end up changing the final size.

**Comment by KristofferC** [comment]
The first case seems to be happening because of ping-ponging between `sizehint!` shrinking memory and `push!` increasing it in every iteration. The `offset` field increases by one in each iteration from the `popfirst!` leading to the `maxsize` increases by `2` in every iteration. And since the `maxsize` is always growing, the `offset` limiting discussed above never kicks in because it is a factor of `maxsize`.

**Comment by adienes** [comment]
fixed sometime in 1.11
```
julia> let
          v = rand(10_000)
          for _ in 1:100_000
              popfirst!(v)
              sizehint!(v, 10_000)
              push!(v,  2.0)
          end
          println(vector_capacity(v))
       end

10000
```

**Comment by oscardssmith** [comment]
This is improved but not yet fixed on 1.11. Using the slightly modified version
```
@time let
    v = rand(10_000)
    for _ in 1:100
        popfirst!(v)
        sizehint!(v, 10_000)
        push!(v,  2.0)
        println(vector_capacity(v))
    end
end
```
we get 
```
# 1.10
27634
27635
27636
27637
27638
27639
27640
27641
27643
27644
27645
27646
27647
27648
27649
27650
27652
27653
27654
27655
27656
27657
27658
27659
27661
...
```
vs
```
# 1.11
27634
10000
27634
10000
27634
10000
...
```
So we're still resizing every time we go through the loop, although we're doing so in a slightly less dumb way. OTOH, in 1.11 if you use `sizehint!(v, 10_000, first=true)`, this only resizes the array a single time
