### ISSUE TITLE
LoggingExtras error on 1.5.0-rc1 for DiffEqBase

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaLang/julia#36519]
1.4 is fine, and 1.6-dev also works great, but on 1.5.0-rc1, if I run a simple example
```julia
using OrdinaryDiffEq
c = 5.730
u0 = 1.0
tspan = (0.0, 1.0)
radioactivedecay(u,p,t) = -c*u
prob = ODEProblem(radioactivedecay,u0,tspan)
```
I get the error
```julia
Info: Precompiling OrdinaryDiffEq [1dea7af3-3e70-54e6-95c3-0bf5283fa5ed]
└ @ Base loading.jl:1278
┌ Warning: Package DiffEqBase does not have Logging in its dependencies:
│ - If you have DiffEqBase checked out for development and have
│   added Logging as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with DiffEqBase
└ Loading Logging into DiffEqBase from project dependency, future warnings for DiffEqBase are suppressed.
ERROR: LoadError: ArgumentError: Package DiffEqBase does not have LoggingExtras in its dependencies:
- If you have DiffEqBase checked out for development and have
  added LoggingExtras as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with DiffEqBase
Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:906
 [2] include(::Function, ::Module, ::String) at ./Base.jl:380
 [3] include(::Module, ::String) at ./Base.jl:368
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:331 [inlined]
 [6] eval(::Expr) at ./client.jl:467
 [7] top-level scope at ./none:3
in expression starting at /Users/abradley/.julia/packages/DiffEqBase/gzrxg/src/DiffEqBase.jl:8
ERROR: LoadError: Failed to precompile DiffEqBase [2b5f629d-d688-5b77-993f-72d75c75574e] to /Users/abradley/.julia/compiled/v1.5/DiffEqBase/oaevG_9q13g.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1290
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923
 [6] include(::Function, ::Module, ::String) at ./Base.jl:380
 [7] include(::Module, ::String) at ./Base.jl:368
 [8] top-level scope at none:2
 [9] eval at ./boot.jl:331 [inlined]
 [10] eval(::Expr) at ./client.jl:467
 [11] top-level scope at ./none:3
in expression starting at /Users/abradley/.julia/packages/OrdinaryDiffEq/nV9bA/src/OrdinaryDiffEq.jl:4

Failed to precompile OrdinaryDiffEq [1dea7af3-3e70-54e6-95c3-0bf5283fa5ed] to /Users/abradley/.julia/compiled/v1.5/OrdinaryDiffEq/DlSvy_9q13g.ji.

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1290
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923
 [6] top-level scope at In[1]:1
```

```julia
julia> versioninfo()
Julia Version 1.5.0-rc1.0
Commit 24f033c951 (2020-06-26 20:13 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.4.0)
  CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

I have also tried `update`, `resolve` and restarting. No change...

**Comment by ChrisRackauckas** [comment]
Bump? This seems like it wold be blocking for a v1.5 release given that packages which utilize logging (and have it stated in the Project.toml) are having issues?

**Comment by KristofferC** [comment]
Can't repro. If this problem only occurs when using multiple registers, then https://github.com/JuliaLang/Pkg.jl/pull/1884 probably fixes it.

**Comment by AshtonSBradley** [comment]
this seems to have been fixed

**Comment by fingolfin** [comment]
I think this can be closed, unless @AshtonSBradley can still reproduce this in Julia 1.5.2?

**Comment by AshtonSBradley** [comment]
Works on julia 1.5.2
