### ISSUE TITLE
@threads over iterator requires collect

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/julia#37435]
on a 0-day master:

```
julia> using Base.Iterators

julia> for i in partition(1:9,3); @info i; end
[ Info: 1:3
[ Info: 4:6
[ Info: 7:9

julia> Threads.@threads for i in partition(1:9,3); @info i; end
ERROR: TaskFailedException
Stacktrace:
 [1] wait
   @ ./task.jl:303 [inlined]
 [2] threading_run(func::Function)
   @ Base.Threads ./threadingconstructs.jl:34
 [3] top-level scope
   @ ./threadingconstructs.jl:93

    nested task error: MethodError: no method matching firstindex(::Base.Iterators.PartitionIterator{UnitRange{Int64}})
    Closest candidates are:
      firstindex(::StepRange) at range.jl:555
      firstindex(::UnitRange) at range.jl:554
      firstindex(::Number) at number.jl:70
      ...
    Stacktrace:
     [1] (::var"#2#threadsfor_fun#1"{Base.Iterators.PartitionIterator{UnitRange{Int64}}})(onethread::Bool)
       @ Main ./threadingconstructs.jl:66
     [2] (::var"#2#threadsfor_fun#1"{Base.Iterators.PartitionIterator{UnitRange{Int64}}})()
       @ Main ./threadingconstructs.jl:48

julia> Threads.@threads for i in collect(partition(1:9,3)); @info i; end
[ Info: 1:3
[ Info: 4:6
[ Info: 7:9
```

**Comment by Moelf** [comment]
I think this is one of those thing where users should be explicitly knowing they are now concreting the `iterator` if they want to thread it, imagine each element in the iterator is 10% of RAM.

**Comment by tkf** [comment]
FYI, [`FLoops.@floop`](https://github.com/JuliaFolds/FLoops.jl) and [`ThreadsX.foreach`](https://github.com/tkf/ThreadsX.jl) both can be used in place of `@threads` and support a rich set of data containers and iterator combinators based on [SplittablesBase.jl](https://github.com/JuliaFolds/SplittablesBase.jl) interface. I think we need something like SplittablesBase.jl in Base to support generic collections in `@threads`.

**Comment by Matthew-D-Dwyer** [comment]
Hi I tried to replicate this issue today and it seems to have been resolved. 

Is there a need for this or can the issue be closed? 

`julia> using Base.Iterators

julia> for i in partition(1:9,3); @info i; end
[ Info: 1:3
[ Info: 4:6
[ Info: 7:9

julia> Threads.@threads for i in collect(partition(1:9,3)); @info i; end
[ Info: 1:3
[ Info: 4:6
[ Info: 7:9

julia> Threads.@threads for i in collect(partition(1:9,3)); @info i; end
[ Info: 1:3
[ Info: 4:6
[ Info: 7:9
`

**Comment by bjarthur** [comment]
no, it is not resolved-- both of your last two loops are identical and have a `collect`.

the issue is about the inability of `@threads` to handle iterators.  `Threads.foreach` iterates over a channel.  why can't `@threads` iterate too?  i suspect there might be a reason why this might be hard to implement, but from user's perspective it is confusing.  it shouldn't have to be materialized.

**Comment by vchuravy** [comment]
>  why can't `@threads` iterate too?
 
Currently `@threads` processes everything in chunks, and if you want to support that then as Taka said in his comment you would need how to generically split the iterator into chunks :). 

> ... and support a rich set of data containers and iterator combinators based on [SplittablesBase.jl](https://github.com/JuliaFolds/SplittablesBase.jl) interface. I think we need something like SplittablesBase.jl in Base to support generic collections in `@threads`.


If you don't want to process things in Chunks it's a lot simpler, but then the performance for little work in the loop will be worse.

```
@sync for i in partition(1:9,3)
   Threads.@spawn begin
       @show i
   end
end
```

**Comment by tkf** [comment]
I agree `partition` is a useful and easy approach applicable to a wide class of parallelizable programs. That said, I believe it has various problems and the Julia ecosystem deserves more. To be more specific, let me enumerate some problems come with `partition`:

### Problem 1: `partition` on generic iterable effectively copies input.

`partition` only has optimization on arrays (and ranges)

https://github.com/JuliaLang/julia/blob/f0c46b3908d0500f8aaaa6155e022625f7feb8c3/base/iterators.jl#L1220-L1224

and the generic implementation constructs a `Vector` for each iteration

https://github.com/JuliaLang/julia/blob/f0c46b3908d0500f8aaaa6155e022625f7feb8c3/base/iterators.jl#L1228

https://github.com/JuliaLang/julia/blob/f0c46b3908d0500f8aaaa6155e022625f7feb8c3/base/iterators.jl#L1233

So, `partition` on generic iterable is at least _currently_ not more efficient than `collect`-first approach. In fact, the performance can be much worse if the input collection does not provide precise `eltype` (which is impossible in many cases; e.g., `Iterators.map`) as it does not use the idiomatic mutate-or-widen approach used in `collect`. This may be partially due to the absence of reusable mutate-or-widen infrastructure in Base (like [BangBang.jl](https://github.com/JuliaFolds/BangBang.jl)).

Of course, the above points are the limitation simply due to the lack of optimizations (as of 1.8-DEV) and not the fundamental one. However, I think `partition` also has some fundamental issues:

### Problem 2: Sequential spawn has less parallelism

Sequential spawn that often appears in the `partition`-based approach has less [parallelism (work-span ratio)](https://www.cprogramming.com/parallelism.html). I find it matters with high core counts. It also matters when splittng (pre-schedule) and merge (post-wait) phases have some computation cost. The former appears when dealing with not (quite) random accessible collections like sparse arrayns and UTF-8 strings. The latter appears when merging non-trivial results like dictionary (e.g., `countmap`).

### Problem 3: `partition` definition does not compose

`partition` cannot be defined efficiently for collections without random access.
This can be handled easily with splitting-based approach if the API allows imprecise split (like SplittablesBase.jl does). This also helps composability since `zip` works as long as only at most one collection in the `zip` does not support exact splitting.

**Comment by KristofferC** [comment]
>  why can't @threads work this way?

Note the docs for `@threads`:

>   The schedule argument can be used to request a particular scheduling
  policy. The only currently supported value is `:static`, which creates one
  task per thread and divides the iterations equally among them. Specifying
  `:static` is an error if used from inside another `@threads` loop or from a
  thread other than 1.
>  The default schedule (used when no schedule argument is present) is
  subject to change.

So it could work differently, it is just that it doesn't.

**Comment by tkf** [comment]
Note that `partition` is not an example. What Valentin suggested is a *generic transformation* (albeit manual) you can use for an arbitrary iterator.

> `Threads.foreach` seems to do something similar

It uses a `Channel`. It is important to remember that queues (e.g., `Channel`) are all about sequentializing the access. It's the opposite of parallelism.

For "generic" `@threads for` implementation, `partition`-based approach is less bad.

> one should be able to `@threads` _any_ for-loop

We need at least some restriction of the properties of the loop body like race freedom and associativity. Furthermore, `@threads` is not designed to be generic even for parallelizable loops that can include reduction and `break`.

All of this is implemented in [JuliaFolds/FLoops.jl](https://github.com/JuliaFolds/FLoops.jl). You can even use [`@floop FoldsThreads.NondeterministicEx() for ...`](https://juliafolds.github.io/FoldsThreads.jl/dev/#FoldsThreads.NondeterministicEx) with arbitrary (possibly non-race-free) iterable that can automatically chunk the input space. This is a much more efficient approach than `Threads.foreach`. Furthermore, JuliaFolds executor framework is designed to be flexible enough to implement the `Threads.foreach` approach if it works better for some programs. An interesting direction for this is to use [more throughput-oriented concurrent queue](https://discourse.julialang.org/t/concurrentcollections-jl-lock-free-dictionary-queue-etc-for-julia-1-7/72501) inside the executor.

**Comment by adienes** [comment]
I think the most direct solution nowdays is to use `@threads :greedy` 
closing, but please reopen if that solution is not sufficient here.

**Comment by bjarthur** [comment]
indeed, `greedy` works, thank you!

```
julia> using Base.Iterators

julia> Threads.@threads :greedy for i in partition(1:9,3); @info i; end
[ Info: 1:3
[ Info: 4:6
[ Info: 7:9
```
