### ISSUE TITLE
Build fails with USE_SYSTEM_CSL=1

### ISSUE THREAD

**Issue by antonio-rojas** [JuliaLang/julia#40201]
When using USE_SYSTEM_CSL=1, the build system still tries to call an internal libgcc_s.so.1 (which obviously fails)
```
cd /build/julia/src/julia-1.6.0/base && /build/julia/src/julia-1.6.0/usr/bin/julia -C "x86-64" --output-ji /build/julia/src/julia-1.6.0/usr/lib/julia/corecompiler.ji.tmp --startup-file=no --warn-overwrite=yes -g0 -O0 compiler/compiler.jl
ERROR: Unable to load dependent library /build/julia/src/julia-1.6.0/usr/bin/../lib/libgcc_s.so.1
Message:/build/julia/src/julia-1.6.0/usr/bin/../lib/libgcc_s.so.1: cannot open shared object file: No such file or directory
```

**Comment by yuyichao** [comment]
This is what @staticfloat [claims that](https://github.com/JuliaLang/julia/pull/37832)

> certainly not the kind of build we like to create.

I'm looking forward to when that statement is changed.

**Comment by staticfloat** [comment]
@antonio-rojas can you show me the output of the following?  You can clear everything out with `git clean -fdx` first, and then run the commands to reduce variation from outside things:

```
$ make USE_SYSTEM_CSL=1 VERBOSE=1 -C deps install-csl
make: Entering directory '/home/sabae/src/julia/deps'
make: [/home/sabae/src/julia/deps/csl.mk:38: /home/sabae/src/julia/usr/lib/libgfortran.so.3] Error 1 (ignored)
make: [/home/sabae/src/julia/deps/csl.mk:39: /home/sabae/src/julia/usr/lib/libgfortran.so.4] Error 1 (ignored)
make: [/home/sabae/src/julia/deps/csl.mk:45: /home/sabae/src/julia/usr/lib/libssp.so.0] Error 1 (ignored)
make: Leaving directory '/home/sabae/src/julia/deps'
$ ls -la usr/lib/
total 5604
drwxrwxr-x 2 sabae sabae    4096 Mar 26 16:59 .
drwxrwxr-x 3 sabae sabae    4096 Mar 26 16:59 ..
-rw-r--r-- 1 sabae sabae   30968 Mar 26 16:59 libatomic.so.1
-rw-r--r-- 1 sabae sabae  104984 Mar 26 16:59 libgcc_s.so.1
-rw-r--r-- 1 sabae sabae 2911456 Mar 26 16:59 libgfortran.so.5
-rw-r--r-- 1 sabae sabae  265856 Mar 26 16:59 libgomp.so.1
-rwxr-xr-x 1 sabae sabae  157224 Mar 26 16:59 libpthread.so.0
-rw-r--r-- 1 sabae sabae  297784 Mar 26 16:59 libquadmath.so.0
-rw-r--r-- 1 sabae sabae 1952928 Mar 26 16:59 libstdc++.so.6
```

When running with `USE_SYSTEM_CSL=1` it should automatically discover your `libgcc_s.so.1` location and install it within the build prefix accordingly, so that this Julia installation can be made portable with a future `make binary-dist`.

**Comment by yuyichao** [comment]
> so that this Julia installation can be made portable with a future make binary-dist.

No, when building with system library it must not be copied.

**Comment by antonio-rojas** [comment]
> @antonio-rojas can you show me the output of the following? You can clear everything out with `git clean -fdx` first, and then run the commands to reduce variation from outside things:

```
==> Starting build()...
make: Entering directory '/build/julia/src/julia-1.6.0/deps'
Warning: git information unavailable; versioning information limited
make: [/build/julia/src/julia-1.6.0/deps/csl.mk:38: /build/julia/src/julia-1.6.0/usr/lib/libgfortran.so.3] Error 1 (ignored)
make: [/build/julia/src/julia-1.6.0/deps/csl.mk:39: /build/julia/src/julia-1.6.0/usr/lib/libgfortran.so.4] Error 1 (ignored)
make: [/build/julia/src/julia-1.6.0/deps/csl.mk:45: /build/julia/src/julia-1.6.0/usr/lib/libssp.so.0] Error 1 (ignored)
make: Leaving directory '/build/julia/src/julia-1.6.0/deps'
total 35632
drwxr-xr-x 1 builduser builduser      200 Mar 26 17:38 .
drwxr-xr-x 1 builduser builduser        6 Mar 26 17:38 ..
-rwxr-xr-x 1 builduser builduser   167224 Mar 26 17:38 libatomic.so.1
-rw-r--r-- 1 builduser builduser   593928 Mar 26 17:38 libgcc_s.so.1
-rwxr-xr-x 1 builduser builduser 11803112 Mar 26 17:38 libgfortran.so.5
-rwxr-xr-x 1 builduser builduser  1555728 Mar 26 17:38 libgomp.so.1
-rwxr-xr-x 1 builduser builduser   154032 Mar 26 17:38 libpthread.so.0
-rwxr-xr-x 1 builduser builduser  1250200 Mar 26 17:38 libquadmath.so.0
-rwxr-xr-x 1 builduser builduser 20947728 Mar 26 17:38 libstdc++.so.6
```

**Comment by staticfloat** [comment]
Hmmm, so it looks like that library is indeed copied.  Can you show me the output of:

```
$ ldd ./usr/lib/libgcc_s.so.1 
        linux-vdso.so.1 (0x00007ffefa1b6000)         
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff100da0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff100fbc000)
```

And can you test to see that the build does indeed fail with that error again?

**Comment by antonio-rojas** [comment]
When the build fails, those libraries are not in usr/lib, the full contents are:
```
drwxr-xr-x 1 arojas users      512 Mar 26 17:42 .
drwxr-xr-x 1 arojas users       90 Mar 26 17:41 ..
drwxr-xr-x 1 arojas users      508 Mar 26 17:41 julia
drwxr-xr-x 1 arojas users       16 Mar 26 17:41 pkgconfig
-rwxr-xr-x 1 arojas users    35960 Mar 26 17:41 libccalltest.so
-rwxr-xr-x 1 arojas users    57120 Mar 26 17:41 libccalltest.so.debug
-r-xr-xr-x 1 arojas users    22120 Mar 26 17:41 libdSFMT.so
lrwxrwxrwx 1 arojas users       24 Mar 26 17:42 libjulia-internal.so -> libjulia-internal.so.1.6
lrwxrwxrwx 1 arojas users       24 Mar 26 17:42 libjulia-internal.so.1 -> libjulia-internal.so.1.6
-rwxr-xr-x 1 arojas users 50506064 Mar 26 17:42 libjulia-internal.so.1.6
lrwxrwxrwx 1 arojas users       15 Mar 26 17:41 libjulia.so -> libjulia.so.1.6
lrwxrwxrwx 1 arojas users       15 Mar 26 17:41 libjulia.so.1 -> libjulia.so.1.6
-rwxr-xr-x 1 arojas users   270624 Mar 26 17:41 libjulia.so.1.6
-rwxr-xr-x 1 arojas users  1252112 Mar 26 17:42 libllvmcalltest.so
-rwxr-xr-x 1 arojas users    15048 Mar 26 17:41 libsuitesparse_wrapper.so
-rw-r--r-- 1 arojas users  1178582 Mar 26 17:41 libuv.a
-rwxr-xr-x 1 arojas users      929 Mar 26 17:41 libuv.la
lrwxrwxrwx 1 arojas users       14 Mar 26 17:41 libuv.so -> libuv.so.2.0.0
lrwxrwxrwx 1 arojas users       14 Mar 26 17:41 libuv.so.2 -> libuv.so.2.0.0
-rwxr-xr-x 1 arojas users   576545 Mar 26 17:41 libuv.so.2.0.0
```
so it doesn't look like `make -C deps install-cls` is being run.

**Comment by staticfloat** [comment]
Makefile bug then. If you run the install-csl step manually first, then run the rest of the build, does it go through?

**Comment by antonio-rojas** [comment]
> Makefile bug then. If you run the install-csl step manually first, then run the rest of the build, does it go through?

Yes, simply symlinking `/usr/lib/libgcc_s.so.1` in `./usr/lib` is enough

**Comment by staticfloat** [comment]
This PR should fix the issue: https://github.com/JuliaLang/julia/pull/40217

We'll get that backported for a future 1.6.1 release, but if you don't want to wait that long, [the patch](https://github.com/JuliaLang/julia/pull/40217/files) is quite small and can be applied in build systems easily.

**Comment by antonio-rojas** [comment]
Thanks, this does fix the build. However, runtime is still broken, because the libraries are not symlinked in the installed `/usr/lib/julia`, unlike all other used system libraries.
```
> julia
ERROR: Unable to load dependent library /usr/bin/../lib/julia/libgcc_s.so.1
Message:/usr/bin/../lib/julia/libgcc_s.so.1: cannot open shared object file: No such file or directory
```

**Comment by staticfloat** [comment]
Sorry, I thought you meant it had gone through completely.

What precise steps have you taken?  When building locally on my machine, using the patch linked above, I am able to `make install` and run the resulting julia binary.  Did you do something different?

**Comment by antonio-rojas** [comment]
Essentially just a `make` and `make install`. You can see the full build script at https://github.com/archlinux/svntogit-community/blob/packages/julia/trunk/PKGBUILD - I just replaced the workaround at lines 38 and 108 with the patch.

**Comment by staticfloat** [comment]
I've got a new implementation that should symlink instead of copy on that PR.  Can you pull it and ensure that it works for you?

**Comment by antonio-rojas** [comment]
> I've got a new implementation that should symlink instead of copy on that PR. Can you pull it and ensure that it works for you?

Still doesn't work. I see the symlink is created in `./usr/lib/julia`, but `make install` doesn't install it in DESTDIR

**Comment by antonio-rojas** [comment]
With this additional change everything works
```
--- a/Makefile
+++ b/Makefile
@@ -291,7 +291,7 @@ endif
        done \
        done
        for suffix in $(JL_PRIVATE_LIBS-1) ; do \
-               lib=$(build_private_libdir)/$${suffix}.$(SHLIB_EXT); \
+               lib=$(build_private_libdir)/$${suffix}.$(SHLIB_EXT)*; \
                $(INSTALL_M) $$lib $(DESTDIR)$(private_libdir) ; \
        done
 endif
```

**Comment by staticfloat** [comment]
Good catch; I've adapted the patch and pushed to my branch.
