### ISSUE TITLE
Regression for CTRL-C in Julia 1.7.0-rc3

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaLang/julia#43103]
It's a regression from rc1 at least, there CRTL-C worked.

With this program:
https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/binarytrees-julia-3.html

```
$ ~/julia-1.7.0-rc3/bin/julia -O3 --cpu-target=ivybridge --math-mode=ieee  -- bt.jl 21
stretch tree of depth 22	 check: 8388607
^C
```

the program hangs over a minute and counting. Without pressing CTRL-C it finishes in 13 sec. max.

I believe there's no guarantee that CTRL-C always working (nor kill, is that the same signal?), but it's an annoying regression (and misleads while benchmarking if not realized), and it seems if Julia isn't listening, then it should at least be ignored.

I may be getting slightly better speed though, with 0m12,267s for rc3 vs 0m12,705s for rc1, Or rather random load effect as later I got 0m12,385s.

**Comment by PallHaraldsson** [comment]
This seems like a pure regression, with no speed advantage. I retested without the web browser (Brave) running, and it seems rather random which is faster rc1 or rc3, at least JULIA_NUM_THREADS=4 (an important benchmark), without it, maybe a slight edge 0m10,726s vs 0m10,979s.

```
$ time JULIA_NUM_THREADS=4 ~/julia-1.7.0-rc1/bin/julia -O3 --cpu-target=ivybridge --math-mode=ieee  -- bt.jl 21
[..]
real	0m9,097s
user	0m23,734s
sys	0m5,292s


$ time JULIA_NUM_THREADS=4 ~/julia-1.7.0-rc3/bin/julia -O3 --cpu-target=ivybridge --math-mode=ieee  -- bt.jl 21
[..]
real	0m9,006s
user	0m24,220s
sys	0m5,502s
```

**Comment by Seelengrab** [comment]
CTRL-C by convention sends SIGINT, which is a distinct signal from SIGKILL.

**Comment by PallHaraldsson** [comment]
Right, about SIGKILL, The default is SIGTERM, I'm not sure how differently it's handled from SIGINT. Maybe it isn't (while could in theory). At least something is done on SIGINT since the Julia process goes from up to 108% load down to disappearing in top.

If I'm really quick I manage to send a kill, i.e. SIGTERM, and it seems to have same effect as SIGINT, i.e. hangs for 2+ min. and counting.

**Comment by Seelengrab** [comment]
I'm just another user, I can't add labels here :shrug: If it worked in 1.7-rc1 and doesn't work on 1.7-rc3, it should be fixed before a final 1.7 release though.

**Comment by KristofferC** [comment]
> If it worked in 1.7-rc1 and doesn't work on 1.7-rc3, it should be fixed before a final 1.7 release though.

That is not necessarily the case. Many things behave in a certain way by chance and changes to that behavior are fine as long as the original behavior was not explicitly supported.

There are many issues with Ctrl-C e.g.: https://github.com/JuliaLang/julia/issues/35524.

**Comment by JeffBezanson** [comment]
Yeah, I'm not sure if this is due to a specific change. Could somebody try bisecting it to see if there is a direct cause?

**Comment by dpinol** [comment]
I can reproduce a regression of 1.7rc3 wrt 1.7rc2 on linux.
If user presses CTRL-C during `Base.readline(stdin)` execution, in 1.7rc3 the application hangs (normal kill does not terminate julia, you need kill -9). In previous versions, applications show stacktrace and quits.

**Comment by PallHaraldsson** [comment]
This is fixed on master. It's hard to tell if master is faster, speed varies for both, lots of overlap, but I've got a bit faster on maser if I recall. I had a PR in mind from last few days than might have fixed why I checked. Should it then be backported?

I wanted to save people the trouble of bisecting backwards, should it be done or even forwards?

**Comment by dpinol** [comment]
This is still happening in 1.7.0 release. Any chance that the fix in master could be backported to 1.7.x? thanks

**Comment by vinzenz-muser** [comment]
I can confirm, this is an issue... I also made a [post]( https://discourse.julialang.org/t/julia-1-7-0-ignores-sigterms-signal-15/72357) in the community forum. I think that's pretty relevant for productive systems, especially if you have to shutdown containers gracefully.

**Comment by maleadt** [comment]
I can't reproduce the CTRL-C/SIGINT issue, but SIGTERM at least behaves differently as noted in https://discourse.julialang.org/t/julia-1-7-0-ignores-sigterms-signal-15/72357.

MWE:

```
tim@virgo ~$ julia-1.7 -e 'sleep(999)' &                            
[1] 449191
tim@virgo ~$ kill -SIGTERM 449191
# does nothing
tim@virgo ~$ kill -SIGKILL 449191
[1]  + killed

tim@virgo ~$ julia-nightly -e 'sleep(999)' &
[1] 449341
tim@virgo ~$ kill -SIGTERM 449341
signal (15): Terminated
```

Bisected:

```
75961b229862fac9ae9dbc621145a181bd5ac092 is the first bad commit
commit 75961b229862fac9ae9dbc621145a181bd5ac092
Author: Jameson Nash <vtjnash@gmail.com>
Date:   Sun Oct 31 23:05:31 2021 -0400

    handle some cases of null Task in segv handling (#42836)
    
    Also ensure we do not use round-robin sampling when printing a critical
    error, only for profiling.
    
    (cherry picked from commit ad607a225b0691f17bbac406fc59d426dabaabe0)
```

cc @vtjnash

**Comment by fredrikekre** [comment]
#43381
