### ISSUE TITLE
"`rationalize`" a rational

### ISSUE THREAD

**Issue by ParadaCarleton** [JuliaLang/julia#43369]
It might be useful to have `rationalize(x)` return `x` if `x` is already rational, to allow generic code that takes both reals and rationals as inputs.

**Comment by ayushsengupta8** [comment]
Hello,
I am completely new to open source projects and would like to try to solve this issue.
I can use a convert() function to rationalize(x), however, it would be helpful if I know in which folder, in which file do I have to change/add the code. @logankilpatrick

**Comment by fredrikekre** [comment]
As you can see by the link just above your comment someone has already started to work on this.

**Comment by ayushsengupta8** [comment]
@fredrikekre Oh! Thanks...and sorry for the lame comment

**Comment by ndinsmore** [comment]
@dkarrasch  I was just looking at this issue and it looks like you meant for it to be closed by https://github.com/JuliaLang/julia/pull/43427

**Comment by vmpyr** [comment]
This issue seems to have been resolved. I think it should be closed now

**Comment by vtjnash** [comment]
Still fails. (waiting for https://github.com/JuliaLang/julia/pull/43427 to be merged)
```
julia> rationalize(rationalize(1.0))
ERROR: MethodError: no method matching rationalize(::Rational{Int64})
```

**Comment by vmpyr** [comment]
I am sorry, I misinterpreted something. My bad. Is that PR still WIP?

**Comment by ParadaCarleton** [comment]
> I am sorry, I misinterpreted something. My bad. Is that PR still WIP?

I don't think it is, so much as it's finished but hasn't been merged.
