### ISSUE TITLE
CI: Linux i686 (32-bit) nightlies return 404

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/julia#45045]

**Comment by DilumAluthge** [comment]
This is likely due to a problem with Buildbot.

The plan here is to work on finishing the transition of Linux i686 to Buildkite.

**Comment by SaschaMann** [comment]
In case it ends up being something else, some additional info:

- I first noticed the issue around April 19th 17:45 UTC due to a [failing test build](https://github.com/julia-actions/setup-julia/actions/runs/2191253675) in `setup-julia`
- The [last working build](https://github.com/julia-actions/setup-julia/actions/runs/2185173177) happened the day before around April 18th 17:45 UTC

**Comment by DilumAluthge** [comment]
This should hopefully be fixed by https://github.com/JuliaCI/julia-buildkite/pull/111

**Comment by SaschaMann** [comment]
The master nightlies work again, but the 32-bit nightlies for the 1.8 release branch are still broken.

Is the fix coming for that branch as well? If not I'll remove them from the setup-julia CI for now
