### ISSUE TITLE
undesirable output when showing empty set in the REPL

### ISSUE THREAD

**Issue by StephenVavasis** [JuliaLang/julia#45229]
I am currently working on `SortedSet` from the package `DataStructures.jl`. SortedSet does not have its own output routines; instead, it relies on the routines inherited from `AbstractSet` in Base.  However, these routines have unexpected behavior for an empty set.  (Julia 1.7.1 on Windows, see below).  I confirmed that the REPL output for ordinary `Set` is also inconsistent when the set is empty, but in the case of ordinary `Set` the issue is less obvious.

```julia-repl
julia> s = SortedSet{Int}([4,3,2,1])
SortedSet{Int64, Base.Order.ForwardOrdering} with 4 elements:
  1
  2
  3
  4

julia> s = SortedSet{Int}([])
SortedSet{Int64, Base.Order.ForwardOrdering}(DataStructures.BalancedTree23{Int64, Nothing, Base.Order.ForwardOrdering}(Base.Order.ForwardOrdering(), DataStructures.KDRec{Int64, Nothing}[DataStructures.KDRec{Int64, Nothing}(1, 2, nothing), DataStructures.KDRec{Int64, Nothing}(1, -1, nothing)], DataStructures.TreeNode{Int64}[DataStructures.TreeNode{Int64}(1, 2, 0, 0, 221796496, 31538)], 1, 1, Int64[], Int64[], BitSet([1, 2]), [224399536, 0, 0], [281825360, 0, 0]))
```

**Comment by Moelf** [comment]
it's just how things are displayed:
```julia
julia> []
Any[]

julia> [1]
1-element Vector{Int64}:
 1
```

**Comment by StephenVavasis** [comment]
Could you elaborate a bit more?  Why is it a good idea to display 0-entry collections differently from collections with one or more entries?

**Comment by Moelf** [comment]
It doesn't matter, as long as it's readable and not confusing.

**Comment by StephenVavasis** [comment]
But in this case (specialized for SortedSet), it's not readable and it is confusing.  Methods written for `AbstractSet` or other abstract classes in Base should be reasonably flexible for library writers.

Can you tell me: what exactly is that big string that is in my original posting?  What statement in Base produced that?

**Comment by Moelf** [comment]
>But in this case (specialized for SortedSet), it's not readable and it is confusing.

thus my original suggestion: opening an issue in `DataStructures.jl`.

**Comment by StephenVavasis** [comment]
I continue to think this should be fixed in Base.  If functions associated with abstract classes in Base that needlessly cause problems for library writers, this somewhat defeats the purpose of even having abstract classes in Base.

But in any case, do you know which statement in Base generated that very long string in my original post?  This might inform me what needs to be done with SortedSet.

**Comment by inkydragon** [comment]
Mabye update julia?

julia v1.7.2 + DataStructures v0.18.12
```jl
julia> s = SortedSet{Int}([4,3,2,1])
SortedSet{Int64, Base.Order.ForwardOrdering} with 4 elements:
  1
  2
  3
  4

julia> s = SortedSet{Int}([])
SortedSet(Int64[],
Base.Order.ForwardOrdering())

julia> SortedSet{Int}(Any[])
SortedSet(Int64[],
Base.Order.ForwardOrdering())

julia> SortedSet{Int}([])
SortedSet(Int64[],
Base.Order.ForwardOrdering())

julia> versioninfo()
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)

(@v1.7) pkg> st
      Status `C:\Users\woclass\.julia\environments\v1.7\Project.toml`
  [6e4b80f9] BenchmarkTools v1.2.2
  [864edb3b] DataStructures v0.18.12
  [31a5f54b] Debugger v0.6.8

```

**Comment by StephenVavasis** [comment]
OK, thanks! This helped me get started.  What I found is: there are several classes in Base derived from AbstractSet including BitSet, Set, KeySet, and IdSet.  Of these, none relies on `show` for `AbstractSet` except the unexported IdSet.  So this means that the `show` method for AbstractSet is provided mainly for library writers, especially library writers for DataStructures.jl such as myself.  And indeed, it is a quite useful method except in the empty-set case.

**Comment by JeffBezanson** [comment]
This is due to #35417. There we decided to prefer 2-argument, parseable output for empty collections, but maybe that's the wrong default for non-arrays.

**Comment by StephenVavasis** [comment]
Just for further information: the big string printed out by `show` for AbstractSet in my original post is not actually parsable to reconstruct the object, at least, not in the obvious way.   Below, I tried to feed the output back into the REPL and received an error.

```julia-repl
julia> SortedSet{Int}()
SortedSet{Int64, Base.Order.ForwardOrdering}(DataStructures.BalancedTree23{Int64, Nothing, Base.Order.ForwardOrdering}(Base.Order.ForwardOrdering(), DataStructures.KDRec{Int64, Nothing}[DataStructures.KDRec{Int64, Nothing}(1, 191898512, nothing), DataStructures.KDRec{Int64, Nothing}(1, 191898640, nothing)], DataStructures.TreeNode{Int64}[DataStructures.TreeNode{Int64}(1, 2, 0, 0, 12, 13)], 1, 1, Int64[], Int64[], BitSet([1, 2]), [32, 4, 10999411245313], [32, 4, 10999411245313]))

julia> SortedSet{Int64, Base.Order.ForwardOrdering}(DataStructures.BalancedTree23{Int64, Nothing, Base.Order.ForwardOrdering}(Base.Order.ForwardOrdering(), DataStructures.KDRec{Int64, Nothing}[DataStructures.KDRec{Int64, Nothing}(1, 191898512, nothing), DataStructures.KDRec{Int64, Nothing}(1, 191898640, nothing)], DataStructures.TreeNode{Int64}[DataStructures.TreeNode{Int64}(1, 2, 0, 0, 12, 13)], 1, 1, Int64[], Int64[], BitSet([1, 2]), [32, 4, 10999411245313], [32, 4, 10999411245313]))
ERROR: MethodError: no method matching DataStructures.BalancedTree23{Int64, Nothing, Base.Order.ForwardOrdering}(::Base.Order.ForwardOrdering, ::Vector{DataStructures.KDRec{Int64, Nothing}}, ::Vector{DataStructures.TreeNode{Int64}}, ::Int64, ::Int64, ::Vector{Int64}, ::Vector{Int64}, ::BitSet, ::Vector{Int64}, ::Vector{Int64})
Closest candidates are:
  DataStructures.BalancedTree23{K, D, Ord}(::Val{true}, ::Any, ::Ord, ::Bool) where {K, D, Ord<:Base.Order.Ordering} at c:\Users\vavasis\OneDrive - University of Waterloo\Julia_pkg_devdir\DataStructures.jl\src\balanced_tree.jl:989
  DataStructures.BalancedTree23{K, D, Ord}(::Ord) where {K, D, Ord<:Base.Order.Ordering} at c:\Users\vavasis\OneDrive - University of Waterloo\Julia_pkg_devdir\DataStructures.jl\src\balanced_tree.jl:134
Stacktrace:
 [1] top-level scope
   @ REPL[7]:1
```

**Comment by StephenVavasis** [comment]
The development branch mentioned in my original post has now become the master branch for DataStructures.jl.  So fixing the undesirable behavior reported in my original post is now slightly more pressing.

**Comment by vtjnash** [comment]
Seems like this was fixed in DataStructures.jl as mentioned above https://github.com/JuliaLang/julia/issues/45229#issuecomment-1120837990 (and verified locally now)

**Comment by StephenVavasis** [comment]
Can you reopen this issue?  It is not fixed.   See e.g., the below trace from how an empty SortedSet is displayed.  The "reopen" button in Github is not working for me.

— Steve Vavasis


***@***.***) pkg> add DataStructures#master
     Cloning git-repo `https://github.com/JuliaCollections/DataStructures.jl.git`
    Updating git-repo `https://github.com/JuliaCollections/DataStructures.jl.git`
   Resolving package versions...
    Updating `C:\Users\juliatest\.julia\environments\v1.11\Project.toml`
  [864edb3b] + DataStructures v0.19.0-DEV `https://github.com/JuliaCollections/DataStructures.jl.git#master`
    Updating `C:\Users\juliatest\.julia\environments\v1.11\Manifest.toml`
  [864edb3b] + DataStructures v0.19.0-DEV `https://github.com/JuliaCollections/DataStructures.jl.git#master`
  [bac558e1] + OrderedCollections v1.8.1
Precompiling project...
  2 dependencies successfully precompiled in 3 seconds. 46 already precompiled.

julia> using DataStructures

julia> s = SortedSet([1,2,3])
SortedSet{Int64, Base.Order.ForwardOrdering} with 3 elements:
  1
  2
  3

julia> s = SortedSet(Int[])
SortedSet{Int64, Base.Order.ForwardOrdering}(DataStructures.BalancedTree23{Int64, Nothing, Base.Order.ForwardOrdering}(Base.Order.ForwardOrdering(), DataStructures.KDRec{Int64, Nothing}[DataStructures.KDRec{Int64, Nothing}(1, 0, nothing), DataStructures.KDRec{Int64, Nothing}(1, 0, nothing)], DataStructures.TreeNode{Int64}[DataStructures.TreeNode{Int64}(1, 2, 0, 0, 0, 0)], 1, 1, Int64[], Int64[], BitSet([1, 2]), [2274487371976, 51539607583, 126888088198241], [2274486723904, 2274486720320, 2274486723008]))

julia>




________________________________
