### ISSUE TITLE
[1.8] norm of a Float16 vector crashes on Win64 (Windows 7)

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/julia#45736]
This crashes on Win64 for me on 1.8-rc1, and is what has been causing https://github.com/JuliaSparse/SparseArrays.jl/issues/147. I can't quite understand why it is non-deterministic on CI, but it fails reliably for me in my Win64 Windows 7 VM.

```
using LinearAlgebra
norm(rand(Float16, 5))
```

Doesn't fail through the debugger, which makes me believe that the issue is with codegen. Error log below, and seems like the missing half float conversion methods might be the culprit.

cc @Wimmerer @DilumAluthge

**Comment by ViralBShah** [comment]
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Viral>C:\Users\Viral\Desktop\julia-1.8.0-rc1\bin\julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.8.0-rc1 (2022-05-27)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> x = rand(Float16,5)
5-element Vector{Float16}:
 0.974
 0.526
 0.5166
 0.5273
 0.3027

julia> using LinearAlgebra

julia> norm(x)
JIT session error: Symbols not found: [ __gnu_f2h_ieee, __gnu_h2f_ieee ]
Failure value returned from cantFail wrapped call
Failed to materialize symbols: { (JuliaOJIT, { jfptr_mapreduce_impl_108, julia_m
apreduce_impl_107 }) }
UNREACHABLE executed at /cygdrive/c/buildbot/worker/package_win64/build/usr/incl
ude/llvm/Support/Error.h:782!

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

signal (22): SIGABRT
in expression starting at REPL[3]:1
crt_sig_handler at /cygdrive/c/buildbot/worker/package_win64/build/src\signals-w
in.c:93
raise at C:\Windows\system32\msvcrt.dll (unknown line)
abort at C:\Windows\system32\msvcrt.dll (unknown line)
.text$_ZN4llvm25llvm_unreachable_internalEPKcS1_j at C:\Users\Viral\Desktop\juli
a-1.8.0-rc1\bin\libLLVM-13jl.dll (unknown line)
cantFail<llvm::JITEvaluatedSymbol> at /cygdrive/c/buildbot/worker/package_win64/
build/usr/include/llvm/Support\Error.h:782 [inlined]
addModule at /cygdrive/c/buildbot/worker/package_win64/build/src\jitlayers.cpp:9
45
jl_add_to_ee at /cygdrive/c/buildbot/worker/package_win64/build/src\jitlayers.cp
p:1238
jl_add_to_ee at /cygdrive/c/buildbot/worker/package_win64/build/src\jitlayers.cp
p:1282
jl_add_to_ee at /cygdrive/c/buildbot/worker/package_win64/build/src\jitlayers.cp
p:1267
jl_add_to_ee at /cygdrive/c/buildbot/worker/package_win64/build/src\jitlayers.cp
p:1267
jl_add_to_ee at /cygdrive/c/buildbot/worker/package_win64/build/src\jitlayers.cp
p:1304 [inlined]
_jl_compile_codeinst at /cygdrive/c/buildbot/worker/package_win64/build/src\jitl
ayers.cpp:149
jl_generate_fptr_impl at /cygdrive/c/buildbot/worker/package_win64/build/src\jit
layers.cpp:327
jl_compile_method_internal at /cygdrive/c/buildbot/worker/package_win64/build/sr
c\gf.c:2072
jl_compile_method_internal at /cygdrive/c/buildbot/worker/package_win64/build/sr
c\gf.c:2019 [inlined]
_jl_invoke at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2350 [inl
ined]
ijl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:25
40
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1838 [in
lined]
do_call at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:126

eval_value at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:
215
eval_stmt_value at /cygdrive/c/buildbot/worker/package_win64/build/src\interpret
er.c:166 [inlined]
eval_body at /cygdrive/c/buildbot/worker/package_win64/build/src\interpreter.c:5
94
jl_interpret_toplevel_thunk at /cygdrive/c/buildbot/worker/package_win64/build/s
rc\interpreter.c:750
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\top
level.c:906
jl_toplevel_eval_flex at /cygdrive/c/buildbot/worker/package_win64/build/src\top
level.c:850
ijl_toplevel_eval at /cygdrive/c/buildbot/worker/package_win64/build/src\topleve
l.c:915 [inlined]
ijl_toplevel_eval_in at /cygdrive/c/buildbot/worker/package_win64/build/src\topl
evel.c:965
eval at .\boot.jl:368 [inlined]
eval_user_input at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib
\v1.8\REPL\src\REPL.jl:151
repl_backend_loop at C:\buildbot\worker\package_win64\build\usr\share\julia\stdl
ib\v1.8\REPL\src\REPL.jl:247
start_repl_backend at C:\buildbot\worker\package_win64\build\usr\share\julia\std
lib\v1.8\REPL\src\REPL.jl:232
#run_repl#47 at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1
.8\REPL\src\REPL.jl:369
run_repl at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.8\R
EPL\src\REPL.jl:355
jfptr_run_repl_64032.clone_1 at C:\Users\Viral\Desktop\julia-1.8.0-rc1\lib\julia
\sys.dll (unknown line)
#966 at .\client.jl:419
jfptr_YY.966_40867.clone_1 at C:\Users\Viral\Desktop\julia-1.8.0-rc1\lib\julia\s
ys.dll (unknown line)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1838 [in
lined]
jl_f__call_latest at /cygdrive/c/buildbot/worker/package_win64/build/src\builtin
s.c:774
#invokelatest#2 at .\essentials.jl:729 [inlined]
invokelatest at .\essentials.jl:726 [inlined]
run_main_repl at .\client.jl:404
exec_options at .\client.jl:318
_start at .\client.jl:522
jfptr__start_26007.clone_1 at C:\Users\Viral\Desktop\julia-1.8.0-rc1\lib\julia\s
ys.dll (unknown line)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1838 [in
lined]
true_main at /cygdrive/c/buildbot/worker/package_win64/build/src\jlapi.c:567
jl_repl_entrypoint at /cygdrive/c/buildbot/worker/package_win64/build/src\jlapi.
c:711
mainCRTStartup at /cygdrive/c/buildbot/worker/package_win64/build/cli\loader_exe
.c:59
BaseThreadInitThunk at C:\Windows\system32\kernel32.dll (unknown line)
RtlUserThreadStart at C:\Windows\SYSTEM32\ntdll.dll (unknown line)
Allocations: 803011 (Pool: 802628; Big: 383); GC: 1

C:\Users\Viral>
```

**Comment by Wimmerer** [comment]
I only have beta3 right now, but that does not fail for me on my machine. Let me try rc1

**Comment by ViralBShah** [comment]
BTW I am on Windows 7.

**Comment by giordano** [comment]
Can you try on master? There has been lots of movement about those functions lately

**Comment by ViralBShah** [comment]
Doesn't crash on the nightly!

**Comment by ViralBShah** [comment]
One of the things I realized as a result of chasing this was that in CI for packages, we always use `windows-latest`, `ubuntu-latest`, etc. But on the buildbots, we are using conservative versions. I think it would be useful for all the packages to run their tests on conservative versions of the OSes than the latest ones, which might help with such issues.

@DilumAluthge @staticfloat Would you guys agree with this broad assessment? Perhaps we can update `PkgTemplates.jl` to reflect this?

**Comment by DilumAluthge** [comment]
For most packages, I think it's perfectly fine to use `$OS-latest`. So I would not recommend changing PkgTemplates

But for stdlibs, and packages that were formerly stdlibs, it does make sense to use an older OS image.

**Comment by ViralBShah** [comment]
Why not just use conservative OS versions on everything? It is just better all around, isn't it? What's the right way to pick a conservative OS in GA (instead of -latest)?

**Comment by giordano** [comment]
One issue is that CI providers will remove support for older OS versions, and the entire ecosystem will always have to catch up with those changes.  It's rather annoying, especially for users not following much progress of CI providers.

**Comment by DilumAluthge** [comment]
> Why not just use conservative OS versions on everything? It is just better all around, isn't it? What's the right way to pick a conservative OS in GA (instead of -latest)?

Yeah, so actually those two questions are related in my mind. The reason that I'm reluctant to recommend this for all packages in the Julia ecosystem is that now package authors will need to edit their CI workflow files more frequently.

For example, to use an older Windows, replace windows-latest with windows-2016.

But the problem is that windows-2016 will not be available forever. Eventually, GitHub will remove that from the list of GitHub-hosted runners.

**Comment by ViralBShah** [comment]
Yes good point. And these are not old enough to trigger this issue, I believe. Trying older OSes in https://github.com/JuliaSparse/SparseArrays.jl/pull/164

**Comment by ViralBShah** [comment]
Would be nice if this list of OSes could somehow be pulled from a central place.

**Comment by DilumAluthge** [comment]
Perhaps we could send a feature request to GitHub to add aliases of the form `windows-oldest` or `windows-earliest`. That would take care of the ecosystem churn issue.

They already have aliases (`windows-latest` is an alias), so there is precedent.

**Comment by vchuravy** [comment]
I think the actual issue is fixed?

**Comment by ViralBShah** [comment]
No the issue remains - we are just working to avoid triggering it in SparseArrays CI.

**Comment by ViralBShah** [comment]
Doesn't crash on master - but does on 1.8-rc1.

**Comment by vchuravy** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/45627 for rc2
