### ISSUE TITLE
Error precompiling `SymbolicsPreallocationToolsExt`

### ISSUE THREAD

**Issue by IanButterworth** [JuliaLang/julia#53081]
This may have overlap with other open extensions issues, but here's a tracking issue to debug it.

A couple of things of note:
- `SymbolicsPreallocationToolsExt` doesn't actually fail its precompile job, just `@error`'s
- It looks like `SymbolicsPreallocationToolsExt` is being loaded in the precompile worker via a trigger before it specifically tries to precompile `SymbolicsPreallocationToolsExt` and I assume succeeds because the worker doesn't fail

```
(@v1.11) pkg> st
Status `~/.julia/environments/v1.11/Project.toml`
  [d236fae5] PreallocationTools v0.4.17
  [295af30f] Revise v3.5.13
  [0c5d862f] Symbolics v5.17.0 `~/.julia/dev/Symbolics`

(@v1.11) pkg> precompile
Precompiling project...
  21 dependencies successfully precompiled in 25 seconds. 122 already precompiled.
  1 dependency had output during precompilation:
┌ Symbolics → SymbolicsPreallocationToolsExt
│  ┌ Warning: Module SymbolicsPreallocationToolsExt with build ID ffffffff-ffff-ffff-0008-4f3de8c9c66b is missing from the cache.
│  │ This may mean SymbolicsPreallocationToolsExt [d479e226-fb54-5ebe-a75e-a7af7f39127f] does not support precompilation but is imported by a module that does.
│  └ @ Base loading.jl:2113
│  ┌ Error: Error during loading of extension SymbolicsPreallocationToolsExt of Symbolics, use `Base.retry_load_extensions()` to retry.
│  │   exception =
│  │    1-element ExceptionStack:
│  │    Error when precompiling module, potentially caused by a __precompile__(false) declaration in the module.
│  └ @ Base loading.jl:1380
└  
```

cc. @ChrisRackauckas

**Comment by IanButterworth** [comment]
ForwardDiff is an indirect dep of `PreallocationTools`. Maybe that's related
```
(@v1.11) pkg> why ForwardDiff
  PreallocationTools → ForwardDiff
  Symbolics → SymbolicUtils → LabelledArrays → ForwardDiff
```

**Comment by RaimundK** [comment]
The issue is still present.

**Comment by KristofferC** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/53972

**Comment by giordano** [comment]
This is still happening in v1.11.6, despite #53972 being backported to `v1.11.0-beta2`: https://github.com/LCSB-BioCore/SBML.jl/actions/runs/17397573638/job/49382878548?pr=272#step:7:341
```
           ✗ Symbolics → SymbolicsPreallocationToolsExt
  143 dependencies successfully precompiled in 327 seconds. 32 already precompiled.

ERROR: LoadError: The following 1 direct dependency failed to precompile:

SymbolicsPreallocationToolsExt --code-coverage=@/Users/runner/work/SBML.jl/SBML.jl --color=yes --check-bounds=yes --warn-overwrite=yes --depwarn=yes --inline=yes --startup-file=no --track-allocation=none --check-bounds=yes --compiled-modules=yes --depwarn=yes 

Failed to precompile SymbolicsPreallocationToolsExt [d479e226-fb54-5ebe-a75e-a7af7f39127f] to "/Users/runner/.julia/compiled/v1.11/SymbolicsPreallocationToolsExt/jl_KYs0jk".
ERROR: LoadError: UndefVarError: `ForwardDiff` not defined in `PreallocationTools`
Stacktrace:
 [1] include
   @ ./Base.jl:562 [inlined]
 [2] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
   @ Base ./loading.jl:2881
 [3] top-level scope
   @ stdin:6
in expression starting at /Users/runner/.julia/packages/Symbolics/qKoME/ext/SymbolicsPreallocationToolsExt.jl:1
in expression starting at stdin:
in expression starting at /Users/runner/work/_actions/julia-actions/julia-runtest/v1/test_harness.jl:25
```

**Comment by KristofferC** [comment]
Looks like a completely different error?
