### ISSUE TITLE
Code warntype should show print the unstable SSA values in red/yellow

### ISSUE THREAD

**Issue by gbaraldi** [JuliaLang/julia#54028]
If you have some code like
```julia
julia> function foo(x)
       y = x[1]
       sin(y)
       end
foo (generic function with 1 method)

julia> code_warntype(foo, (Vector{Any},), optimize=true)
```
<img width="697" alt="image" src="https://github.com/JuliaLang/julia/assets/28694980/1b0d6e80-85d6-4b4a-8b11-80cfd20aaf67">

It would be useful if `%17` was printed in red

**Comment by arhik** [comment]
I don't know the consequences of directly interpolating expression [here](https://github.com/arhik/julia/blame/a74deeee053a7c33960cd85c28a97f6464d6a732/base/compiler/ssair/show.jl#L84) but here is the first attempt at it. Any guiding information on coverage of IR statements in code changes made will be appreciated.


![Screenshot 2024-04-29 at 12 45 15 AM](https://github.com/JuliaLang/julia/assets/5755530/d61be908-00f0-4096-8500-9a1bfcef6d9b)

**Comment by arhik** [comment]
@gbaraldi Should line 19 be highlighted too ?

**Comment by arhik** [comment]
![Screenshot 2024-05-17 at 8 16 09 AM](https://github.com/JuliaLang/julia/assets/5755530/d5655496-d812-4d2a-9162-d652a783ac68)

**Comment by joseeloren** [comment]
I was checking a good first issue to start with, and I think this is solved already. Am I right?

**Comment by arhik** [comment]
@joseeloren Its partially solved and need tests. Also, I have commits on my local setup. I am struggling to make time, and I don't recollect if I have it all resolved. If you don't see any commits from me by coming weekend it's all yours. 

In case you end up taking this up, the existing code is good enough for adding tests directly (I think it doesn't cover few node types yet and that can be next PR or next set of commits after passing tests for commits made so far).

**Comment by KeshavSingh2703** [comment]
Hey there, I would like to take this issue

**Comment by joseeloren** [comment]
Hi @KeshavSingh2703 I was working on this on #55435

**Comment by KeshavSingh2703** [comment]
The current status includes partial tests and coverage for specific cases, though it might still need further refinements and checks for completeness.
