### ISSUE TITLE
Regression in latency from loading StyledStrings

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/julia#57997]
On e89294840e5 (Version 1.12.0-DEV.2136 (2025-03-26))

```julia
julia> using Pkg

julia> Pkg.UPDATED_REGISTRY_THIS_SESSION[] = true
true

julia> ENV["JULIA_PKG_PRECOMPILE_AUTO"] = 0
0

julia> @time @eval Pkg.add("Example")
  Resolving package versions...
No packages added to or removed from `~/.julia/environments/v1.12/Project.toml`
No packages added to or removed from `~/.julia/environments/v1.12/Manifest.toml`
 0.290076 seconds (1.25 M allocations: 77.722 MiB, 5.93% gc time, 89.65% compilation time: 79% of which was recompilation)
```

On (c175ace780d72340c065)  `1.12.0-beta1`

```julia
julia> using Pkg

julia> Pkg.UPDATED_REGISTRY_THIS_SESSION[] = true
true

julia> ENV["JULIA_PKG_PRECOMPILE_AUTO"] = 0
0

julia> @time @eval Pkg.add("Example")
   Resolving package versions...
No packages added to or removed from `~/.julia/environments/v1.12/Project.toml`
No packages added to or removed from `~/.julia/environments/v1.12/Manifest.toml`
  1.267370 seconds (6.99 M allocations: 377.474 MiB, 7.84% gc time, 98.18% compilation time: 82% of which was recompilation)
```

**Comment by KristofferC** [comment]
It seems it is StyledStrings that causes a lot of this (as it always is). I made a branch so that StyledStrings is not loaded by default by the REPL (and deps) in https://github.com/JuliaLang/julia/tree/kc/no_styled. And we get:

No StyledStrings:
```
julia> using Pkg

julia> Pkg.UPDATED_REGISTRY_THIS_SESSION[] = true;

julia> ENV["JULIA_AUTO_PRECOMPILE"] = 0;

julia> @time @eval Pkg.add("Example")
   Resolving package versions...
No packages added to or removed from `~/.julia/environments/v1.12/Project.toml`
No packages added to or removed from `~/.julia/environments/v1.12/Manifest.toml`
  0.443519 seconds (2.97 M allocations: 170.194 MiB, 6.73% gc time, 94.00% compilation time: 68% of which was recompilation)
```

With StyledStrings

```
julia> using StyledStrings

julia> using Pkg

julia> Pkg.UPDATED_REGISTRY_THIS_SESSION[] = true;

julia> ENV["JULIA_AUTO_PRECOMPILE"] = 0;

julia> @time @eval Pkg.add("Example")
   Resolving package versions...
No packages added to or removed from `~/.julia/environments/v1.12/Project.toml`
No packages added to or removed from `~/.julia/environments/v1.12/Manifest.toml`
  1.769898 seconds (11.39 M allocations: 610.943 MiB, 7.10% gc time, 98.41% compilation time: 76% of which was recompilation)
```

cc @tecosaur, @topolarity

**Comment by jakobnissen** [comment]
Thanks for digging into this. If I understand correctly, this is not due to inference problems in the iobuffer code (which I believe should all be well-inferred), but instead inference issues in AnnotatedStrings, or elsewhere in Base.

**Comment by KristofferC** [comment]
I don't know yet why that specific commit caused the issue. But reverting that commit on my branch that doesn't load StyledStrings doesn't change any timings so it doesn't seem like there is anything bad with that code on its own.

**Comment by tecosaur** [comment]
Wow, that's quite a large regression. Is there any way to better identify what is behind this change? I'm very sympathetic to the headaches with StyledStrings involved here, I just have a hard time identifying actionable changes to improve the situation. The only change involving StyledStrings / the annotated code that's occurred recently is #57912, but it's hard for me to see how that could be implicated here. The core issue seems to be the `print`/`write` methods you identify here, and the obvious solution in my mind is for them not to be in StyledStrings, but that's not my decision.

This leaves us with (1) abandoning the idea of a stdlib to manage rich content better across the stdlib, as per #57998 (2) adjusting the base/stdlib split (3) doing some slightly tricky work to make it work despite the split (which is what I've been speaking with Cody about, and what I sense you've run out of patience waiting for Kristoffer).

**Comment by topolarity** [comment]
> I just have a hard time identifying actionable changes to improve the situation.

The actionable change is to fix the StyledStrings type-piracy.

> The core issue seems to be the `print`/`write` methods you identify here, and the obvious solution in my mind is for them not to be in StyledStrings, but that's not my decision.

Yes, we'll need to fix these soon - it should have been done earlier in the 1.12 release cycle, but let's get it done now and relieve some pain for folks

**Comment by KristofferC** [comment]
>  I just have a hard time identifying actionable changes to improve the situation

It's ok, https://github.com/JuliaLang/julia/issues/57998 is very actionable, and I can take that on.

**Comment by KristofferC** [comment]
Fixed with inference barrier

**Comment by nsajko** [comment]
I still see lots of invalidation due to type piracy when loading `StyledStrings` in a fresh session, on current `master`, 6568124d5b. See JSON file:

* [invalidations_on_loading_StyledStrings_on_master_6568124d5b.json](https://github.com/user-attachments/files/21984296/invalidations_on_loading_StyledStrings_on_master_6568124d5b.json)

**Comment by jakobnissen** [comment]
Ping @tecosaur - I know you have a lot on your plate, but has there been any progress on the long-term latency fix for StyledStrings?

**Comment by tecosaur** [comment]
> I still see lots of invalidation due to type piracy when loading StyledStrings in a fresh session, on current master, https://github.com/JuliaLang/julia/commit/6568124d5bef0a0f7d83c15242adb84f54fc47f9. See JSON file:

Thanks for this @nsajko, if I'm interpreting that correctly, it looks like all of the invalidations are from this one function? https://github.com/JuliaLang/StyledStrings.jl/blob/main/src/legacy.jl#L126

At a glance, it seems like that simply wasn't covered in #58112, but should be able to be resolved the same way.

> Ping tecosaur - I know you have a lot on your plate, but has there been any progress on the long-term latency fix for StyledStrings?

@jakobnissen conceptually, yes, practically no. My current priorities are something like:

1. Adjust to more of the changes in JuliaSyntax 1.0 in JuliaSyntaxHighlighting (errors/breakage was sorted out a while back, but there are some undesired changes in behaviour)
2. Finish up some packages that are being spun off from my work (I want to be able to stop thinking about them)
3. PR the fancy REPL history picker I've got 95% of the way to being PR-able (https://github.com/tecosaur/REPLChronicle.jl)
4. Actually start work on scoping + concrete + less invalidating by-design changes to StyledStrings that Cody and I have started talking about. These are changes that don't inhibit work like (3), but I think are key to StyledStrings living up to its full potential.
5. Other stuff, like the potential short-string optimisation, path type proposal, int parsing speedup, other packages I'm working on, etc. 

If I had a few weeks I could put aside to work on Julia stuff, I'd be much happier with my to-do list (I might actually be part-way through No.4 by now), but unfortunately life keeps happening 🙃

**Comment by nsajko** [comment]
> Thanks for this @nsajko, if I'm interpreting that correctly, it looks like all of the invalidations are from this one function?

You're welcome, I'm glad to help. Yeah, the single pirate method looks like it's causing all the recorded invalidation from `using StyledStrings`.

**Comment by KristofferC** [comment]
So can we add the remaining function (`printstyled`?) to the list of inference hiding? @tecosaur?

**Comment by tecosaur** [comment]
Yep, absolutely. I've just had an unfortunately busy last few weeks, but I should be able to spin up a PR this coming weekend.

Last week I finally managed to finish the remaining work to adjust to JuliaSyntax 1.0 in JuliaSyntaxHighlighting. It would be good to get both these changes in the next RC.

**Comment by KristofferC** [comment]
Bump on this (@tecosaur). Is there anything that needs to be done on the StyledString side or is it only here that the definition needs to be added?

**Comment by tecosaur** [comment]
There is a little, and I've just done that and spun up a PR: #59596.

**Comment by nsajko** [comment]
With 406d37b79df I do not see any more invalidation on `using StyledStrings`.

**Comment by tecosaur** [comment]
That's great to hear, thanks for checking (and thanks to Kristoffer for sorting that PR).
