### ISSUE TITLE
hashing types consistently in different processes

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaLang/julia#5849]
Types are generally hash-consed, so their memory addresses are used in computing their object_ids, since this is fast and easy. However this means Dicts with types in keys do not work inside the system image. For example https://github.com/timholy/HDF5.jl/pull/78.

We should probably hash types the same between runs of the same image, and _maybe_ (though less likely) hash them the same globally (e.g. based on `hash(string(T))`).

EDIT: Note this doesn't affect `ObjectIdDict` since those are rehashed automatically when deserialized.

**Comment by JeffBezanson** [comment]
The missing case here is UnionAlls and TypeVars. We also have e.g.

```
julia> (Array{T} where T) === (Array{T} where T)
false
```

since TypeVars are compared by address. We could fix this by building a type environment during `egal` and `object_id`.

**Comment by StefanKarpinski** [comment]
Wouldn't this be a non-breaking change? Is it required for anything else that is blocking?

**Comment by JeffBezanson** [comment]
Well, I implemented it already, but it does change the behavior of `===` and `object_id` so it's technically breaking.

**Comment by vtjnash** [comment]
This doesn't implement type-equality-based-hashing (assuming that's even possible), so it could still get different answers for `Vector{Union{Tuple{A}, Tuple{B}}}` and `Vector{Tuple{Union{A, B}}}` in different processes, even those are the same leaftype (and type equal, and would thus be normalized by apply_type)

**Comment by JeffBezanson** [comment]
That's fine --- there are far fewer use cases for that. The use cases we care about are e.g. serializing a structure and having it behave the same on the other end.
