### ISSUE TITLE
__chkstk function (LLVM36)

### ISSUE THREAD

**Issue by vtjnash** [JuliaLang/julia#9339]
with LLVM35, it looks like we need to provide llvm with a __chkstk_ms function?

```
$ make -C test numbers
make: Entering directory '/home/julia/julia64/test'
    JULIA test/numbers
     * numbers
LLVM ERROR: Program used external function '___chkstk_ms' which could not be resolved!
/bin/sh: line 1:  2628 Segmentation fault      /home/julia/julia64/usr/bin/julia.exe --check-bounds=yes -f ./runtests.jl numbers
Makefile:9: recipe for target 'numbers' failed
make: *** [numbers] Error 139
make: Leaving directory '/home/julia/julia64/test'
```

**Comment by Keno** [comment]
This may have been fixed upstream in http://reviews.llvm.org/rL227519.

**Comment by tkelman** [comment]
On 3.7, yeah? Should keep an eye on the 3.6 branch to see whether it gets backported. If not we can probably carry the patch locally if we use 3.6.

**Comment by SimonDanisch** [comment]
Guess this is not completely fixed on cygwin:
```
reduce.jl
intset.jl
dict.jl
iterator.jl
inference.jl
LLVM ERROR: Program used external function '___chkstk_ms' which could not be resolved!
LLVM ERROR: Program used external function '___chkstk_ms' which could not be resolved!
error during bootstrap:
RtlLockHeap at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
RtlEnterCriticalSection at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
utf8proc_NFKC at C:\cygwin64\home\S\julia\usr\bin\libjulia.dll (unknown line)
utf8proc_NFKC at C:\cygwin64\home\S\julia\usr\bin\libjulia.dll (unknown line)
utf8proc_NFKC at C:\cygwin64\home\S\julia\usr\bin\libjulia.dll (unknown line)
utf8proc_NFKC at C:\cygwin64\home\S\julia\usr\bin\libjulia.dll (unknown line)
utf8proc_NFKC at C:\cygwin64\home\S\julia\usr\bin\libjulia.dll (unknown line)
utf8proc_NFKC at C:\cygwin64\home\S\julia\usr\bin\libjulia.dll (unknown line)
jl_generate_fptr at /home/S/julia/src\codegen.cpp:749
jl_trampoline_compile_function at /home/S/julia/src\builtins.c:968
jl_apply_generic at /home/S/julia/src\gf.c:1676
unknown function (ip: 0000000007BE00EE)
jl_apply_generic at /home/S/julia/src\gf.c:1651
jl_f_apply at /home/S/julia/src\builtins.c:486
unknown function (ip: 000000000C0625D4)
jl_apply at /home/S/julia/src\julia.h:1262
unknown function (ip: 000000000C061220)
jl_apply at /home/S/julia/src\julia.h:1262
unknown function (ip: 000000000C060699)
jl_apply at /home/S/julia/src\julia.h:1262
unknown function (ip: 0000000008FB8DB7)
jl_apply at /home/S/julia/src\julia.h:1262
unknown function (ip: 0000000007FC0A27)
jl_apply at /home/S/julia/src\julia.h:1262
unknown function (ip: 000000000AA5009E)
jl_apply at /home/S/julia/src\julia.h:1262
unknown function (ip: 000000000A6F1CFC)
jl_apply_generic at /home/S/julia/src\gf.c:1651
unknown function (ip: 000000000A6B0FF8)
jl_apply at /home/S/julia/src\julia.h:1262
unknown function (ip: 000000000A1D0B00)
...
```
commit 50cf3537c548b15e9e708f31771ea7b78c101a45
```
System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
```

**Comment by tkelman** [comment]
LLVM version _._?

**Comment by SimonDanisch** [comment]
Ah yeah, 3.6.0

**Comment by tkelman** [comment]
Can you tell whether or not that was built including the patch from https://github.com/JuliaLang/julia/blob/master/deps/win64-allocas-llvm-3.6.0.patch ? I think we got those patches backported for 3.6.1, should also be in 3.6.2. Or release_37 branch is in RC mode so should hopefully be slow-moving until 3.7.0 is ready?
