### ISSUE TITLE
*.mem files not written out for user source code on Windows 7

### ISSUE THREAD

**Issue by PetrKryslUCSD** [JuliaLang/julia#9654]
Tried memory allocation debugging with --track-allocation=user and --track-allocation=all with version 0.3.4 and 0.4: Problem – *.mem files not written out for user source code on Windows 7. *.mem files written out only for Julia core files.

**Comment by ihnorton** [comment]
Probably dupe of #9581 (but there might be some other windows-specific issue)

**Comment by timholy** [comment]
If it's a recent build, #9581 together with 357666536fe34fc30f2c1ffa5a11d16e227cdba6 seems to have fixed that problem. But perhaps those aren't in your build? Can you provide the versioninfo()? (Details were in that link I sent you.)

**Comment by PetrKryslUCSD** [comment]
On Tue, Jan 6, 2015 at 7:15 PM, Tim Holy <notifications@github.com> wrote:

> 665
> <https://github.com/JuliaLang/julia/commit/357666536fe34fc30f2c1ffa5a11d16e227cdba6>
> seems to have fixed that problem. But perhaps those aren't in your build?
> Can you provide the versioninfo()? (Details were in that lin


julia> versioninfo()
Julia Version 0.4.0-dev+2070
Commit f2b5a11 (2014-12-11 10:19 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-2640M CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3


-- 
Petr Krysl
Professor
University of California, San Diego
Skype: Petr.Krysl.UCSD.EDU, Office: 858-822-4787
http://hogwarts.ucsd.edu/~pkrysl/

**Comment by jiahao** [comment]
The referenced commit is 3 days old; looks like you can try updating and try again.

**Comment by timholy** [comment]
In order to get the full benefit of the fixes in #9581 & Jeff's commit, you need at least `0.4.0-dev+2473`.

**Comment by PetrKryslUCSD** [comment]
Installed latest dev. Still no .mem files written out for "user" source
code. The base .mem files are produced for =all option.

Petr

On Tue, Jan 6, 2015 at 9:11 PM, Tim Holy <notifications@github.com> wrote:

> In order to get the full benefit of the fixes in #9581
> <https://github.com/JuliaLang/julia/pull/9581> & Jeff's commit, you need
> at least 0.4.0-dev+2473.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaLang/julia/issues/9654#issuecomment-68979762>.
>



-- 
Petr Krysl
Professor
University of California, San Diego
Skype: Petr.Krysl.UCSD.EDU, Office: 858-822-4787
http://hogwarts.ucsd.edu/~pkrysl/

**Comment by timholy** [comment]
Current `versioninfo()`? Can you try with a really simple test?
```
function f(n)
    m = 2*n  # first line is weird if called from REPL, so do something simple
    A = Array(Float64, n)
end

f(20)
Profile.clear_malloc_data()
f(20)
exit()
```

**Comment by quinnj** [comment]
```julia
julia> versioninfo()
Julia Version 0.4.0-dev+2541
Commit e5b4e0b* (2015-01-07 04:56 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```
Ran julia with `julia --track-allocation=user`.
Then ran @timholy's example from above and didn't see any *.mem files in the directory that I started julia in.

**Comment by dhoegh** [comment]
I have also bumped into this issue a month ago on 0.3.2. Maybe it is I coincidence but I have also Sandybridge cpu and I am on windows.

**Comment by timholy** [comment]
Can anyone out there in Windows-land make this work, or is this broken on all Windows machines?

I can't do much to debug this myself, unfortunately. The core logic is [here](https://github.com/JuliaLang/julia/blob/d74d8cce708faf1faab937b8de9c6dfaffb83db9/src/codegen.cpp#L951-L973).

@PetrKryslUCSD, if I remember correctly you're trying to solve what you suspect to be a type-stability problem. Another approach (available only on recent 0.4) is [`@code_warntype`](http://docs.julialang.org/en/latest/manual/performance-tips/#code-warntype).

**Comment by PetrKryslUCSD** [comment]
Tim,

I have resolved the type instability successfully  some time ago (12/16):
https://groups.google.com/forum/?fromgroups=#!searchin/julia-users/Krysl|sort:relevance/julia-users/dgNqrJBZx5U/oGeXMZFjToMJ

With some recent improvements added onto the implementation reported  on
12/16, the Julia solver is now  three seconds faster than the commercial
FEA package with the fastest  sparse-system solver available in that
package (13 seconds versus 16 seconds).

Nevertheless, I'm still curious about the remaining few percent  of
performance  that might be available  if the amount of
allocated/deallocated memory  could be reduced.   I would like to
establish  effective programming patterns for the future work of porting  a
substantial finite element package to Julia. That is what I would like to
accomplish with getting the memory allocation debugging  working.

Thanks very much for your help.

Petr



On Wed, Jan 7, 2015 at 4:02 AM, Tim Holy <notifications@github.com> wrote:

> Can anyone out there in Windows-land make this work, or is this broken on
> all Windows machines?
>
> I can't do much to debug this myself, unfortunately. The core logic is
> here
> <https://github.com/JuliaLang/julia/blob/d74d8cce708faf1faab937b8de9c6dfaffb83db9/src/codegen.cpp#L951-L973>
> .
>
> @PetrKryslUCSD <https://github.com/PetrKryslUCSD>, if I remember
> correctly you're trying to solve what you suspect to be a type-stability
> problem. Another approach (available only on recent 0.4) is @code_warntype
> <http://docs.julialang.org/en/latest/manual/performance-tips/#code-warntype>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaLang/julia/issues/9654#issuecomment-69013117>.
>



-- 
Petr Krysl
Professor
University of California, San Diego
Skype: Petr.Krysl.UCSD.EDU, Office: 858-822-4787
http://hogwarts.ucsd.edu/~pkrysl/

**Comment by tkelman** [comment]
dunno what's wrong here, but cc me

also putting this here for github search purposes since it's a related term: coverage

**Comment by vtjnash** [comment]
the more relevant code is just above that
https://github.com/JuliaLang/julia/blob/d74d8cce708faf1faab937b8de9c6dfaffb83db9/src/codegen.cpp#L894-L940

it probably doesn't like that we try to open a unix-style absolute path there, which most certainly doesn't exist

**Comment by tkelman** [comment]
There is an [`isabspath` in `src/init.c`](https://github.com/JuliaLang/julia/blob/d74d8cce708faf1faab937b8de9c6dfaffb83db9/src/init.c#L792-L811), though it's not exported so I'm having trouble using it directly as-is from codegen.cpp. Could duplicate the logic, it's not that long.

**Comment by vtjnash** [comment]
is this fixed now?

**Comment by tkelman** [comment]
Has anything changed in the past 10 days since #10102 was reported that would be likely to fix this? I don't think it's fixed yet.

**Comment by dhoegh** [comment]
I just tested it on latest master `0.4.0-dev+3353` and it is working. Then I tried it on `0.4.0-dev+2818` where it did produce a `.mem` file but the allocation numbers where just zero.

**Comment by dhoegh** [comment]
It did not work on `0.3.5` either.

**Comment by tkelman** [comment]
No kidding... what are the sha's for those versions?

**Comment by dhoegh** [comment]
```
 Version 0.4.0-dev+2818 (2015-01-19 18:50 UTC)
 Commit 196544c (27 days old master)
```
```
 Version 0.4.0-dev+3353 (2015-02-14 17:08 UTC)
 Commit 0179028* (1 day old master)
 x86_64-w64-mingw32
```

**Comment by tkelman** [comment]
What do you know, this does look fixed on latest master. If I was the one who fixed it then I must've been testing something incorrectly. The numbers look a little odd, but that might just be inlining and sys.dll confusing things.

**Comment by dhoegh** [comment]
If it is possible it would be nice to backport the fix to 0.3.

**Comment by tkelman** [comment]
Yes, it would. That first requires determining what the fix was, then deciding whether or not it is appropriate to backport.

**Comment by tkelman** [comment]
whoops, sorry, it was fixed in 69c58535b486a0b59aea97d247058c2b4d36be16 - let's see how much of that surrounding code has changed, whether it's backport-able

**Comment by tkelman** [comment]
I'll just manually copy over `isabspath` from master and make the same change, the `write_log_data` function is in a different file on 0.3. Sorry for not realizing the bug was exactly the same on 0.3 and backporting this sooner.
