### ISSUE TITLE
effect-free (asserting) calls may be incorrectly omitted for inline functions

### ISSUE THREAD

**Issue by yuyichao** [JuliaLang/julia#9765]
typeassert is sometimes removed incorrectly for arguments of inline functions.

``` julia
julia> function f(::Int)
           return 1
       end
f (generic function with 1 method)

julia> 

julia> function f(::Float64)
           return 2
       end
f (generic function with 2 methods)

julia> 

julia> function g(x)
           a = x > 0 ? 1.0 : 1
           if !isa(a, Int)
               return f(a::Int)
           else
               return f(a::Float64)
           end
       end
g (generic function with 1 method)

julia> 

julia> println(@code_typed g(1))
Any[:($(Expr(:lambda, Any[:x], Any[Any[:a],Any[Any[:x,Int64,0],Any[:a,Any,2]],Any[]], :(begin  # none, line 2:
        unless (top(slt_int))(0,x::Int64)::Bool goto 0
        a = 1.0
        goto 1
        0: 
        a = 1
        1:  # line 3:
        unless (top(box))(Bool,(top(not_int))(isa(a::Union(Int64,Float64),Int)::Bool)) goto 2 # line 4:
        return 1
        goto 3
        2:  # line 6:
        return 2
        3: 
    end::Int64))))]

julia> println(g(1))
1

julia> println(g(-1))
2
```

P.S. As recently brought up on the dev list, it would be nice to have a `@inbounds` equivalent for `typeassert` to be used (correctly) in this case.

**Comment by yuyichao** [comment]
In case it's confusing, there's a `!` before the `isa(a, Int)` and the type assert in the branches are reversed.

**Comment by vtjnash** [comment]
good catch.

we are incorrectly asserting that `typeassert` is `effect_free` (https://github.com/JuliaLang/julia/blob/master/base/inference.jl#L1963) and using that to eliminate the unused argument (https://github.com/JuliaLang/julia/blob/master/base/inference.jl#L2465-L2467)

**Comment by vtjnash** [comment]
actually, this is a more general issue with `effect_free`. it's return value is correct in the case where these intrinsics succeed, but are incorrect in cases where these calls might fail. we might need a "isvalid_intrinsic_call" filter function that can be used to test a `t_func` call signature to indicate whether the intrinsic call will/may/won't succeed.

**Comment by yuyichao** [comment]
@vtjnash Is this what you mean?

```
julia> f(::Bool) = 1
f (generic function with 1 method)

julia> g() = f(isa(1, 1))
g (generic function with 1 method)

julia> @code_typed g()
1-element Array{Any,1}:
 :($(Expr(:lambda, Any[], Any[Any[],Any[],Any[],Any[]], :(begin  # none, line 1:
        return 1
    end::Int64))))

julia> g()
1
```

**Comment by vtjnash** [comment]
yeah, that's a fun example of the same

**Comment by KristofferC** [comment]
I now get:

```
julia> println(g(1))
ERROR: TypeError: g: in typeassert, expected Int64, got Float64
 in g(::Int64) at ./REPL[3]:4

julia> println(g(-1))
ERROR: TypeError: g: in typeassert, expected Float64, got Int64
 in g(::Int64) at ./REPL[3]:6
```

does this mean it is fixed?

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/issues/9765#issuecomment-94605126 is not fixed.
