### ISSUE TITLE
Incorrect line number for BoundsError

### ISSUE THREAD

**Issue by phobon** [JuliaLang/julia#9811]
arrtest.jl:
```
function arrtest(N)
    arr = zeros(3)
    for i=1:3
        arr[i] = 1.
    end
    for j=1:N
        arr[j] = 2.
    end
    arr
end
```
```
julia> include("arrtest.jl")
arrtest (generic function with 1 method)

julia> arrtest(5)
ERROR: BoundsError: attempt to access 3-element Array{Float64,1}:
 2.0
 2.0
 2.0
  at index [4]
 in arrtest at /.../arrtest.jl:4
```
Notice the error is reported at line 4 when it actually happens on line 7.

**Comment by nalimilan** [comment]
Lines 4 and 7 share the same assembly code for the bounds error handling. Looks like a too aggressive optimization.

```asm
Source line: 4 # Bounds error on line 4 goes here
L282:	mov	RCX, RSP
	lea	RSI, QWORD PTR [RCX - 16]
	mov	RSP, RSI
	inc	RAX
	jmpq	L318
L300:	mov	EAX, 1
Source line: 7 # Bounds error on line 7 goes here
	sub	RAX, RCX
	mov	RCX, RSP
	lea	RSI, QWORD PTR [RCX - 16]
	mov	RSP, RSI
Source line: 4 # Notice how line 7 bounds error also ends up here
L318:	mov	QWORD PTR [RCX - 16], RAX
	movabs	RAX, jl_bounds_error_ints
	mov	EDX, 1
	call	RAX
```

**Comment by nalimilan** [comment]
Actually you can get the same bug with an even simpler function:
```julia
function f()
    arr = zeros(3)
    arr[2]
    arr[4]
end
```

**Comment by phobon** [comment]
Happened to check and this is fixed on master. Doing a bisect suggests it was fixed in commit https://github.com/JuliaLang/julia/commit/adc0813c05c4cbe1bbc87e78629392ea64972907.

**Comment by andyferris** [comment]
I'm still getting this kind of (quite annoying) line-number mistake on 0.4.2. Out of curiosity, will this bugfix be backported?

**Comment by timholy** [comment]
Seems unlikely. Check out the PR that it appeared in, #11973.

**Comment by andyferris** [comment]
OK, thanks. Though incorrect line number for errors is definitely a bug "in practice" that makes fixing *my* bugs much harder, to quote @JeffBezanson in https://github.com/JuliaLang/julia/pull/11973#issuecomment-140196561:

> Good to merge this into master, but I don't yet see a compelling reason to backport it. If we encounter a bug in 0.4 *in practice* that's fixed by this, we can weigh at that point whether it's better to backport or do a more minimal patch against 0.4.

Of course, I also understand significant effort is required for backports.

**Comment by tkelman** [comment]
ref #13851, we may try a limited backport of a small part of https://github.com/JuliaLang/julia/pull/13491/files#diff-6d4d21428a67320600faf5a1a9f3a16aR5911 next time around, if I'm less busy and can run PackageEvaluator on it. The other commit from that same PR wound up being quite breaking, so I've been hesitant to try again. Good reason to keep PR's small, isolated and independent.

**Comment by andyferris** [comment]
Indeed. Thanks @tkelman, it would be great. :)
